<script type="text/javascript">

$(document).ready(function(){
    
    loadappdiv('/Tbls-Mgmt/?tbl=gxt_audit',null,'#logsdata');

});

</script>

<div class="heading-block" style="margin-bottom:25px;">
    <span class="left" style="font-size:1.5em;font-weight:bold;">
    App Logs
    </span>

    <span class="right">
    <a href="javascript:;" onclick="loadappdiv('/Tbls-Mgmt/?tbl=gxt_audit',null,'#logsdata');"><span class="ui-icon ui-icon-calculator" style="vertical-align:middle;display:inline-block;"></span> Audit Entries</a>
    &nbsp;|&nbsp;
    <a href="javascript:;" onclick="loadappdiv('/Logs-Mgmt/lstsyslogs',null,'#logsdata');"><span class="ui-icon ui-icon-flag" style="vertical-align:middle;display:inline-block;"></span> System Logs</a>
    </span>
</div>

<br clear="all">

<div id="logsdata">
</div>