{if $smarty.request.type!="history"}
<script type="text/javascript">
$(document).ready(function(){

    $('#all_history .file').click(function() {
        $('#all_history').html('{$smarty.const._MSG_WAIT_SM_}');
        $('#all_history').load('locks?kbguid={$smarty.request.kbguid}&type=history');
    });

});
</script>
{/if}

<div class="column left">
    &nbsp;<img src="{$smarty.const._IMG_LOCK_SM_}" alt="{$smarty.const._LBL_LOCK_}" title="{$smarty.const._LBL_LOCK_}">
    {if $smarty.request.type!="history"}
    {$lL.__list_of_active_locks__}.
    {else}
    {$lL.__object_s_locking_history__}.
    {/if}
</div>
<div class="column right">
    &nbsp;{$resultset|@count} {$lL.__row_s___}
</div>

<br clear="all">

<table width="100%" align="center" class="list">
<thead>
    {if $smarty.request.type!="history"}
    <tr><th>{$lL.__object__}</th><th>{$lL.__username__}</th><th>{$lL.__locked_since__} &darr;</th></tr>
    {else}
    <tr><th>{$lL.__object__}</th><th>{$lL.__locked_on__} &darr;<br>{$lL.__by_user__}</th><th>{$lL.__released_on__}<br>{$lL.__by_user__}</th></tr>
    {/if}
</thead>
<tbody>
    {foreach from=$resultset key=k item=rec}
    <tr class='{cycle values="odd,even"}'>
        {if $smarty.request.type!="history"}
            <td>&nbsp;<img src="../img/gx/objclass/{$gx_objcls[$rec.objcls].small}.png" title="{$gx_objcls[$rec.objcls].long}">&nbsp;{$rec.objnam}</td>
            <td>&nbsp;{$InProve_Smarty->guid2name('gxt_users', $rec.setuserguid)}</td>
            <td align="center">{$InProve_Smarty->ts2str($rec.setts)}</td>
        {else}
            <td>&nbsp;<img src="../img/gx/objclass/{$gx_objcls[$rec.objcls].small}.png" title="{$gx_objcls[$rec.objcls].long}">&nbsp;{$rec.objnam}</td>
            <td align="center">{$InProve_Smarty->ts2str($rec.setts)}<br>{$InProve_Smarty->guid2name('gxt_users', $rec.setuserguid)}</td>
            <td align="center">{$InProve_Smarty->ts2str($rec.unsetts)}<br>{$InProve_Smarty->guid2name('gxt_users', $rec.unsetuserguid)}</td>
        {/if}
    </tr>
    {/foreach}
</tbody>
</table>

{if $smarty.request.type!="history"}
<span id="all_history">
    <span class="file">
    {$InProve_Smarty->msg("ui-icon-zoomin","{$lL.__click_to_see_all_locking_history__}.")}
    </span>
</span>
<br clear="all">
{/if}