{if $smarty.request.type!="history"}
<script type="text/javascript">
$(document).ready(function(){

    $('#all_history .file').click(function() {
        $('#all_history').html('{$smarty.const._MSG_WAIT_SM_}');
        $('#all_history').load('locks?kbguid={$smarty.request.kbguid}&type=history');
    });

});
</script>
{/if}

<div class="column left">
    &nbsp;<img src="{$smarty.const._IMG_LOCK_SM_}" alt="{$smarty.const._LBL_LOCK_}" title="{$smarty.const._LBL_LOCK_}">
    {if $smarty.request.type!="history"}
    __LNG__List of active locks__LNG__.
    {else}
    __LNG__Object's locking history__LNG__.
    {/if}
</div>
<div class="column right">
    &nbsp;{$resultset|@count} __LNG__row(s)__LNG__
</div>

<br clear="all">

<table width="100%" align="center" class="list">
<thead>
    {if $smarty.request.type!="history"}
    <tr><th>__LNG__Object__LNG__</th><th>__LNG__Username__LNG__</th><th>__LNG__Locked Since__LNG__ &darr;</th></tr>
    {else}
    <tr><th>__LNG__Object__LNG__</th><th>__LNG__Locked On__LNG__ &darr;<br>__LNG__by User__LNG__</th><th>__LNG__Released On__LNG__<br>__LNG__by User__LNG__</th></tr>
    {/if}
</thead>
<tbody>
    {foreach from=$resultset key=k item=rec}
    <tr class='{cycle values="odd,even"}'>
        {if $smarty.request.type!="history"}
            <td>&nbsp;<img src="../img/gx/objclass/{$gx_objcls[$rec.objcls].small}.png" title="{$gx_objcls[$rec.objcls].long}">&nbsp;{$rec.objnam}</td>
            <td>&nbsp;{$InProve_Smarty->guid2name('gxt_users', $rec.setuserguid)}</td>
            <td align="center">{$InProve_Smarty->ts2str($rec.setts)}</td>
        {else}
            <td>&nbsp;<img src="../img/gx/objclass/{$gx_objcls[$rec.objcls].small}.png" title="{$gx_objcls[$rec.objcls].long}">&nbsp;{$rec.objnam}</td>
            <td align="center">{$InProve_Smarty->ts2str($rec.setts)}<br>{$InProve_Smarty->guid2name('gxt_users', $rec.setuserguid)}</td>
            <td align="center">{$InProve_Smarty->ts2str($rec.unsetts)}<br>{$InProve_Smarty->guid2name('gxt_users', $rec.unsetuserguid)}</td>
        {/if}
    </tr>
    {/foreach}
</tbody>
</table>

{if $smarty.request.type!="history"}
<span id="all_history">
    <span class="file">
    {$InProve_Smarty->msg("ui-icon-zoomin","__LNG__Click to see all locking history__LNG__.")}
    </span>
</span>
<br clear="all">
{/if}