{include file="../skel/header.phtml"}
<script type="text/javascript">
$(document).ready(function(){
    $("#tabs").tabs();

    $("#GenericDialog").dialog({
        bgiframe: true,
        autoOpen: false,
        modal: true,
        position: 'center',
        open: function(event, ui) { $("#GenericDialog").html('{$smarty.const._MSG_WAIT_SM_}'); }
    });
});
</script>

    <table align="center" width="100%" class="list-horizontal">
    <tr>
		<td align="left" class="header first" scope="row">
			__LNG__Internal Id__LNG__
		</td>
		<td align="left" class="first">
			{$record.kbguid}
		</td>
	</tr>
    <tr>
		<td align="left" class="header" scope="row">
			__LNG__Visual Id__LNG__
		</td>
		<td align="left">
			{$visualid}
		</td>
	</tr>
    <tr>
		<td align="left" class="header" scope="row">
			__LNG__Description__LNG__
		</td>
		<td align="left">
			{$record.kbdsc}
		</td>
	</tr>
    <tr>
		<td align="left" class="header" scope="row">
			__LNG__Source__LNG__
		</td>
		<td align="left">
			{$record.kbdir}
		</td>
	</tr>
    <tr>
		<td align="left" class="header" scope="row">
			__LNG__Vers./Sync. Status__LNG__
		</td>
        <td align="left">
        {if $versyncsts.status == "not_finished"}
            Last run {$versyncsts.datetime}, {$versyncsts.vers} % is versioned, and {$versyncsts.sync} % was synchronized.
        {elseif $versyncsts.status == "sync_pending"}
            Synchronization pending.
        {elseif $versyncsts.status == "finished"}
            No sync. pending, {$versyncsts.vers} % versioned, and {$versyncsts.sync} % synchronized.
        {/if}
        </td>
    </tr>
    </table>
    <p>
    <div id="tabs">
    <ul>
        <li><a href="position?kbguid={$record.kbguid}"><span>__LNG__Kb Position__LNG__</span></a></li>
        {if $record.kbclass >= 7500}<li><a href="envs?kbguid={$record.kbguid}"><span>__LNG__Environments__LNG__</span></a></li>{/if}
        <li><a href="/Fsys-Brw/?data2browse={$kbfiles2browse}"><span>__LNG__KB Files__LNG__</span></a></li>
        <li><a href="/Fsys-Brw/?data2browse={$staged2browse}"><span>__LNG__Stag Files__LNG__</span></a></li>
        <li><a href="locks?kbguid={$record.kbguid}"><span>__LNG__Locking__LNG__</span></a></li>
    </ul>
    </div>

{include file="../skel/footer.phtml"}