<script type="text/javascript">
$(document).ready(function(){    
    pieChart = new Highcharts.Chart({
        credits: {
         enabled: false
        },
        chart: {
         renderTo: 'pie-chart',
         plotBackgroundColor: null,
         plotBorderWidth: null,
         plotShadow: false
        },
        title: {
         text: '{$lL.__objects_class_distribution_map__}'
        },
        tooltip: {
         formatter: function() {
            return '<b>'+ this.point.name +'</b>: '+ this.y;
         }
        },
        plotOptions: {
         pie: {
            allowPointSelect: true,
            cursor: 'pointer',
            dataLabels: {
               enabled: false
            },
            showInLegend: true
         }
        },
        series: [{
        type: 'pie',
        name: '{$lL.__class_distribution__}',
        data: [            
            {foreach $pie_data as $key => $val name=data}
            ['{$key}', {$val}]{if !$smarty.foreach.data.last},{/if}
            {/foreach}
        ]
        }]
    });
});
</script>
<div id="pie-chart" style="float:left;height:300px;width:350px;margin-top:.75em;">
    {$smarty.const._MSG_WAIT_SM_}
</div>
<div id="database-data" style="float:left;text-align:left;margin-left:50px;margin-top:.75em;">
    <strong>{$lL.__database_related__}</strong>
    <p>{$schema.5}</p>
    <p>{$schema.11}</p>
    <p>{$schema.7}</p>
    <p>{$schema.30}</p>
</div>