{include file="../skel/header.phtml"}
<script type="text/javascript">
$(document).ready(function(){
    $("#tabs").tabs();

    $("#GenericDialog").dialog({
        bgiframe: true,
        autoOpen: false,
        modal: true,
        position: 'center',
        open: function(event, ui) { $("#GenericDialog").html('{$smarty.const._MSG_WAIT_SM_}'); }
    });
});
</script>

    <table align="center" width="100%" class="list-horizontal">
    <tr>
		<td align="left" class="header first" scope="row">
			{$lL.__internal_id__}
		</td>
		<td align="left" class="first">
			{$record.kbguid}
		</td>
	</tr>
    <tr>
		<td align="left" class="header" scope="row">
			{$lL.__visual_id__}
		</td>
		<td align="left">
			{$visualid}
		</td>
	</tr>
    <tr>
		<td align="left" class="header" scope="row">
			{$lL.__description__}
		</td>
		<td align="left">
			{$record.kbdsc}
		</td>
	</tr>
    <tr>
		<td align="left" class="header" scope="row">
			{$lL.__source__}
		</td>
		<td align="left">
			{$record.kbdir}
		</td>
	</tr>
    <tr>
		<td align="left" class="header" scope="row">
			{$lL.__vers__sync__status__}
		</td>
        <td align="left">
        {if $versyncsts.status == "not_finished"}
            Last run {$versyncsts.datetime}, {$versyncsts.vers} % is versioned, and {$versyncsts.sync} % was synchronized.
        {elseif $versyncsts.status == "sync_pending"}
            Synchronization pending.
        {elseif $versyncsts.status == "finished"}
            No sync. pending, {$versyncsts.vers} % versioned, and {$versyncsts.sync} % synchronized.
        {/if}
        </td>
    </tr>
    </table>
    <p>
    <div id="tabs">
    <ul>
        <li><a href="position?kbguid={$record.kbguid}"><span>{$lL.__kb_position__}</span></a></li>
        {if $record.kbclass >= 7500}<li><a href="envs?kbguid={$record.kbguid}"><span>{$lL.__environments__}</span></a></li>{/if}
        <li><a href="/Fsys-Brw/?data2browse={$kbfiles2browse}"><span>{$lL.__kb_files__}</span></a></li>
        <li><a href="/Fsys-Brw/?data2browse={$staged2browse}"><span>{$lL.__stag_files__}</span></a></li>
        <li><a href="locks?kbguid={$record.kbguid}"><span>{$lL.__locking__}</span></a></li>
    </ul>
    </div>

{include file="../skel/footer.phtml"}