<div id="repo_stats">
    <strong>{$lL.__project__} : </strong>{$project.projabv}
    <br>
    <strong>{$lL.__repository__} : </strong>
    {if $repo_stats.ava != '!exist'}
        <span style="text-decoration:underline;color:blue;cursor:pointer;" onclick="mDialog('/Browse-Repos/rinfo?repopath={$repo_stats.path|base64_encode}&projguid={$projguid}', '{$lL.__repository_detailed_stats__}', 480, 640);">{$lL.__available__}</span>
    {else}
        {$InProve_Smarty->msg("ui-icon-alert","{$lL.__not_available__}")}
    {/if}
</div>

<div class="myhr"></div>

<div id="repo_stats">
    <table align="center" width="100%">
    <tr>
        <td align="left">{$lL.__parent_kb__}</td><td align="left">{$relations.parent}</td>
    </tr>
    <tr>
        <td align="left">{$lL.__children_kb_s___}</td><td align="left">{foreach from=$relations.children key=k item=rec}{$rec}<br>{/foreach}</td>
    </tr>
    </table>
</div>