<div id="repo_stats">
    <strong>Project : </strong>{$project.projabv}
    <br>
    <strong>Repository : </strong>
    {if $repo_stats.ava != '!exist'}
        <span style="text-decoration:underline;color:blue;cursor:pointer;" onclick="mDialog('/Browse-Repos/rinfo?repopath={$repo_stats.path|base64_encode}&projguid={$projguid}', 'Repository Detailed Stats', 480, 640);">Available</span>
    {else}
        {$Accendo_Smarty->msg("ui-icon-alert","Not Available")}
    {/if}
</div>

<div class="myhr"></div>

<div id="repo_stats">
    <table align="center" width="100%">
    <tr>
        <td align="left">Parent Kb</td><td align="left">{$relations.parent}</td>
    </tr>
    <tr>
        <td align="left">Children Kb(s)</td><td align="left">{foreach from=$relations.children key=k item=rec}{$rec}<br>{/foreach}</td>
    </tr>
    </table>
</div>