
<script type="text/javascript">
$(document).ready(function(){

    $("#form_confxml").ajaxForm({
        dataType: 'json',
        async: false,
        beforeSubmit: function() {
            $("#form_confxml .buttons").hide();
        },
        success: function (r) {
            notify("Notification",r.msg,(r.sts ? "info" : "error"),(r.sts ? 2500 : 7500));
            if (r.sts) {
                setTimeout('window.location.reload();', 2500);                
            } else {
                $("#form_confxml .buttons").show("slow");
            }
        },
        error: function (jqXHR) {
            handleXHRerror(jqXHR);
        }
    });

    $("#form_confxml input:text").blur(function() { checkValues(); });
    
    checkValues();

    $("#osinfo").load("/Conf-Xml/osinfo");

});

function checkValues(entryspec) {
                        
    $("#form_confxml input:text").each( function(idx,obj) {
    if (!entryspec || entryspec==$(obj).attr("entryname")) {
        if ($(obj).val() && $(obj).val() != "__NEED_SETTING__" && $("#check_"+hex_sha1($(obj).attr("entryname"))).attr("id")) {
            $.getJSON(
                    "/Conf-Xml/check",
                    { chkif:"inFilesystem" , chkval:$(obj).val(), entryname:$(obj).attr("entryname") },
                    function(r) {
                        if (r.sts=="ok") {
                            $("#check_"+hex_sha1($(obj).attr("entryname"))).html("<img src='../img/icons/16/tick.png' alt='ok' title='"+r.msg+"'>");
                        } else if (r.sts=="err") {
                            $("#check_"+hex_sha1($(obj).attr("entryname"))).html("<img src='../img/icons/16/error.png' alt='ok' title='"+r.msg+"'>");
                        } else {
                            $("#check_"+hex_sha1($(obj).attr("entryname"))).html("");
                        }
                    }
            );
        } else {
            $("#check_"+hex_sha1($(obj).attr("entryname"))).html("");
        }
        
        if ($(obj).val() == "__NEED_SETTING__") {
            $("#label_"+hex_sha1($(obj).attr("entryname"))).css("color","red");
        }
        if ($(obj).val() != $("#input_"+hex_sha1($(obj).attr("entryname"))).attr("entryvalue")) {
            $("#label_"+hex_sha1($(obj).attr("entryname"))).css("color","#4581DF");
        } else {
            $("#label_"+hex_sha1($(obj).attr("entryname"))).css("color","");
        }
    }
    });
    
}

function deleteFile(file2delete) {
    
    $("#form_confxml .buttons").hide();    
    if (confirm('Confirm File Deletion ?')) {
        $.getJSON(
                "/Conf-Xml/delfile",
                { file2delete:file2delete },
                function(r) {
                    notify("Notification",r.msg,(r.sts ? "info" : "error"),(r.sts ? 2500 : 7500));
                    if (r.sts) {                        
                        setTimeout('window.location.reload();', 2500);
                    } else {
                        $("#form_confxml .buttons").show("slow");
                    }
                }
        );
    } else {
        $("#form_confxml .buttons").show("slow");
    }

}
</script>

<div id="osinfo" class="right" style="font-size:.8em;" onclick="$('.section').toggle();">
    {$smarty.const._MSG_WAIT_SM_}
</div>    
<div id="confxml" class="section">
	<form id="form_confxml" action="/Conf-Xml/post" method="POST" enctype="multipart/form-data">
        <div class="myhr">Environment Variables</div>
        <table align="center" width="95%">
        {foreach $xmlConf.envvars as $prop_name => $prop_value}
        <tr>
            <td style="text-align:left;font-weight:bold;width:30%;">
                <span id="label_{$prop_name|sha1}">{$entriesDef.$prop_name.label|default:$prop_name}</span>
                {if $entriesDef.$prop_name.check}<span id="check_{$prop_name|sha1}" class="right"><img style="vertical-align:middle; padding:5px;" src="../img/loading_16-{$smarty.const.__LAYER_ROLE__}.gif"></span>{/if}
            </td>
            <td align="left">
                <input type="{$entriesDef.$prop_name.inputtype|default:'text'}" size="70" id="input_{$prop_name|sha1}" name="envvars[{$prop_name}]" value="{$prop_value}" {if $entriesDef.$prop_name.readonly}readonly="readonly"{/if} entryname="{$prop_name}" entryvalue="{$prop_value}">
                {if $entriesDef.$prop_name.defvalue}
                &nbsp;&laquo;&nbsp;
                {if $entriesDef.$prop_name.defvalue != "__UNSET__"}
                <a href="javascript:;" class="setDefVal" style="font-size:.8em;" onclick="$('#input_{$prop_name|sha1}').val('{$entriesDef.$prop_name.defvalue}');checkValues('{$prop_name}');">From system</a>&nbsp;|&nbsp;
                {/if}
                <a href="javascript:;" {if $entriesDef.$prop_name.defvalue == "__UNSET__"}class="setDefVal"{/if} style="font-size:.8em;" onclick="$('#input_{$prop_name|sha1}').val('');checkValues('{$prop_name}');">Unset</a>
                {/if}
            </td>
        </tr>
        {/foreach}
        <tr>
            <td colspan="2" align="right">
                <a href="javascript:;" style="font-size:.8em;" onclick="$('.setDefVal').click();">Set All with Default Values</a>
            </td>
        </tr>        
        </table>

        {foreach $xmlConf.gxtend_servers as $server_name => $server_props}
        <div class="myhr">Metadata Connection Properties for {$server_name}</div>
        <table align="center" width="96%">
        {foreach $server_props as $prop_name => $prop_value}
        <tr>
            <td style="text-align:left;font-weight:bold;width:30%;">
                <span id="label_{$prop_name|sha1}">{$entriesDef.$prop_name.label|default:$prop_name}</span>
                {if $entriesDef.$prop_name.check}<span id="check_{$prop_name|sha1}" class="right"><img style="vertical-align:middle; padding:5px;" src="../img/loading_16-{$smarty.const.__LAYER_ROLE__}.gif"></span>{/if}
            </td>
            <td align="left">
                <input type="{$entriesDef.$prop_name.inputtype|default:'text'}" size="70" id="input_{$prop_name|sha1}" name="gxtend_servers[{$server_name}][{$prop_name}]" value="{$prop_value}" {if $entriesDef.$prop_name.readonly}readonly="readonly"{/if} entryname="{$prop_name}" entryvalue="{$prop_value}">
                {if $prop_name == "schema" && $smarty.const.__LAYER_ROLE__ == "Client"}&nbsp;<a id="delete_{$prop_value|sha1}" href="javascript:;" style="font-size:.8em;" onclick="deleteFile('{$prop_value}');">Delete file</a>{/if}
            </td>
        </tr>
        {/foreach}
        </table>
        {/foreach}
        <div class="myhr"></div>
        <div class="left">
            {include file='../index/ttp.phtml' bck2top='no'}
        </div>
        <div class="buttons right">
            {$smarty.const._FORM_BTN_UPDATE_}
            &nbsp;or&nbsp;
            <a href="javascript:;" onclick='$("#GenericDialog").dialog("close");'>cancel</a>&nbsp;
        </div>
	</form>
</div>
<div id="instprog" class="section" style="display:none;">
    <div class="myhr">Currently Installed Programs</div>
    <table align="center" width="95%" class="list">
    <thead>
        <tr><th>Name</th><th>Publisher</th><th>Version</th></tr>
    </thead>
    <tbody>
    {foreach $lstSoft as $entry_id => $entry_data}
    {if $entry_data.DisplayName && strtolower($entry_data.Publisher)=="artech"}
    <tr class="{strtolower($entry_data.Publisher)|sha1}">
        <td>
            {$entry_data.DisplayName|utf8_encode}
        </td>
        <td>
            {$entry_data.Publisher|utf8_encode}
        </td>
        <td>
            {$entry_data.DisplayVersion}
        </td>
    </tr>
    {/if}
    {/foreach}
    </tbody>
    </table>    
</div>