<script type="text/javascript">
$(document).ready(function(){
    
    $("#my_profile #tabber").tabs({
        load: function(event, ui) {
            initializeButtons();
        }
    });

});
</script>

<div class="heading-block">
    <h1>{$lL.__my_profile__}</h1>
</div>

<div id="my_profile" class="profile">

    <div id="tabber">
        <ul>
        <li><a href="/form/render?parms={$parms}">{$lL.__personal_data__}</a></li>
        <li><a href="/My-Profile/appconfig">{$lL.__personal_settings__}</a></li>
        </ul>
    </div>

</div>