<script type="text/javascript">
$(document).ready(function(){
    $("#pselector").click();
});

function show_synch(type, projguid) {

    if (type=="push") {
        var url = "/Push/index";
    } else if (type=="fetch") {
        var url = "/Fetch/index";
    } else if (type=="stats") {
        var url = "/Work-Stats/index";
    }

    $("#synch").html('{$smarty.const._MSG_WAIT_SM_}');
    $("#synch").load(url, { projguid:projguid });

}

function show_diffs(type, projguid, kbguid, what2comp) {

    var codeline = $("#codeline").val();

    $("#diffs").html('{$smarty.const._MSG_WAIT_SM_}');

    if (type=="checkin") {
        $("#diffs").load("/Chkin/index",{ projguid:projguid,kbguid:kbguid,mdlid:1,mergebefore:0,what2comp:what2comp });
    } else if (type=="catchup") {
        $("#diffs").load("/Catchup/index",{ projguid:projguid,kbguid:kbguid,mdlid:1,mergebefore:0,what2comp:what2comp });
    } else if (type=="merge") {
        $("#diffs").load("/Chkin/index",{ projguid:projguid,kbguid:kbguid,mdlid:1,mergebefore:1 });
    }

}

function show_srchres(projguid, kbguid, mdlid) {

    var qrystr = $.trim($("#qrystr").val());
    if (qrystr!=="") {
    	loadappdiv("/Lock/search",{ projguid:projguid,kbguid:kbguid,mdlid:mdlid,qrystr:qrystr },"#diffs");
	} else {
		alert("Need to specify a value to submit");
	}

}

</script>

<div id="project">
    <h1>
        <span id="pselector" onclick='var offset=$("#pselector_xypos").offset();mDialog("/cvs/pselector", "{$lL.__switch_to_project__}...", null, null, [offset.left,offset.top]);' class='file'>{$lL.__switch_to_project__}...</span>&nbsp;<span id="pselector_xypos"></span>
    </h1>
    <span style="float:right;">
        <p>&nbsp;</p>   
    </span>
    <br>
    <div id="proj_tabber">
    </div>
</div>