<script type="text/javascript">

$(document).ready(function(){

    $("#east_panel #proj_tabber #tabber #tab-1-loadmsg").hide();
    $("#tabber").tabs("option","disabled",[]);

    {if $project.repo_stats.ava != "!exist"}
    $("#synch").show("slow", show_synch("stats","{$project.projguid}"));
    {/if}

});

function buildLR(projguid) {

    $("#east_panel #proj_tabber #tabber #prjnfo").html('{$smarty.const._MSG_WAIT_SM_}');
    $("#east_panel").block({ message: '{$smarty.const._BAR_WAIT_}' });

    jQuery.getJSON(
            "/Cvs/clone",
            { projguid:projguid },
            function (data, textStatus) {
                showlogmsg();       // Display user message...
                $("#east_panel #proj_tabber #tabber").tabs("load",0);
                $("#east_panel").unblock();
            }
    );    

}

</script>

<div id="prjnfo">

    <div style="float:left;">
    <strong>&nbsp;{$lL.__local_repo___}:&nbsp;</strong>
    {if $project.repo_stats.ava == "!exist"}
        {$InProve_Smarty->msg("ui-icon-alert","{$lL.__not_found__}")}
        {if $project.remo_repo_stats.ava == "open" || $project.remo_repo_stats.ava == "read"}
        &nbsp;<span onclick='if(confirm("{$lL.__confirm_repository_creation__} ?")) { buildLR("{$project.projguid}"); }' class='pointer'><img src="{$smarty.const._IMG_DOWNLOAD_SM_}" title="{$lL.__click_to_build_project_repository_local_instance__}"></span>
        {/if}
    {else}
        <span style="text-decoration:underline;color:blue;cursor:pointer;" onclick="mDialog('/Browse-Repos/rinfo?repopath={$project.repo_stats.path|base64_encode}&projguid={$project.projguid}', '{$lL.__repository_detailed_stats__}', 480, 640);">{$lL.__available__}</span>
    {/if}
    </div>

    <div style="float:right;">
    <strong style="float:left;">&nbsp;{$lL.__remote_repo___}:&nbsp;</strong>
    {if !$project.remo_repo_stats}
        &nbsp;{$lL.__unavailable__}
    {else}
        {if $project.remo_repo_stats.ava == "!exist"}
            &nbsp;{$lL.__not_found__}
        {else}
            {if $project.remo_repo_stats.ava == "open"}
            &nbsp;{$lL.__available_for_reading_and_writing__}
                {if $project.repo_stats.ava == "open"}
                &nbsp;<span id="pushlnk" onclick='$("#synch").show("slow", show_synch("push","{$project.projguid}"));' class='pointer'><img src='{$smarty.const._IMG_PUSH_SM_}' alt='Push' title='{$lL.__click_to_see_push__}'></span>
                &nbsp;<span id="fetchlnk" onclick='$("#synch").show("slow", show_synch("fetch","{$project.projguid}"));' class='pointer'><img src='{$smarty.const._IMG_FETCH_SM_}' alt='Fetch' title='{$lL.__click_to_see_fetch__}'></span>
                {/if}
            {elseif $project.remo_repo_stats.ava == "read"}
            &nbsp;Available for Reading (not Writing)
                {if $project.repo_stats.ava == "open"}
                &nbsp;<span id="fetchlnk" onclick='$("#synch").show("slow", show_synch("fetch","{$project.projguid}"));' class='pointer'><img src='{$smarty.const._IMG_FETCH_SM_}' alt='Fetch' title='{$lL.__click_to_see_fetch__}'></span>
                {/if}
            {elseif $project.remo_repo_stats.ava == "close"}
                &nbsp;{$lL.__not_available_for_reading_or_writing__}
            {/if}
        {/if}
    {/if}
    </div>

</div>
<br clear="both">
<br clear="both">
<div id="synch" style="display: none;"></div>