{include file="../skel/header.phtml"}
<script type="text/javascript">
$(document).ready(function(){

    $("#form_compare,#form_catchup,#form_confr,#form_checkin").ajaxForm({
                                dataType: "json",
                                async: false,
                                beforeSubmit: function() {
                                    $.blockUI({ message: '{$smarty.const._MSG_WAIT_}' });
                                },
                                success: function (r) {
                                    $.unblockUI();
                                    notify("Notification",r.msg,"info",2500);
                                },
                                error: function (jqXHR) {
                                    handleXHRerror(jqXHR);
                                }
    });

    setsubmitsts("#form_catchup > :checkbox:checked", "#submit_catchup");
    setsubmitsts("#form_confr > :radio:checked", "#submit_confr");
    setsubmitsts("#form_checkin > :checkbox:checked", "#submit_chkin");

    $("#show_hide_lnk").toggle(
        function() {
            $("#show_hide_div").show();
            $("#show_hide_img").attr("src", "{$smarty.const._IMG_HIDE_SM_}");
        },
        function() {
            $("#show_hide_div").hide();
            $("#show_hide_img").attr("src", "{$smarty.const._IMG_SHOW_SM_}");
        }
    );

});
</script>

    <table align="center" width="100%">
    <tr><td align="left"><img src="../img/gx/objclass/{$gx_objcls[$smarty.get.OBJCLS].small}.png" title="{$gx_objcls[$smarty.get.OBJCLS].long}">&nbsp;{$smarty.get.OBJNAM}</td><td align="left">{$smarty.get.OBJDSC}</td></tr>
    <tr><td align="left"><b>Local</b> {$local_visualid}</td><td align="left">Updated on {$InProve_Smarty->ts2str($smarty.get.OBJUPDTS)}</td></tr>
    <tr><td align="left"><b>Remote</b> {$remote_visualid}</td><td align="left">Updated on {$InProve_Smarty->ts2str($smarty.get.COMPREF)}</td></tr>
    <tr><td align="left"><b>Modification Status</b></td><td align="left">{$smarty.get.CHKINSTS}</td></tr>
    <tr><td align="left" colspan="2">
            <p>
            <fieldset><legend>Catchup with server's version</legend>
            <form id="form_catchup" action="../catchup/catchup" method="POST" enctype="multipart/form-data">
            <input type="hidden" name="lkbguid" value="{$smarty.request.lkbguid}">
            <input type="hidden" name="lmdlid" value="{$smarty.request.lmdlid}">
            <input type="hidden" name="repo" value="{$smarty.request.repo}">
            <input type="hidden" name="rkbguid" value="{$smarty.request.rkbguid}">
            <input type="hidden" name="rmdlid" value="{$smarty.request.rmdlid}">
            <input type=checkbox name='checked_objs[]' value='{$smarty.get.MDLID},{$smarty.get.OBJCLS},{$smarty.get.OBJNAM}' onclick='setsubmitsts("#form_catchup > :checkbox:checked", "#submit_catchup");'>
            Discard my changes, update my working copy with server's version.
            <input type=submit id="submit_catchup" name="submit_btn" value="{$smarty.const._LBL_SUBMIT_}" title="{$smarty.const._TITLE_SUBMIT_}">&nbsp;
            </form>
            </fieldset>
        </td></tr>
    <tr><td align="left" colspan="2">
            <p>
            <fieldset><legend>Conflict resolution help options</legend>
            <form id="form_compare" action="compare" method="POST" enctype="multipart/form-data">
            <input type="hidden" name="lkbguid" value="{$smarty.request.lkbguid}">
            <input type="hidden" name="lmdlid" value="{$smarty.request.lmdlid}">
            <input type="hidden" name="repo" value="{$smarty.request.repo}">
            <input type="hidden" name="rkbguid" value="{$smarty.request.rkbguid}">
            <input type="hidden" name="rmdlid" value="{$smarty.request.rmdlid}">
            <input type="hidden" name="checked_objs[]" value="{$smarty.get.MDLID},{$smarty.get.OBJCLS},{$smarty.get.OBJNAM}">
            &nbsp;Code compare using {$comparer}&nbsp;
            <input type=submit id="submit_list" name="submit_btn" value="{$smarty.const._LBL_SUBMIT_}" title="{$smarty.const._TITLE_SUBMIT_}">&nbsp;
            </form>
            <hr>
            <form id="form_confr" action="confr" method="POST" enctype="multipart/form-data">
            <input type="hidden" name="lkbguid" value="{$smarty.request.lkbguid}">
            <input type="hidden" name="lmdlid" value="{$smarty.request.lmdlid}">
            <input type="hidden" name="repo" value="{$smarty.request.repo}">
            <input type="hidden" name="rkbguid" value="{$smarty.request.rkbguid}">
            <input type="hidden" name="rmdlid" value="{$smarty.request.rmdlid}">
            <input type="hidden" name="checked_objs[]" value="{$smarty.get.MDLID},{$smarty.get.OBJCLS},{$smarty.get.OBJNAM}">
            <input type=radio name="ResOpt" value="Local_Merge_My" onclick='setsubmitsts("#form_confr > :radio:checked", "#submit_confr");'> Local manual merge using my copy as base.<br>
            <input type=radio name="ResOpt" value="Local_Merge_Server" onclick='setsubmitsts("#form_confr > :radio:checked", "#submit_confr");'> Local manual merge using server's copy as base.
            <div align="right">
            <input type=submit id="submit_confr" name="submit_btn" value="{$smarty.const._LBL_SUBMIT_}" title="{$smarty.const._TITLE_SUBMIT_}">&nbsp;
            </div>
            </form>
            </fieldset>
        </td></tr>
    <tr><td align="left" colspan="2">
            <p>
            <fieldset><legend>Ready to Check-In [conflicts solved or no need to]</legend>
            <form id="form_checkin" action="../chkin/chkin" method="POST" enctype="multipart/form-data">
            <input type="hidden" name="lkbguid" value="{$smarty.request.lkbguid}">
            <input type="hidden" name="lmdlid" value="{$smarty.request.lmdlid}">
            <input type="hidden" name="repo" value="{$smarty.request.repo}">
            <input type="hidden" name="rkbguid" value="{$smarty.request.rkbguid}">
            <input type="hidden" name="rmdlid" value="{$smarty.request.rmdlid}">
            {if $commit_status.sts}
                <input type=checkbox name='checked_objs[]' value='{$smarty.get.MDLID},{$smarty.get.OBJCLS},{$smarty.get.OBJNAM}' onclick='setsubmitsts("#form_checkin > :checkbox:checked", "#submit_chkin");'>
                Use my current working copy to update server's version
                <input type=submit id="submit_chkin" name="submit_btn" value="{$smarty.const._LBL_SUBMIT_}" title="{$smarty.const._TITLE_SUBMIT_}">&nbsp;
                <br>
                <div style="font-size:.8em">
                <!-- Release Lock-->
                &nbsp;[Release lock on successful commit <input type=checkbox name='relcommlcks' value='1' checked>]&nbsp;
                <!-- Add Comment-->
                &nbsp;<a href="#" id="show_hide_lnk">[Add Comment <img id="show_hide_img" src="{$smarty.const._IMG_SHOW_SM_}" title="{$smarty.const._TITLE_SHOW_}">]</a>
                <div style="display:none;text-align:center;" id="show_hide_div">
                    <textarea name="message" rows="5" cols="70"></textarea>
                </div>
                </div>
            {else}
                <span class="red">Check-In not available at this time [{$commit_status.msg}]</span>&nbsp;
            {/if}
            </form>
            </fieldset>
        </td></tr>
    </table>

{include file="../skel/footer.phtml"}