<script type="text/javascript">
function applyAction(action) {
    
    $('#service_action div.left').html('{$smarty.const._MSG_WAIT_SM_}');
    
    jQuery.getJSON(
            "/Services/apply",
            { action:action, srvname:'{$smarty.request.srvname}' },
            function (r, textStatus) {
                if (r.sts == "ok") {
                    $("#service_action div.left").html("<img src='../img/icons/32/tick.png' alt='ok' title='ok'> "+r.msg);
                    setTimeout("getServicesStatus('servicessts');",2500);
                } else {
                    $("#service_action div.left").html("<img src='../img/icons/32/error.png' alt='err' title='err'> "+r.msg);
                }

            }
    );
    
}

function getServicesStatus(hldid) {
    
    $("#"+hldid).html('{$smarty.const._MSG_WAIT_SM_}');

    $.get(
        "/Services/?match={$smarty.request.match}",
        function (data, textStatus, jqXHR) {
            $("#"+hldid).html(data);
        }
    );

}
</script>
<div id="service_action" style="font-size:1.10em;">
    <ul style="padding-left:1em;list-style-type:square;">
        <li style="margin:5px;"><strong>{$lL.__name__} :</strong> {$service.Caption}</li>
        <li style="margin:5px;"><strong>{$lL.__description__} :</strong> {$service.Description}</li>
        <li style="margin:5px;"><strong>{$lL.__status__} :</strong>
        {if $service.State != "Running"}
            <span class="red">{$service.State}</span>
        {else}
            <span class="green">{$service.State}</span>
        {/if}
        </li>
        <li style="margin:5px;"><strong>{$lL.__process_id__} :</strong> {$service.ProcessId}</li>
        <li style="margin:5px;"><strong>{$lL.__startup_type__} :</strong> {$service.StartMode}</li>
        <li style="margin:5px;"><strong>{$lL.__log_on_as__} :</strong> {$service.StartName}</li>
    </ul>
    <div class="left">
    </div>
    <div class="right">
        {if $service.State != "Running"}
        <div style="float:left;margin:5px;cursor:pointer;" class="ui-state-default ui-corner-all" title="{$lL.__start_service__}" onclick="applyAction('start');"><span class="ui-icon ui-icon-play"></span></div>
        {else}
        <div style="float:left;margin:5px;cursor:pointer;" class="ui-state-default ui-corner-all" title="{$lL.__stop_service__}" onclick="if (confirm('{$lL.__are_you_sure_you_want_to_stop_this_service__} ?')) { applyAction('stop'); }"><span class="ui-icon ui-icon-stop"></span></div>
        <div style="float:left;margin:5px;cursor:pointer;" class="ui-state-default ui-corner-all" title="{$lL.__restart_service__}" onclick="if (confirm('{$lL.__are_you_sure_you_want_to_restart_this_service__} ?')) { applyAction('restart'); }"><span class="ui-icon ui-icon-arrowrefresh-1-n"></span></div>
        {/if}
        <!--div style="float:left;margin:5px;cursor:pointer;" class="ui-state-default ui-corner-all" title="{$lL.__pause_service__}" onclick="if (confirm('{$lL.__are_you_sure_you_want_to_pause_this_service__} ?')) { applyAction('pause'); }"><span class="ui-icon ui-icon-pause"></span></div>
        <div style="float:left;margin:5px;cursor:pointer;" class="ui-state-default ui-corner-all" title="{$lL.__continue_service__}" onclick="if (confirm('{$lL.__are_you_sure_you_want_to_continue_this_service__} ?')) { applyAction('continue'); }"><span class="ui-icon ui-icon-play"></span></div-->
    </div>
</div>