{if $services}
{foreach $services as $srv name=dset}
    <a href="javascript:;" onclick="mDialog('/Services/action?match={$smarty.request.match}&srvname={$srv.DisplayName}', '{$lL.__action_on_service__}', 250, 500);">{$srv.DisplayName}</a> {$lL.__is__} 
    {if $srv.State != "Running"}
        <span class="red">{$srv.State}</span>
    {else}
        <span class="green">{$srv.State}</span>
    {/if}
    {if count($services)>1 && !$smarty.foreach.dset.last}, {/if}
{/foreach}
{else}
    <span class="red">{$lL.__service_s__not_available_installed__}</span>
{/if}