{if $services}
{foreach $services as $srv name=dset}
    <a href="javascript:;" onclick="mDialog('/Services/action?match={$smarty.request.match}&srvname={$srv.DisplayName}', 'Action on Service', 250, 500);">{$srv.DisplayName}</a> is 
    {if $srv.State != "Running"}
        <span class="red">{$srv.State}</span>
    {else}
        <span class="green">{$srv.State}</span>
    {/if}
    {if count($services)>1 && !$smarty.foreach.dset.last}, {/if}
{/foreach}
{else}
    <span class="red">Service(s) not Available in '{php_uname('s')}'</span>
{/if}