<!--External Includes-->
<script type="text/javascript" src="../syntax/shCore.js"></script>
<script type="text/javascript" src="../syntax/shAutoloader.js"></script>
<link href="../syntax/css/shCore.css" rel="stylesheet" type="text/css" />
<link href="../syntax/css/shThemeDefault.css" rel="stylesheet" type="text/css" />

<script type="text/javascript">
$(document).ready(function(){

	$("#reorg form").ajaxForm({
		dataType: 'json',
        async: true,
		beforeSubmit: function() {
            $('#reorg .toValidate').validate({
               ignore: ":hidden"
            });
            if ( $('#reorg .toValidate').valid() ) {
                $("#reorg button").prop("disabled", true).addClass("ui-state-disabled");
                if (confirm("__LNG__Confirm execution of changeset__LNG__ ?")) {
                $("#reorg form").hide(); $("#reorg #sqlResult").show();
                return true;
                }
            }
            return false;
		},
		success: function (r) {
            if (r.sts) {
                $("#reorg #sqlResult").html(base64_decode(r.msg));
            } else {
                notify("Notification",r.msg,(r.sts ? "info":"error"),2500);
                $("#reorg form").show(); $("#reorg #sqlResult").hide();
                $("#reorg button").prop("disabled", false).removeClass("ui-state-disabled");
            }
		},
		error: function (jqXHR) {
            handleXHRerror(jqXHR);
		}
	});

    SyntaxHighlighter.autoloader(
        'sql  ../syntax/shBrushSql.js',
        'php  ../syntax/shBrushPhp.js'
    );
    SyntaxHighlighter.all();

});
</script>

<div id="reorg">
<h3><strong>__LNG__Status__LNG__ :</strong> {$metasts.msg}</h3>
<div class="myhr"></div>

{if !$chgcode}
 __LNG__Current database structure version reports to be the same this build is set to__LNG__ (Version # {$InProve_Smarty->get_prm("meta_struct_version")})
{/if}
{foreach $chgcode as $dsc => $code name=changeSets}
<div class="infoset">
    <span class="ui-state-active ui-corner-all" style="padding:5px;">__LNG__Changes to get from__LNG__ {$dsc}</span>
    <div style="margin-top:10px;">
    {if $code.eval}
        [PHP]
        <pre type="syntaxhighlighter" class="brush: php">{$code.eval}</pre>
    {/if}
    {if $code.sql}
        [SQL]
        <pre type="syntaxhighlighter" class="brush: sql">{$code.sql}</pre>
        {if $smarty.foreach.changeSets.first}
        <form action="/Reorg/post" method="POST" enctype="multipart/form-data" class="toValidate right">
        <input type="hidden" name="set2exec" value="{$dsc}">
            <h3>__LNG__Authentication Information__LNG__</h3><br />
            <table>
            <tr>
                <td>&nbsp;<b>__LNG__Username__LNG__</b></td>
                <td>
                    <input name="username" type="text" value="" size="20" class="required" />
                </td>
            </tr>
            <tr>
                <td>&nbsp;<b>__LNG__Password__LNG__</b></td>
                <td><input name="password" type="password" value="" size="20" class="required" /></td>
            </tr>
            </table>
            <br />
            <div style="float:right;">{$smarty.const._FORM_BTN_SUBMIT_}</div>
        </form>
        <div id="sqlResult" class="ui-state-active ui-corner-all" style="padding:5px;display:none;">{$smarty.const._MSG_WAIT_SM_}</div>
        {/if}
        <br clear="all">
    {/if}
    </div>
</div>
{/foreach}

<div class="myhr"></div>
<ul>
    __LNG__
    <li>The execution of a set of changes might take <span style="color:red;font-weight:bold;">several minutes</span>.</li>
    <li>You can <span style="color:red;font-weight:bold;">monitor progress</span> by checking running processes using 'show processlist' MySql sentence.</li>
    <li>In some cases it might be a better choice to perform the above changes manually by using always present MySql shell interface or some visual stateful application (eg; MySql Workbench).</li>
    __LNG__
</ul>
</div>