<div id="div_history">

    {foreach from=$timeperiods key=k item=tperiod}
    {if $local_changes[$tperiod]|@count}
    <br clear="all">
    <fieldset>
        <legend>
            {$tperiod}
            [&nbsp;
            <span class='file' title='{$smarty.const._TITLE_HIDE_SHOW_}' onclick='$("#{$tperiod|sha1}").toggle("slow");'>&minus;/&plus;</span>
            &nbsp;]
        </legend>
		<div class="left">
            &nbsp;
		</div>
		<div class="column right">
            {$local_changes[$tperiod]|@count} commit(s)
		</div>
    <div id="{$tperiod|sha1}">
        <br clear="all">
        <table width="100%" align="center" class="list">
        {foreach from=$local_changes[$tperiod] key=commitId item=commitData}
        <tr id="{$commitId}" class='{cycle values="odd,even"}'>
            <td>
            <h3>{$commitData.changes|count} __LNG__change(s) commited from__LNG__ {$commitData.VisualId}</h3>
            <div class="column left" style="padding:1em;">
                <b>Id :</b> <a class="pointer" title="__LNG__Click to see commit's content__LNG__" href="javascript:;" onclick="mDialog('/Promote/?projguid={$smarty.request.projguid}&commits={$commitId}', '__LNG__Commit Data & Promotion Status__LNG__', 600, 900);">{$InProve_Smarty->cutstr($commitId,0,$smarty.const._GUID_LEN_)}</a><br>
                <img src='{$smarty.const._IMG_COMMENT_BLUE_SM_}' alt="comment" title='__LNG__Comment__LNG__' style="vertical-align:text-top;"> {$InProve_Smarty->cutstr($commitData.subject,0,80)}
            </div>
            <div class="column right" style="padding:1em;">
                <b>__LNG__Commited on__LNG__ :</b> {$InProve_Smarty->ts2str($commitData.commiterTs)}<br>
                <b>__LNG__Commited by__LNG__ :</b>
                                    {if $commitData.commiter==$InProve_Smarty->getSessVar('MyProfile.userdata.username')}
                                        <span class="green">{$commitData.commiter}</span> / {$InProve_Smarty->guid2name("gxt_users",$commitData.commiter_guid)}
                                    {else}
                                        <span class="blue">{$commitData.commiter}</span> / {$InProve_Smarty->guid2name("gxt_users",$commitData.commiter_guid)}
                                    {/if}
            </div>
            </td>
        </tr>
        {/foreach}
        </table>
    </div>
    </fieldset>
    {/if}
    {/foreach}

</div>