<div>
    <p style="margin:0px;">
    <img src="{$smarty.const._IMG_CLOCK_SM_}" alt="{$lL.__time__}" title="{$lL.__time_trace__}">&nbsp;{$InProve_Smarty->msg("#efefef:blue", "{$lL.__time_tracks_by__}")}
    <p>
    <ul style="margin-left:-10px;">
    {foreach from=$data.hoursfrom key=pos item=commenter}
        <li>
        {$InProve_Smarty->guid2name("gxt_users",$commenter.userguid)} [ {$commenter.number_of_times} ]<br>
        {if $commenter.phone}{$commenter.phone}<br>{/if}
        {if $commenter.im}{$commenter.im}<br></if>{/if}
        </li>
    {/foreach}
    </ul>
</div>