<div>
    <p style="margin:0px;">
    <img src="{$smarty.const._IMG_MAIL_FWD_SM_}" alt="{$lL.__subscribed__}" title="{$lL.__subscribed__}">&nbsp;{$InProve_Smarty->msg("#efefef:blue", "{$lL.__notifications__}")}&nbsp;{$InProve_Smarty->msg("HandT","Notifications")}
    </p>
    <ul style="margin-left:-10px;">
    {foreach $data.actsubsc as $pos => $userguid}
        <li>
        {$InProve_Smarty->guid2name("gxt_users",$userguid)}
        {if $userguid == $InProve_Smarty->getSessVar("MyProfile.userdata.userguid")}
        &nbsp;<span class="pointer" onclick="unsubsc('{$smarty.request.ttsguid}','{$userguid}');">({$lL.__unsubscribe__})</span>
        {/if}
        </li>
    {/foreach}
    </ul>
    <p style="margin:25px 0px 0px 0px;">
    <img src="{$smarty.const._IMG_COMMENT_BLUE_SM_}" alt="{$lL.__commented__}" title="{$lL.__commented__}">&nbsp;{$InProve_Smarty->msg("#efefef:blue", "{$lL.__comments_by__}")}
    </p>
    <ul style="margin-left:-10px;">
    {foreach $data.entriesfrom as $pos => $commenter}
        <li>
        {$InProve_Smarty->guid2name("gxt_users",$commenter.userguid)} [ {$commenter.number_of_comments} ]<br>
        {if $commenter.phone}{$commenter.phone}<br>{/if}
        {if $commenter.im}{$commenter.im}<br></if>{/if}
        </li>
    {/foreach}
    </ul>
</div>