Dear {$user_data.name},
<p>
{$Accendo_Smarty->guid2name("gxt_users",$ttsi_data.added_by)} commented on a To-Do.
<p>
    <h3>{$todo_data.todoabv}</h3>
    <ul style="line-height: 2em;">
        <li>
        &nbsp;{$item_data.ttsabv}
        &nbsp;<span style="background:green;color:white">&nbsp;{$all_status[$item_data.ttssts]}&nbsp;</span>
        </li>
    </ul>
    <fieldset><legend>Comment</legend>
        {$ttsi_data.itmtxt}
    </fieldset>
<p>
--<br>
Regards<br>
GxTend<br>