<script type="text/javascript">
function applyFilter(pname,pvalue) {
    
    var objParms = {}, urlParms;
    
    if (pname == "todoguid") {
        $('#filterONtodo').val(pvalue);
    } else {
        if (pname && pvalue) { objParms[pname] = pvalue; }
    }

    if ($("#filterONproj").val()) { objParms["filterONproj"] = $("#filterONproj").val(); }
    if ($("#filterONtodo").val()) { objParms["filterONtodo"] = $("#filterONtodo").val(); }
    if ($("#filterONuser").val()) { objParms["filterONuser"] = $("#filterONuser").val(); }
    if ($("#filterONduets").val()) { objParms["filterONduets"] = $("#filterONduets").val(); }
    urlParms = jQuery.param(objParms);
    
    loadappdiv("/Ticket-Mgmt/listall"+(urlParms ? "?"+urlParms : ""));
    
}
</script>

<div style="float:left;text-align:left;width:70%;padding-top:1em;">
    {foreach from=$lists_data key=lk item=list}
    {if $smarty.request.filterONtodo || $list.todosts.total.open!=0}
    {if !$smarty.request.projguid || $list.milestone.projguid==$smarty.request.projguid}
        <h2 style="cursor:pointer;text-decoration:underline;" onclick="applyFilter('todoguid','{$list.todoguid}');">{$list.todoabv}</h2>
        <button class="button-rss" style="font-size:0.7em;" type="button" onclick="window.open('/Rss/?todoguid={$list.todoguid}&token={$InProve_Smarty->userToken()}', '_blank');">&nbsp;&nbsp;RSS</button>
        {if $list.milestone && $list.milestone.mistabv!="_LBL_GLUE_"}
        <strong>Related milestone:</strong> <i>{$list.milestone.mistabv}</i>, <strong>due date</strong> <i style="color:{$list.milestone.dueDateColor};">{$InProve_Smarty->ts2str($list.milestone.mistduets, "date")}</i>
        {else}
        <i>No milestone is related to this list</i>
        {/if}
        <ul style="line-height: 2.3em;">
        {foreach from=$items_data[$list.todoguid] key=tk item=ticket}
            {if $ticket.open}
            <li class="entry_with_status_{$ticket.ttssts}">
                {$ticket.ttsabv}
                <span style="font-size:.9em;">
                &nbsp;{$InProve_Smarty->msg("white:back", $InProve_Smarty->guid2name("gxt_users",$ticket.assigned_to))}
                {if $ticket.ttsduets}&nbsp;{$InProve_Smarty->msg("white:back", $InProve_Smarty->ts2str($ticket.ttsduets,"date"))}{/if}
                &nbsp;{$InProve_Smarty->msg("green:white", $all_status[$ticket.ttssts])}
                &nbsp;
                <span class="file" onclick="loadappdiv('/Ticket-Mgmt/edit?ttsguid={$ticket.ttsguid}');">
                    {if $ticket.unseen}
                    <img src="{$smarty.const._IMG_COMMENT_BLUE_SM_}" alt="Click to View/Edit" title="There has been changes since the last time you view this ticket.">
                    {else}
                    <img src="{$smarty.const._IMG_COMMENT_GRAY_SM_}" alt="Click to View/Edit" title="No changes since last time you check on this ticket.">
                    {/if}
                </span>
                </span>
            </li>
            {/if}
        {/foreach}
            <div style="background-color:#efefef; font-size:0.9em; text-align:right;">
                {if $list.grants.rw}
                <button class="button-add" style="font-size:0.8em;" type="button" onclick="loadappdiv('/Ticket-Mgmt/edit?todoguid={$list.todoguid}&form_mode={$smarty.const._LBL_ADD_}');">&nbsp;&nbsp;Add Ticket</button>&nbsp;&nbsp;
                {else}
                {$InProve_Smarty->msg("#efefef:black", "Read Only Access")}&nbsp;&nbsp;
                {/if}
            </div>
        {if !$smarty.request.filterONuser && !$smarty.request.filterONduets}
        {foreach from=$items_data[$list.todoguid] key=tk item=ticket}
            {if !$ticket.open}
            <li class="entry_with_status_{$ticket.ttssts}" style="color: #999; font-size:0.8em;">
                {$ticket.ttsabv}
                &nbsp;{$InProve_Smarty->msg("#efefef:black", $all_status[$ticket.ttssts])}
                &nbsp;
                <span class="file" onclick="loadappdiv('/Ticket-Mgmt/edit?ttsguid={$ticket.ttsguid}');">
                    {if $ticket.unseen}
                    <img src="{$smarty.const._IMG_COMMENT_BLUE_SM_}" alt="Click to View/Edit" title="There has been changes since the last time you view this ticket.">
                    {else}
                    <img src="{$smarty.const._IMG_COMMENT_GRAY_SM_}" alt="Click to View/Edit" title="No changes since last time you check on this ticket.">
                    {/if}
                </span>
            </li>
            {/if}
        {/foreach}
            <div style="font-size:0.9em; text-align:left;">
                {if $list.todosts.total.close>3 && !$smarty.request.filterONtodo}
                <button class="button-zoomin" style="font-size:0.8em;" type="button" onclick="applyFilter('todoguid','{$list.todoguid}');">&nbsp;&nbsp;View all {$list.todosts.total.close} completed tickets</button>&nbsp;&nbsp;
                {/if}
            </div>
        {/if}
        </ul>
    {/if}
    {/if}
    {/foreach}
</div>

<div class="ui-state-active ui-corner-all todo-list" style="float:right;text-align:right;width:25%;font-size:0.9em;padding-top:1em;margin-top:1em;padding-bottom:1em;margin-bottom:1em;">
    <div style="float:right;text-align:right;padding-right:1em;">
        <strong class="file" onclick="loadappdiv('/Tbls-Mgmt/', { tbl:'gxt_todos' }, null, '$(\'#addNew\').click();');">Add List</strong>
    </div>
    {if $smarty.request.filterONtodo}
        <div style="text-align:left;padding-left:1em;">
            <strong style="color:black;">Show To-Dos on project&nbsp;</strong><br>
            {$projsdbox}
        </div>
        <br>
        <div style="text-align:left;padding-left:1em;">
            <strong style="color:black;">Show To-Dos assigned to&nbsp;</strong><br>
            {$usersdbox}
        </div>
        <br>
        <div style="text-align:left;padding-left:1em;">
            <strong style="color:black;">Show To-Dos that are due&nbsp;</strong><br>
            {$duetsdbox}
        </div>
        <br>
        <div style="text-align:left;padding-left:1em;">
            <strong style="color:black;">Show To-Dos in specific status&nbsp;</strong><br>
            <ul style="padding-left:1.5em;list-style-type:square;">
            {foreach from=$all_status key=sts_val item=sts_dsc}
                <li><input type="checkbox" onchange="$('.entry_with_status_{$sts_val}').toggle();" checked> {$sts_dsc}</li>
            {/foreach}
            </ul>
        </div>
        <br>
        <div style="text-align:left;padding-left:1em;">
            <span class="file" onclick="applyFilter('todoguid','');">Return to full To-Dos list</span>
        </div>
    {else}
        <div style="text-align:left;padding-left:1em;">
            <strong style="color:black;">Show To-Dos on project&nbsp;</strong><br>
            {$projsdbox}
        </div>
        <br>
        <div style="text-align:left;padding-left:1em;">
            <strong style="color:black;">Show To-Dos assigned to&nbsp;</strong><br>
            {$usersdbox}
        </div>
        <br>
        <div style="text-align:left;padding-left:1em;">
            <strong style="color:black;">Show To-Dos that are due&nbsp;</strong><br>
            {$duetsdbox}
        </div>
        <br>
        <div style="text-align:left;padding-left:1em;">
            <strong style="color:black;">Current To-Do Lists&nbsp;</strong>
            <ul style="padding-left:1.5em;list-style-type:square;">
            {foreach from=$lists_data key=lk item=list}
                {if $list.todosts.total.open!=0 || ($list.todosts.total.open==0 && $list.todosts.total.close==0)}
                <li class="file" onclick="applyFilter('todoguid','{$list.todoguid}');">{$InProve_Smarty->cutstr($list.todoabv)}</li>
                {/if}
            {/foreach}
            </ul>
        </div>
        <br>
        <div style="text-align:left;padding-left:1em;">
            <strong style="color:black;">Completed To-Do Lists&nbsp;</strong><p>
            <ul style="padding-left:1.5em;list-style-type:square;">
            {foreach from=$lists_data key=lk item=list}
                {if $list.todosts.total.open==0 && $list.todosts.total.close!=0}
                <li class="file" onclick="applyFilter('todoguid','{$list.todoguid}');">{$InProve_Smarty->cutstr($list.todoabv)}</li>
                {/if}
            {/foreach}
            </ul>
        </div>
    {/if}
    <div style="display:none;">
        {$todosdbox}
    </div>    
</div>