<script type="text/javascript">
$(document).ready(function(){

	$("#form_settag").ajaxForm({
		dataType:  'json',
		beforeSubmit: function() {
            $('#form_settag.toValidate').validate();
            if ( $('#form_settag.toValidate').valid() ) {
                $("#GenericDialog").block({ message: '{$smarty.const._MSG_WAIT_}' });
                return true;
            }
            return false;
		},
		success: function (r) {
            if (r.sts) {
                mDialog('/Ticket-Mgmt/settag?ttsguid={$smarty.request.ttsguid}', '__LNG__Ticket Tags__LNG__', 480, 640);
            } else {
                notify("__LNG__Notification__LNG__",r.msg,(r.sts ? "info" : "error"),(r.sts ? 2500 : 5000));
                $("#GenericDialog").unblock();
            }
        },
        error: function (jqXHR) {
            handleXHRerror(jqXHR);
        }
	});

});

function goChgPrm(mode,k,v) {
    
    $("#form_settag").show();
    if (mode=="edt") {
        $("#form_settag #key").prop("readonly","readonly").val(k);
        $("#form_settag #val").val(v);
        $("#form_settag #val").focus();
    } else {
        $("#form_settag #key").prop("readonly","").val("");
        $("#form_settag #val").val("");
        $("#form_settag #key").focus();
    }    
    $("#GenericDialog").animate({ scrollTop: $("#GenericDialog").height() }, 1000);

}
</script>

<div id="ttstags_detail" class="profile">

    <table align="center" width="100%" class="list-horizontal">
    <thead>
        <tr>
            <td class="header">__LNG__Name__LNG__</td>
            <td class="header">__LNG__Value__LNG__</td>
        </tr>
    </thead>
    <body>
    {foreach $tagslst as $row}
    <tr class="config_entries" onmouseover="$('#{$row.key|sha1}').show();" onmouseout="$('#{$row.key|sha1}').hide();">
        <td align="left" width="25%">
            <strong>{$row.key}</strong>
        </td>
        <td align="left">
            {$InProve_Smarty->cutstr($row.val,0,50)}
            <span id="{$row.key|sha1}" style="display:none;" onclick='goChgPrm("edt","{$row.key}","{$row.val}");' class='pointer right'><img src="{$smarty.const._IMG_EDIT_SM_}" title="__LNG__Edit entry__LNG__."></span>
        </td>
    </tr>
    {/foreach}
    <tr class="config_entries">
        <td align="left" class="header" scope="row" colspan="2">
            <span style="cursor:pointer;float:right;font-size:.8em;" onclick='goChgPrm("add","","");'>__LNG__Add Entry__LNG__</span>
        </td>
    </tr>
    </body>
    </table>

    <form id="form_settag" action="/Ticket-Mgmt/additm" method="POST" enctype="multipart/form-data" class="toValidate" style="display:none;">
    <input type="hidden" name="ttsguid" value="{$smarty.request.ttsguid}">
    <input type="hidden" name="itmtyp" value="tag">
        <p>
            {$InProve_Smarty->msg("ui-icon-info","__LNG__Add/Edit Tag__LNG__")}
        </p>
        <div>
        <label for="key"><strong>__LNG__Key__LNG__</strong></label>
        <input type="input" id="key" name="key" size="30" value="" class="required">
        </div>
        <div>
        <label for="val"><strong>__LNG__Value__LNG__</strong></label>
        <input type="input" id="val" name="val" size="75" value="" class="required" style="width:80%;">
        </div>
        <div id="bottom_right" class="buttons right">
            {$smarty.const._FORM_BTN_INSERT_}
            &nbsp;__LNG__or__LNG__&nbsp;
            <a href="javascript:;" onclick='$("#form_settag").hide();'>__LNG__cancel__LNG__</a>&nbsp;
        </div>
    </form>                
    
</div>