<script type="text/javascript">
$(document).ready(function(){

	$("#form_settag").ajaxForm({
		dataType:  'json',
		beforeSubmit: function() {
            $('#form_settag.toValidate').validate();
            if ( $('#form_settag.toValidate').valid() ) {
                $("#GenericDialog").block({ message: '{$smarty.const._MSG_WAIT_}' });
                return true;
            }
            return false;
		},
		success: function (r) {
            if (r.sts) {
                mDialog('/Ticket-Mgmt/settag?ttsguid={$smarty.request.ttsguid}', 'Ticket Tags', 480, 640);
            } else {
                notify("Notification",r.msg,(r.sts ? "info" : "error"),(r.sts ? 2500 : 5000));
                $("#GenericDialog").unblock();
            }
        },
        error: function (jqXHR) {
            handleXHRerror(jqXHR);
        }
	});

});

function goChgPrm(mode,k,v) {
    
    $("#form_settag").show();
    if (mode=="edt") {
        $("#form_settag #key").prop("readonly","readonly").val(k);
        $("#form_settag #val").val(v);
        $("#form_settag #val").focus();
    } else {
        $("#form_settag #key").prop("readonly","").val("");
        $("#form_settag #val").val("");
        $("#form_settag #key").focus();
    }    
    $("#GenericDialog").animate({ scrollTop: $("#GenericDialog").height() }, 1000);

}
</script>

<div id="ttstags_detail" class="profile">

    <table align="center" width="100%" class="list-horizontal">
    <thead>
        <tr>
            <td class="header">Name</td>
            <td class="header">Value</td>
        </tr>
    </thead>
    <body>
    {foreach $tagslst as $row}
    <tr class="config_entries" onmouseover="$('#{$row.key|sha1}').show();" onmouseout="$('#{$row.key|sha1}').hide();">
        <td align="left" width="25%">
            <strong>{$row.key}</strong>
        </td>
        <td align="left">
            {$InProve_Smarty->cutstr($row.val,0,50)}
            <span id="{$row.key|sha1}" style="display:none;" onclick='goChgPrm("edt","{$row.key}","{$row.val}");' class='pointer right'><img src="{$smarty.const._IMG_EDIT_SM_}" title="Edit entry."></span>
        </td>
    </tr>
    {/foreach}
    <tr class="config_entries">
        <td align="left" class="header" scope="row" colspan="2">
            <span style="cursor:pointer;float:right;font-size:.8em;" onclick='goChgPrm("add","","");'>Add Entry</span>
        </td>
    </tr>
    </body>
    </table>

    <form id="form_settag" action="/Ticket-Mgmt/additm" method="POST" enctype="multipart/form-data" class="toValidate" style="display:none;">
    <input type="hidden" name="ttsguid" value="{$smarty.request.ttsguid}">
    <input type="hidden" name="itmtyp" value="tag">
        <p>
            {$InProve_Smarty->msg("ui-icon-info","Add/Edit Tag")}
        </p>
        <div>
        <label for="key"><strong>Key</strong></label>
        <input type="input" id="key" name="key" size="30" value="" class="required">
        </div>
        <div>
        <label for="val"><strong>Value</strong></label>
        <input type="input" id="val" name="val" size="75" value="" class="required" style="width:80%;">
        </div>
        <div id="bottom_right" class="buttons right">
            {$smarty.const._FORM_BTN_INSERT_}
            &nbsp;or&nbsp;
            <a href="javascript:;" onclick='$("#form_settag").hide();'>cancel</a>&nbsp;
        </div>
    </form>                
    
</div>