{include file='../Wsite/header.phtml'}
<script>
    $(function() {
        $("#register form").ajaxForm({
		dataType: 'json',
        async: true,
		beforeSubmit: function() {
            $('#register .toValidate').validate({
               ignore: ":hidden"
            });
            if ( $('#register .toValidate').valid() ) {
                 $("#register button").prop("disabled", true).addClass("ui-state-disabled");
                return true;
            }
            return false;
		},
		success: function (r) {
            if (r.sts) {
                $("#register").html(r.msg);
            } else {
                notify("{$lL.__notification__}",r.msg,(r.sts ? "info":"error"),(r.sts ? 2500:5000));
                $("#register button").prop("disabled", false).removeClass("ui-state-disabled");
            }
		},
		error: function (jqXHR) {
            handleXHRerror(jqXHR);
		}
	});
    
    $("#register input:visible:first").focus();
});
</script>
<div id="content">
    <div class="inner">
        <div id="register">
            <h1>{$lL.__sign_up__}</h1>
            <h6>{$lL.__register_description__}.</h6>
            <hr />
            <form action="/Register/postr" method="POST" enctype="multipart/form-data" class="toValidate">
                <div class="row">
                    <label for="fullname">{$lL.__full_name__}</label>
                    <input type="text" name="fullname" value="" class="required">
                </div>
                <div class="row">
                    <label for="email">{$lL.__your_email__}</label>
                    <input type="text" name="email" value="" class="required email">
                </div>
                <div class="row">
                    <label for="password">{$lL.__create_password__}</label>
                    <input type="password"name="password" value="" class="required">
                </div>
                <div class="row">
                    <label for="confirm-password">{$lL.__confirm_password__}</label>
                    <input type="password" name="confirm-password" value="" class="required">
                </div>
                <div class="row">
                    {$smarty.const._FORM_BTN_SUBMIT_}
                </div>
            </form>
        </div>
    </div>
</div>

{include file="../Wsite/footer.phtml"}