
{include file='form.ready.js.inc'}

	<br>
	<form id="form_{$form_ctrlid}" action="form/post" method="POST" enctype="multipart/form-data" class="toValidate">
	<input type="hidden" name="parms" value="{$smarty.get.parms}">
		<table align="center" width="100%">
        {if $form_mode != $smarty.const._LBL_ADD_}
		<tr><td align="left">
			<b>{$lL.__group_id__}</b>
            </td>
			<td align="left">
            {$InProve_Smarty->cutstr($groupguid,0,$smarty.const._GUID_LEN_)}<p>
            </td>
		</tr>
        {/if}
		<tr><td align="left">
			<b>{$lL.__abv__description__}</b>
            </td>
			<td align="left">
			<input type="text" size="60" name="f|groupabv|unique" value="{$groupabv}" class="string required">
            </td>
		</tr>
		<tr><td align="left">
			<b>{$lL.__is_admin__}</b>
            </td>
			<td align="left">
			{$isadmin}
            </td>
		</tr>
        {if !$userParam && $form_mode != $smarty.const._LBL_ADD_}
		<tr><td align="left">
			<b>{$lL.__current_users_in_this_group__}</b>
            </td>
			<td align="left">
            <table align="center" width="100%" class="list">
            <thead>
            <tr>
                <th>{$lL.__user__}</th>
                <th>{$lL.__actions__}</th>
            </tr>
            </thead>
            <tbody>
                {foreach from=$usersINgroup key=k item=rec}
                <tr>
                    <td>{$InProve_Smarty->guid2name("gxt_users",$rec.userguid)}</td>
                    <td>{$rec.edtlnk}</td>
                </tr>
                {/foreach}
            </tbody>
            </table>
            </td>
		</tr>
        {/if}        
		</table>
        <div class="myhr"></div>
        <div class="buttons right">
        {if $form_mode != $smarty.const._LBL_ADD_}
            <button class="button-update" type="submit" name="submit_btn" value="{$smarty.const._LBL_UPDATE_}" title="{$smarty.const._TITLE_UPDATE_}">{$smarty.const._LBL_UPDATE_}</button>
            <button class="button-add" type="submit" name="submit_btn" value="{$smarty.const._LBL_ADD_}" title="{$smarty.const._TITLE_ADD_}">{$smarty.const._LBL_ADD_}</button>
            <button class="button-delete" type="submit" name="submit_btn" value="{$smarty.const._LBL_DELETE_}" title="{$smarty.const._TITLE_DELETE_}" onclick="return(confirm('{$smarty.const._TITLE_DELETE_} ?'));">{$smarty.const._LBL_DELETE_}</button>
        {else}
            <button class="button-add" type="submit" name="submit_btn" value="{$smarty.const._LBL_INSERT_}" title="{$smarty.const._TITLE_INSERT_}">{$smarty.const._LBL_INSERT_}</button>
        {/if}
        <button type="button" class="button-closethick" onclick="grid_remtab('{$smarty.get.grid_ctrlid}');" value="{$smarty.const._LBL_CANCEL_}" title="{$smarty.const._TITLE_CANCEL_}">{$smarty.const._LBL_CANCEL_}</button>
        </div>
        <br clear="all">
	</form>