
{include file='form.ready.js.inc'}

<script type="text/javascript">
$(document).ready(function(){

    if (!$("#fmistguid")[0].length) {
        $("#form_{$form_ctrlid} button").prop("disabled", true).addClass("ui-state-disabled");
    }
    
    $("#fmistguid").addClass("string required");

});
</script>

	<br>
	<form id="form_{$form_ctrlid}" action="form/post" method="POST" enctype="multipart/form-data" class="toValidate">
	<input type="hidden" name="parms" value="{$smarty.get.parms}">
        <h3>
            {$lL.__milestone_this_to_do__} {if $form_mode != $smarty.const._LBL_ADD_}{$lL.__is__}{else}{$lL.__will_be__}{/if} {$lL.__related_to__} {$mistguid}
            &nbsp;<span class="file" style="font-size:.8em;" onclick="loadappdiv('/Tbls-Mgmt/?tbl=gxt_milestones', null, '$(\'#addNew\').click();');">[+]</span>
        </h3>        
        <div class="myhr"></div>
		<table align="center" width="100%">
        {if $form_mode != $smarty.const._LBL_ADD_}
		<tr><td align="left">
			<b>{$lL.__todo_id__}</b>
			<td align="left">
            {$InProve_Smarty->cutstr($todoguid,0,$smarty.const._GUID_LEN_)}
            <p>
        {/if}
		<tr><td align="left">
			<b>{$lL.__description__}</b>
			<td align="left">
            <textarea rows="3" cols="80" name="f|todoabv" class="string required">{$todoabv}</textarea>
        <!--
		<tr><td align="left">
			<b>{$lL.__time_tracking__}</b>
			<td align="left">
            {$timetrack}&nbsp;{$lL.__enable_track_time_feature_for_items_in_this_to_do_list__} ?
        -->
		<tr><td align="left">
			&nbsp;
			<td align="right">
            <div class="buttons right">
			{if $form_mode != $smarty.const._LBL_ADD_}
                <button class="button-update" type="submit" name="submit_btn" value="{$smarty.const._LBL_UPDATE_}" title="{$smarty.const._TITLE_UPDATE_}">{$smarty.const._LBL_UPDATE_}</button>
                <button class="button-delete" type="submit" name="submit_btn" value="{$smarty.const._LBL_DELETE_}" title="{$smarty.const._TITLE_DELETE_}" onclick="return(confirm('{$smarty.const._TITLE_DELETE_} ?'));">{$smarty.const._LBL_DELETE_}</button>
			{else}
				<button class="button-add" type="submit" name="submit_btn" value="{$smarty.const._LBL_INSERT_}" title="{$smarty.const._TITLE_INSERT_}">{$smarty.const._LBL_INSERT_}</button>
			{/if}
            <button type="button" class="button-closethick" onclick="grid_remtab('{$smarty.get.grid_ctrlid}');" value="{$smarty.const._LBL_CANCEL_}" title="{$smarty.const._TITLE_CANCEL_}">{$smarty.const._LBL_CANCEL_}</button>
            </div>
		</table>
	</form>