
{include file='form.ready.js.inc'}

	<br>
	<form id="form_{$form_ctrlid}" action="form/post" method="POST" enctype="multipart/form-data" class="toValidate">
	<input type="hidden" name="parms" value="{$smarty.get.parms}">
		<table align="center" width="100%">
		<tr><td align="left">
			<b>{$lL.__abv__description__}</b>
            </td>
			<td align="left">
			<input type="text" size="60" name="f|cliabv" value="{$cliabv}" class="string required">
            </td>
		</tr>
		<tr><td align="left">
			<b>{$lL.__country__}</b>
            </td>
			<td align="left">
			{$countryid}
            </td>
		</tr>
        {if $form_mode != $smarty.const._LBL_ADD_}
		<tr><td align="left">
			<b>{$lL.__current_users_for_this__}</b>
            </td>
			<td align="left">
            <table align="center" width="100%" class="list">
            <thead>
            <tr>
                <th>{$lL.__username__}</th>
                <th>{$lL.__full_name__}</th>
                <th>{$lL.__active__}</th>
                <th>{$lL.__actions__}</th>
            </tr>
            </thead>
            <tbody>
                {foreach from=$usersINgroup key=k item=rec}
                <tr>
                    <td>{$rec.username}</td>
                    <td>{$InProve_Smarty->guid2name("gxt_users",$rec.userguid)}</td>
                    <td>{if $rec.active}{$smarty.const.__YES__}{else}{$smarty.const.__NO__}{/if}</td>
                    <td>{$rec.edtlnk}</td>
                </tr>
                {/foreach}
            </tbody>
            </table>
            </td>
		</tr>
        {/if}        
		</table>
        <div class="myhr"></div>
        <div class="buttons right">
        {if $form_mode != $smarty.const._LBL_ADD_}
            <button class="button-update" type="submit" name="submit_btn" value="{$smarty.const._LBL_UPDATE_}" title="{$smarty.const._TITLE_UPDATE_}">{$smarty.const._LBL_UPDATE_}</button>
            <button class="button-add" type="submit" name="submit_btn" value="{$smarty.const._LBL_ADD_}" title="{$smarty.const._TITLE_ADD_}">{$smarty.const._LBL_ADD_}</button>
            <button class="button-delete" type="submit" name="submit_btn" value="{$smarty.const._LBL_DELETE_}" title="{$smarty.const._TITLE_DELETE_}" onclick="return(confirm('{$smarty.const._TITLE_DELETE_} ?'));">{$smarty.const._LBL_DELETE_}</button>
        {else}
            <button class="button-add" type="submit" name="submit_btn" value="{$smarty.const._LBL_INSERT_}" title="{$smarty.const._TITLE_INSERT_}">{$smarty.const._LBL_INSERT_}</button>
        {/if}
        <button type="button" class="button-closethick" onclick="grid_remtab('{$smarty.get.grid_ctrlid}');" value="{$smarty.const._LBL_CANCEL_}" title="{$smarty.const._TITLE_CANCEL_}">{$smarty.const._LBL_CANCEL_}</button>
        </div>
        <br clear="all">
	</form>