
{include file='form.ready.js.inc'}

<script type="text/javascript">
$(document).ready(function(){
    
    $("#fprojguid").addClass("string required");
    
    $("#fkbclass").change(function() {
        $("#kboptsprops").show(); $("#barekb").prop("checked",false); toggleBareKb()
        $(".options").hide();
        $(".kbver_"+$("#fkbclass").val()).show();
    });
    $(".kbver_"+$("#fkbclass").val()).show();

    $("#conn_type").change(function() {
        chgConnType();
    });
    chgConnType();

    if (!$("#fprojguid")[0].length) {
        $("#form_{$form_ctrlid} button").prop("disabled",true);
    }
    
    $("#barekb").change(function() {
        toggleBareKb();
    });
    {if $form_mode != $smarty.const._LBL_ADD_}
        {if !$kbdir}
            $("#kboptsprops").hide();
            $("#barekb").prop("checked",true).prop("disabled",true);
            $("#kbdir").val("").prop("disabled",true);
        {else}
            $("#barekb").prop("checked",false).prop("disabled",true);
        {/if}
    {/if}

});

function toggleBareKb() {
    
    if ($("#barekb").is(":checked")) {
        $("#kbdir").val("{$lL.__empty_kb_will_be_initialized__}").prop("disabled",true);
        $("#kboptsprops").hide();
    } else {
        $("#kbdir").val("").prop("disabled",false);
        $("#kboptsprops").show();
    }

}

function chgConnType() {

    $(".sqlviamem, .sqlviatcp").hide();
    $("."+$("#conn_type").val()).show();
    if ($("#conn_type").val()=="sqlviamem") {
        $("#dbms_host").prop("size",32);
    } else {
        $("#dbms_host").prop("size",20);
    }

}
</script>

	<br>
	<form id="form_{$form_ctrlid}" action="form/post" method="POST" enctype="multipart/form-data" class="toValidate">
	<input type="hidden" name="parms" value="{$smarty.get.parms}">
        <h3>{$lL.__project_kb_belongs_to__} {$projguid}</h3>
        <div class="myhr"></div>
		<table align="center" width="100%">
		<tr><td align="left">
			<b>{$lL.__description__}</b>
            </td>
			<td align="left">
			<input type="text" size="60" id="kbdsc" name="f|kbdsc" value="{$kbdsc}" class="string required">
            </td>
		</tr>
		<tr><td align="left">
			<b>{$lL.__kb_class__}</b>
            </td>
			<td align="left">
			{$kbclass} <span class="options kbver_1111" style="font-size:.8em;"><input type="checkbox" id="barekb" name="barekb" value="1"> {$lL.__no_working_environment_in_server___}</span>
            </td>
		</tr>
		<tr><td align="left">
			<b>{$lL.__host___path__}</b>
            </td>
			<td align="left">
            {$hostname} @ <input type="text" size="60" id="kbdir" name="f|kbdir|unique" value="{$kbdir}" class="string required">
            </td>
		</tr>
		<tr><td align="left">
			<b>{$lL.__owner_responsible__}</b>
            </td>
			<td align="left">
			{$userguid}
            </td>
		</tr>
		<tr><td align="left">
			<b>{$lL.__parent_kb__}</b>
            </td>
			<td align="left">
			{$pkbguid}
            </td>
		</tr>
        {if in_array($smarty.const.__LAYER_ROLE__,array("Server","Website"))}
		<tr id="kboptsprops"><td align="left" colspan="2">
                <br>
                <fieldset><legend>{$lL.__kb_specific_options_properties__}</legend>

                <div class="myhr">{$lL.__versioning_properties__}</div>
                <table width="100%">
                    <tr style="display:none;" class="options kbver_1111 kbver_7500 kbver_8000 kbver_9000 kbver_10000 kbver_10100 kbver_10200 kbver_10300">
                        <td style="font-weight:bold;width:30%;">{$lL.__monitoring_status__}</td>
                        <td>{$kbmirror}&nbsp;&nbsp;{$qevent}</td>
                    </tr>
                    <tr style="display:none;" class="options kbver_1111">
                        <td style="font-weight:bold;">{$lL.__inclusions__}</td>
                        <td><input type="text" size="40" name="inclusions" id="inclusions" value="{$options.inclusions}"></td>
                    </tr>
                    <!--tr style="display:none;" class="options kbver_1111">
                        <td style="font-weight:bold;">{$lL.__exclusions__}</td>
                        <td><input type="text" size="40" name="exclusions" id="inclusions" value="{$options.exclusions}" disabled="disabled"></td>
                    </tr-->
                    <tr style="display:none;" class="options kbver_7500 kbver_8000 kbver_9000">
                        <td style="font-weight:bold;">{$lL.__model_s__to_version__}</td>
                        <td><input type="text" size="20" name="mdls2vers" id="mdls2vers" value="{$options.mdls2vers}">&nbsp;<span style="font-size:.8em;">({$lL.__comma_separated_values__})</span></td>
                    </tr>
                    <tr style="display:none;" class="options kbver_10000 kbver_10100 kbver_10200 kbver_10300">
                        <td style="font-weight:bold;">{$lL.__env_s__to_version__}</td>
                        <td><input type="text" size="20" name="mdls2vers" id="mdls2vers" value="{$options.mdls2vers}">&nbsp;<span style="font-size:.8em;">({$lL.__comma_separated_values__})</span></td>
                    </tr>
                    {if $form_mode != $smarty.const._LBL_ADD_}
                    <tr style="display:none;" class="options kbver_1111 kbver_7500 kbver_8000 kbver_9000 kbver_10000 kbver_10100 kbver_10200 kbver_10300">
                        <td style="font-weight:bold;width:30%;">{$lL.__current_progress___state__}</td>
                        {if $versyncsts.status == "connection_failed"}
                            <td class="red"><img src="{$smarty.const._IMG_ERR_SM_}" alt="error">&nbsp;&nbsp;Error connecting to KB [ {$InProve_Smarty->getSessVar("GxKbCnx.ecod")} : {$InProve_Smarty->getSessVar("GxKbCnx.emsg")} ]
                        {elseif $versyncsts.status == "not_finished"}
                            <td><img src="{$smarty.const._IMG_CLOCK_SM_}" alt="progress">&nbsp;&nbsp;{$lL.__last_run__} {$versyncsts.datetime}, {$versyncsts.vers} % {$lL.__is_versioned__and__} {$versyncsts.sync} % {$lL.__was_synchronized__}.
                        {elseif $versyncsts.status == "sync_pending"}
                            <td><img src="{$smarty.const._IMG_CLOCK_SM_}" alt="pending">&nbsp;&nbsp;{$lL.__synchronization_pending__}.
                        {elseif $versyncsts.status == "finished"}
                            <td class="green"><img src="{$smarty.const._IMG_SAVE_SM_}" alt="fully">&nbsp;&nbsp;{$lL.__fully_synchronized__}.
                        {else}
                            <td class="red"><img src="{$smarty.const._IMG_ERR_SM_}" alt="error">&nbsp;&nbsp;{$versyncsts|print_r} [ {$InProve_Smarty->getSessVar("GxKbCnx.ecod")} : {$InProve_Smarty->getSessVar("GxKbCnx.emsg")} ]
                        {/if}
                        </td>
                    </tr>
                    {/if}
                </table>

                <div class="myhr options kbver_10000 kbver_10100 kbver_10200 kbver_10300" style="display:none;">{$lL.__genexus_connection_properties__}</div>
                <table width="100%" class="options kbver_10000 kbver_10100 kbver_10200 kbver_10300" style="display:none;">
                    <tr>
                        <td style="font-weight:bold;width:30%;">{$lL.__genexus_base_directory__}</td>
                        <td>
                            <input type="text" size="60" name="gx_basedir" id="gx_basedir" value="{$options.gx_basedir}" class="string required">&nbsp
                            &nbsp;&laquo;&nbsp;
                            <a href="javascript:;" style="font-size:.8em;" onclick="$('#gx_basedir').val($('#gx_basedir_'+$('#fkbclass').val()).text());">{$lL.__from_system__}</a>&nbsp;|&nbsp;
                            <a href="javascript:;" style="font-size:.8em;" onclick="$('#gx_basedir').val('');">{$lL.__unset__}</a>
                            <span id="gx_basedir_10000" style="display:none;">{$gx_basedir_10000}</span>
                            <span id="gx_basedir_10100" style="display:none;">{$gx_basedir_10100}</span>
                            <span id="gx_basedir_10200" style="display:none;">{$gx_basedir_10200}</span>
                            <span id="gx_basedir_10300" style="display:none;">{$gx_basedir_10300} (Trial)</span>
                        </td>
                    </tr>
                    <tr style="display:none;">
                        <td style="font-weight:bold;">{$lL.__connection_driver__}</td>
                        <td>
                            <select name="dbms_driver" id="dbms_driver">
                                <option value="Sqlsrv">MS Sql Server</option>
                            </select>
                        </td>
                    </tr>
                    <tr>
                        <td style="font-weight:bold;">{$lL.__connection_type__}</td>
                        <td>
                            <select name="conn_type" id="conn_type">
                                <option value="sqlviamem" {if $conn_type=="sqlviamem"}selected{/if}>Shared Memory</option>
                                <option value="sqlviatcp" {if $conn_type=="sqlviatcp"}selected{/if}>TCP/IP</option>
                            </select>
                        </td>
                    </tr>
                    <tr>
                        <td style="font-weight:bold;">
                            <span class="sqlviamem" style="display:none;">{$lL.__server_name__}</span>
                            <span class="sqlviatcp" style="display:none;">{$lL.__host___port__}</span>
                        </td>
                        <td>
                            <input type="text" size="20" name="dbms_host" id="dbms_host" value="{$options.dbms_host}" class="string required">
                            <span class="sqlviamem" style="display:none;font-size:.8em;">
                            &nbsp;Eg; <a href="javascript:;" onclick="$('#dbms_host').val('localhost\\SQLEXPRESS');">localhost\SQLEXPRESS</a>
                            </span>
                            <span class="sqlviatcp" style="display:none;">
                            &nbsp;:&nbsp;
                            <input type="text" size="5" name="dbms_port" id="dbms_port" value="{$options.dbms_port}" class="string required">
                            <span style="font-size:.8em;">&nbsp;Eg; <a href="javascript:;" onclick="$('#dbms_host').val('localhost');$('#dbms_port').val('1433');">localhost : 1433</a></span>
                            </span>
                        </td>
                    </tr>
                    <tr>
                        <td style="font-weight:bold;">{$lL.__username___password__}</td>
                        <td>
                            <input type="text" size="20" name="dbms_user" id="dbms_user" value="{$options.dbms_user}">
                            &nbsp;/&nbsp;
                            <input type="password" size="20" name="dbms_pass" id="dbms_pass" value="{$options.dbms_pass}">
                            <span style="font-size:.8em;">&nbsp;{$lL.__for__windows_authentication___} <a href="javascript:;" onclick="$('#dbms_user,#dbms_pass').val('');">{$lL.__set_both_empty__}</a></span>
                        </td>
                    </tr>
                    <!--tr>
                        <td style="font-weight:bold;">Schema Name</td>
                        <td><input type="text" size="20" name="dbms_schema" id="dbms_schema" value="{$options.dbms_schema}"></td>
                    </tr-->
                </table>
                </fieldset>
            </td>
        {/if}
		</tr>
		</table>
        <div class="myhr"></div>
        <div class="buttons right">
        {if $form_mode != $smarty.const._LBL_ADD_}
            <button class="button-update" type="submit" name="submit_btn" value="{$smarty.const._LBL_UPDATE_}" title="{$smarty.const._TITLE_UPDATE_}">{$smarty.const._LBL_UPDATE_}</button>
            <button class="button-delete" type="submit" name="submit_btn" value="{$smarty.const._LBL_DELETE_}" title="{$smarty.const._TITLE_DELETE_}" onclick="return(confirm('{$smarty.const._TITLE_DELETE_} ?'));">{$smarty.const._LBL_DELETE_}</button>
        {else}
            <button class="button-add" type="submit" name="submit_btn" value="{$smarty.const._LBL_INSERT_}" title="{$smarty.const._TITLE_INSERT_}">{$smarty.const._LBL_INSERT_}</button>
        {/if}
        <button type="button" class="button-closethick" onclick="grid_remtab('{$smarty.get.grid_ctrlid}');" value="{$smarty.const._LBL_CANCEL_}" title="{$smarty.const._TITLE_CANCEL_}">{$smarty.const._LBL_CANCEL_}</button>
        </div>
        <br clear="all">
	</form>