<script type="text/javascript">
    $(document).ready(function(){

        $("#form_pass").ajaxForm({
            dataType:  'json',
            beforeSubmit: function() {
                $.blockUI({ message: '{$smarty.const._MSG_WAIT_}' });
            },
            success: function (r) {
                if (r.sts) {
                    window.location.reload();
                } else {
                    setTimeout("$.unblockUI();", 1500);
                    notify("Notification",r.msg,"error",7500);
                }
            },
            error: function (jqXHR) {
                handleXHRerror(jqXHR);
            }
        });

        CheckRepository();

    });

    function CheckRepository() {

        if ($("#login #username").val()) {
            $("#login #password").focus();
        } else {
            $("#login #username").focus();
        }

        $("#startupopts").html('{$smarty.const._MSG_WAIT_SM_}');
        $("#submitopts").html('{$smarty.const._MSG_WAIT_SM_}');
        $("#repository").attr("disabled", "disabled");

        jQuery.getJSON(
                "/index/passopts",
                { repository:$("#repository").val(), language:$("#language").val() },
                function (data, textStatus) {
                    $("#startupopts").html(data.startupopts);
                    $("#submitopts").html(data.submitopts);
                    $("#repository").removeAttr("disabled");
                    initializeButtons();
                    if (data.showconflnk) {
                        $("#configGear").show("slow");
                    }
                }
        ).error(function(jqXHR) {
            handleXHRerror(jqXHR);
            $("#submitopts").html('{$smarty.const._MSG_ERR_}');
        });

    }
</script>
<div id="login" style="text-align:center;width:500px;margin:0px auto;padding-top:50px;text-align:left;">
    <div id="login-box">
        <form id="form_pass" action="index/login" method="POST" enctype="multipart/form-data">
            <input type="hidden" name="sts" value="">
            <h2>{$lL.__welcome_to_gxtend__} {$smarty.const.__LAYER_ROLE__}</h2>
            <br>
            <div class="login-box-name">{$lL.__language__}:</div>
            <div class="login-box-field">
                {$language}
            </div>
            <div class="login-box-name">{$lL.__username__}:</div>
            <div class="login-box-field">
                <input class="form-login" type="text" maxlength="100" id="username" name="username" value="{$username}" title="">
            </div>
            <div class="login-box-name">{$lL.__password__}:</div>
            <div class="login-box-field">
                <input class="form-login" type="password" maxlength="20" id="password" name="password" value="" title="">
            </div>
            <div class="login-box-name">{$lL.__gxtsrv__}:</div>
            <div class="login-box-field">
                {$repository}
            </div>
            {if $smarty.const.__LAYER_ROLE__=="Client"}
            <div class="login-box-name"></div>
            <div class="login-box-field">
                <span id="startupopts" style="float:left;">{$smarty.const._MSG_WAIT_SM_}</span>
            </div>
            {/if}
            <br>
            <span class="login-box-options left">Ver. {$InProve_Smarty->gxtVersion()}</span>
            {if $smarty.const.__LAYER_ROLE__=="Client"}
            <span id="configGear" class="ui-icon ui-icon-wrench pointer left" style="margin-left:5px;display:none;" title="{$lL.__mdialog_config_title__}" onclick="mDialog('/Config/?sects=1,3', '{$lL.__mdialog_title__}', 600, 900);"></span>
            {/if}
            <br clear="all">
            <span id="submitopts" class="right">{$smarty.const._MSG_WAIT_SM_}</span>
        </form>
    </div>
</div>