<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN"
   "http://www.w3.org/TR/html4/strict.dtd">
<html lang="en">
<head>
    {include file='common_head.phtml'}
    {if $InProve_Smarty->getSessVar("LoginStatus.islogged")}
    <script type="text/javascript">
    $(document).ready(function(){

        $("#GenericDialog").dialog({
            bgiframe: true,
            autoOpen: false,
            modal: true,
            position: 'center',
            open: function(event, ui) { $("#GenericDialog").html('{$smarty.const._MSG_WAIT_SM_}'); }
        });

        loadappdiv('{$url}');
		
    });
    </script>
    {/if}
</head>
<body>
<div id="container" style="background:url('../img/main_bkg_{$smarty.const.__LAYER_ROLE__}.png') no-repeat right bottom;">
    {if $InProve_Smarty->getSessVar("LoginStatus.islogged")}
	<div id="east_panel" class="ui-layout-center">
        &nbsp;
	</div>
	{else}
		Session not logged in.
	{/if}

</div>

<div id="GenericDialog" title="Generic Dialog"></div>

</body>
</html>