<script type="text/javascript">
$(document).ready(function(){

	$("#form_catchup").ajaxForm({
		dataType:  'json',
        async: true,
		beforeSubmit: function() {
			$("#diffs").block({ message: '{$smarty.const._BAR_WAIT_}' });
            $("#div_catchup #bottom_left").html("");
		},
		success: function (r) {
            for ( var i in r.gxcons ) {
                if (r.gxcons[i] == "ok") {
                    $("#"+i).html("<img src='../img/icons/16/tick.png' alt='ok' title='{$lL.__object_successfully_imported__}'>");
                } else if (r.gxcons[i] == "wrn") {
                    $("#"+i).html("<img src='../img/icons/16/warning.png' alt='wrn' title='{$lL.__object_imported_with_warning_s___}'>");
                } else if (r.gxcons[i] == "err") {
                    $("#"+i).html("<img src='../img/icons/16/error.png' alt='err' title='{$lL.__object_not_imported__}'>");
                }
            }

            for ( var i in r.gxdele ) {
                if (r.gxdele[i] == "ok") {
                    $("#"+i).html("<img src='../img/icons/16/tick.png' alt='ok' title='{$lL.__object_successfully_deleted__}'>");
                } else if (r.gxdele[i] == "err") {
                    $("#"+i).html("<img src='../img/icons/16/error.png' alt='err' title='{$lL.__object_not_deleted__}'>");
                }
            }

            if (r.overall.xpzmsg) {
                if (r.overall.xpzsts) {
                    $("#div_catchup #bottom_left").html("<img src='../img/icons/32/tick.png' alt='ok' title='ok'> {$lL.__all_objects_were_successfully_packaged__}. [ <a href='/Download/download?file_guid="+r.overall.xpzmsg+"'>{$lL.__click_to_download__}</a> ]");
                } else {
                    $("#div_catchup #bottom_left").html("<img src='../img/icons/32/error.png' alt='err' title='err'> {$lL.__error_building__xpz_file__}. ["+r.overall.xpzmsg+"]");
                }
            } else {
                if (r.overall.okis > 0 && r.overall.wrns == 0 && r.overall.errs == 0) {
                    $("#div_catchup #bottom_left").html("<img src='../img/icons/32/tick.png' alt='ok' title='ok'> {$lL.__all_objects_were_successfully_imported__}. [ {$InProve_Smarty->get_popup_link('auditlog','/audit-Info/render?audguid="+r.overall.audguid+"',null,{$lL.__log_entry_details__},'800x600',{$lL.__click_to_view_log__})} ]");
                } else if (r.overall.wrns > 0 && r.overall.errs == 0) {
                    $("#div_catchup #bottom_left").html("<img src='../img/icons/32/warning.png' alt='wrn' title='wrn'> {$lL.__warnings_in_objects_import__}. [ {$InProve_Smarty->get_popup_link('auditlog','/audit-Info/render?audguid="+r.overall.audguid+"',null,{$lL.__log_entry_details__},'800x600',{$lL.__click_to_view_log__})} ]");
                } else if (r.overall.wrns > 0 || r.overall.errs > 0) {
                    $("#div_catchup #bottom_left").html("<img src='../img/icons/32/error.png' alt='err' title='err'> {$lL.__errors_warnings_in_objects_import__}. [ {$InProve_Smarty->get_popup_link('auditlog','/audit-Info/render?audguid="+r.overall.audguid+"',null,{$lL.__log_entry_details__},'800x600',{$lL.__click_to_view_log__})} ]");
                } else if (r.overall.okis == 0 && r.overall.wrns == 0 && r.overall.errs == 0) {
                    $("#div_catchup #bottom_left").html("<img src='../img/icons/32/error.png' alt='err' title='err'> {$lL.__could_not_obtain_lock_on_kb__}.");
                }
            }

            $("#diffs").unblock();
            setsubmitsts("#form_catchup .objlst", "#form_catchup button");
        },
        error: function (jqXHR) {
            handleXHRerror(jqXHR);
        }
	});

    initializeButtons();

    setsubmitsts("#form_catchup .objlst", "#form_catchup button");

    $("#east_panel #project #div_catchup img.tip").cluetip({ splitTitle: "|" });

    filter_by_objsts();

});

function filter_by_objsts() {

    $("#form_catchup > table > tbody > tr").show();
    if (!$("#div_catchup #gen1chk").prop("checked")) { $("#form_catchup > table > tbody > tr.gen1").hide(); }
    if (!$("#div_catchup #gen2chk").prop("checked")) { $("#form_catchup > table > tbody > tr.gen2").hide(); }
    if (!$("#div_catchup #olderchk").prop("checked")) { $("#form_catchup > table > tbody > tr.OLDER").hide(); }
    if ($("#periods_filter").val()) {
        $("#form_catchup > table > tbody > tr").not("."+$("#periods_filter").val()).hide();
    }

    var $visibleRows = $('#form_catchup > table > tbody > tr:visible').length;
    var $hiddenRows = $('#form_catchup > table > tbody > tr:hidden').length;

    if ($hiddenRows) { $("#div_catchup #filterctrls").show(); }
    $("#div_catchup #resultrows").text($visibleRows);

}
</script>
<div id="div_catchup">

    {if !is_array($local_changes)}
        {$InProve_Smarty->msg("ui-icon-alert", $local_changes)}
    {else}
        <div class="myhr"></div>
        <div class="left">
            <img src="{$smarty.const._IMG_CATCHUP_SM_}" alt="{$smarty.const._LBL_CATCHUP_}" title="{$smarty.const._LBL_CATCHUP_}"> {$lL.__catchup_changes_from__local_history_repo___}
            &nbsp;|&nbsp;{$periods_filter}
            <span id="filterctrls" style="display:none;">
            &nbsp;|&nbsp;
            <input type="checkbox" id="gen1chk" name="gen1chk" onchange="filter_by_objsts();"> <img class="tip" alt="gen1" src="../img/icons/16/lightning_green.png" title="{$lL.__visual_tag_information_objects_tagged_with_this_icon_were_detected_as_being_automatically_generated_by_some_genexus_process__eg__from_a_pattern_instance___}.">&nbsp;
            <input type="checkbox" id="gen2chk" name="gen2chk" onchange="filter_by_objsts();" checked> <img class="tip" alt="gen2" src="../img/icons/16/lightning_red.png" title="{$lL.__visual_tag_information_objects_tagged_with_this_icon_were_detected_as_being_automatically_generated_by_some_genexus_process__eg__from_a_pattern_instance__but_some_of_it_has_been_modified_by_a_user__}.">&nbsp;
            <input type="checkbox" id="olderchk" name="olderchk" onchange="filter_by_objsts();"> <img class="tip" alt="older" src="../img/icons/16/warning.png" title="{$lL.__visual_tag_information_objects_tagged_with_this_icon_were_detected_as_being_older_than_its_target__}.">
            </span>
        </div>
        <div class="column right">
            <span id="resultrows"></span> {$lL.__row_s___}
        </div>
        <br clear="all">

        <form id="form_catchup" action="catchup/catchup" method="POST" enctype="multipart/form-data">
        <input type="hidden" name="projguid" value="{$smarty.request.projguid}">
        <input type="hidden" name="kbguid" value="{$smarty.request.kbguid}">
        <input type="hidden" name="mdlid" value="{$smarty.request.mdlid}">
            <table width="100%" align="center" class="list">
            <thead>
                <tr><th>{$lL.__object__}</th><th>{$lL.__description__}</th><th>{$lL.__modified___server__} &darr;</th><th><span style='cursor:pointer;' title='{$smarty.const._TITLE_CHKALL_}' onclick='setcheck("#form_catchup .objlst");setsubmitsts("#form_catchup .objlst", "#form_catchup button");'>&nbsp;{$smarty.const._LBL_CHKALL_}</span></th></tr>
            </thead>
            <tbody>
                {foreach from=$local_changes key=k item=rec}
                <tr class='{cycle values="odd,even"} gen{$rec.gxinfo.generated} {$rec.gxinfo.COMP} {$rec.gxinfo.updperiod}' style="{if $rec.gxinfo.generated==1 || $rec.gxinfo.COMP=='OLDER'}display:none;{/if}">
                <td>&nbsp;
                    {if $rec.gxinfo.objcls!=111}
                    <img src="../img/gx/objclass/{$gx_objcls[$rec.gxinfo.objcls].small}.png" title="{$gx_objcls[$rec.gxinfo.objcls].long}">
                    &nbsp;{$rec.gxinfo.objnam}
                    {else}
                    <img src="../img/icons/16/file.png" title="File">
                    &nbsp;{$rec.gxinfo.objnam|basename}
                    {/if}
                </td>
                <td>
                    &nbsp;{$rec.gxinfo.objdsc}
                    {if $rec.gxinfo.lock && $rec.gxinfo.lock.setuserguid != $InProve_Smarty->getSessVar("MyProfile.userdata.userguid")}
                    &nbsp;<img class="tip" alt="locked" src="{$smarty.const._IMG_LOCK_SM_}" title="Object's Lock Status|'{$InProve_Smarty->guid2name('gxt_users', $rec.gxinfo.lock.setuserguid)}' has an active lock on this object since '{$InProve_Smarty->ts2str($rec.gxinfo.lock.setts)}'">
                    {/if}
                </td>
                <td align="center">
                    &nbsp;{$InProve_Smarty->ts2str($rec.gxinfo.objupdts)}
                    {if $rec.gxinfo.COMP=="NEW"}
                    &nbsp;<img alt="new" src="../img/icons/16/new.png" title="{$lL.__does_not_exist_in_target__}.">
                    {elseif $rec.gxinfo.COMPREF=="DELETED_FROM_GXKB"}
                    &nbsp;<img alt="del" src="../img/icons/16/cleanup.png" title="{$lL.__object_detected_as_deleted_in_source__}.">
                    {elseif $rec.gxinfo.COMP=="OLDER"}
                    &nbsp;<img alt="older" src="../img/icons/16/warning.png" title="{$lL.__target_modified_on__} {$InProve_Smarty->ts2str($rec.gxinfo.COMPREF)}">
                    {/if}
                    {if $rec.gxinfo.generated==1}
                    &nbsp;<img alt="gen1" src="../img/icons/16/lightning_green.png" title="{$lL.__automatically_generated__}.">
                    {else if $rec.gxinfo.generated==2}
                    &nbsp;<img alt="gen2" src="../img/icons/16/lightning_red.png" title="{$lL.__automatically_generated_but_modified__}.">
                    {/if}
                </td>
                <td align="center">
                    {if $rec.gxinfo.lock && $rec.gxinfo.lock.setuserguid == $InProve_Smarty->getSessVar("MyProfile.userdata.userguid")}
                        <img class="tip" alt="locked" src="{$smarty.const._IMG_LOCK_OWN_SM_}" title="{$lL.__object_s_lock_status_you_have_an_active_lock_on_this_object_since__} '{$InProve_Smarty->ts2str($rec.gxinfo.lock.setts)}'">
                    {else}
                        {if $rec.b64}
                        <span id="{$rec.b64|sha1}">
                            <input class="objlst" type=checkbox name='checked_objs[]' value='{$rec.b64}' onclick='setsubmitsts("#form_catchup .objlst", "#form_catchup button");'>
                        </span>
                        {/if}
                    {/if}
                </td>
                </tr>
                {/foreach}
            </tbody>
            </table>

        <div class="myhr"></div>

        <div id="bottom_left" class="left">
            {include file='../skel/ttp.phtml' ttpLabel={$lL.__ttp__} secLabel={$lL.__second__} topLabel={$lL.__top__}}
        </div>
        <div  id="bottom_right" class="buttons right">
            <input type="radio" name='catchuptype' value='import' checked>&nbsp;<img src='{$smarty.const._IMG_CATCHUP_SM_}'> {$smarty.const._LBL_CATCHUP_}&nbsp;&nbsp;
            <input type="radio" name='catchuptype' value='getxpz'>&nbsp;<img src='{$smarty.const._IMG_PACKAGE_SM_}'> {$smarty.const._LBL_PACKAGE_}&nbsp;&nbsp;
            <p>
            <div style="float:right;">
                <button class="button-circle" type="submit" name="submit_btn" value="{$smarty.const._LBL_SUBMIT_}" title="{$smarty.const._TITLE_SUBMIT_}">{$smarty.const._LBL_SUBMIT_}</button>
            </div>
        </div>

        </form>
        <br clear="all">
    {/if}
</div>