<script type="text/javascript">
$(document).ready(function(){

    $("#form_config").ajaxForm({
        dataType: 'json',
        async: false,
        beforeSubmit: function() {
            $("#form_config").validate({
               ignore: ":hidden"
            });
            if ( $("#form_config").valid() ) {
                 $("#form_config .submit_btn_holder").toggle();
                return true;
            }
            return false;            
        },
        success: function (r) {
            notify("Notification",r.msg,(r.sts ? "info" : "error"),(r.sts ? 2500 : 7500));
            if (r.sts) {
                setTimeout('window.location.reload();', 2500);                
            } else {
                $("#form_config .submit_btn_holder").toggle();
            }
        },
        error: function (jqXHR) {
            handleXHRerror(jqXHR);
        }
    });

    $("input:radio[name=publisher]").change(function() {
        opt = $("input:radio[name=publisher]:checked").val();
        if (opt == "all") {
            $("#section_4 > table > tbody > tr").show();
        } else {
            $("#section_4 > table > tbody > tr").hide();
            $("#section_4 > table > tbody > tr."+opt).show();
        }
    });

    {if $smarty.request.secti}
    togglebwsections({$smarty.request.secti});
    {else}
    $("#secsel > span:first").click();
    {/if}

    $("#form_config input:text").blur(function() { checkValues(); });
    
    checkValues();

});

function checkValues(entryspec) {
                        
    $("#form_config input:text").each( function(idx,obj) {
    if (!entryspec || entryspec==$(obj).attr("entryname")) {
        if ($(obj).val() && $(obj).val() != "__NEED_SETTING__" && $("#check_"+hex_sha1($(obj).attr("entryname"))).attr("id")) {
            $("#check_"+hex_sha1($(obj).attr("entryname"))).html("").addClass("msg_wait small");
            $.getJSON(
                    "/Config/check",
                    { chkif:"Available" , chkval:$(obj).val(), entryname:$(obj).attr("entryname") },
                    function(r) {
                        $("#check_"+hex_sha1($(obj).attr("entryname"))).removeClass("msg_wait small");
                        if (r.sts=="ok") {
                            $("#check_"+hex_sha1($(obj).attr("entryname"))).html("<img src='../img/icons/16/tick.png' alt='ok' title='"+r.msg+"'>");
                        } else if (r.sts=="err") {
                            $("#check_"+hex_sha1($(obj).attr("entryname"))).html("<img src='../img/icons/16/error.png' alt='ok' title='"+r.msg+"'>");
                        } else {
                            $("#check_"+hex_sha1($(obj).attr("entryname"))).html("");
                        }
                    }
            );
        } else {
            $("#check_"+hex_sha1($(obj).attr("entryname"))).html("");
        }
        
        if ($(obj).val() == "__NEED_SETTING__") {
            $("#label_"+hex_sha1($(obj).attr("entryname"))).css("color","red");
        }
        if ($(obj).val() != $("#input_"+hex_sha1($(obj).attr("entryname"))).attr("entryvalue")) {
            $("#label_"+hex_sha1($(obj).attr("entryname"))).css("color","#4581DF");
        } else {
            $("#label_"+hex_sha1($(obj).attr("entryname"))).css("color","");
        }
    }
    });
    
}

function deleteFile(file2delete) {
    
    $("#form_config .buttons").hide();    
    if (confirm('Confirm File Deletion ?')) {
        $.getJSON(
                "/Config/delfile",
                { file2delete:file2delete },
                function(r) {
                    notify("Notification",r.msg,(r.sts ? "info" : "error"),(r.sts ? 2500 : 7500));
                    if (r.sts) {                        
                        setTimeout('window.location.reload();', 2500);
                    } else {
                        $("#form_config .buttons").show("slow");
                    }
                }
        );
    } else {
        $("#form_config .buttons").show("slow");
    }

}

function togglebwsections(id) {

    if (id=="next") {
        $("#form_config .section").each( function(idx,obj) {
            if ($(obj).is(":visible")) {
            id = idx + 1 + 1;
            }
        });
    }

    if (!$("#section_"+id).is(":visible")) {
        if (id==4) {
            //$("#form_config").hide();
        } else {
            //$("#form_config").show();
        }
        $(".section").hide();
        $("#section_"+id).show();
    }

}
</script>

<div id="secsel" class="right" style="font-size:.8em;">
{foreach $sectionLst as $i => $label name=sects}
    {if $label}
    <span onclick="togglebwsections({$smarty.foreach.sects.iteration});" class="file">{$label}</span>
    {/if}
    {if !$smarty.foreach.sects.last}&nbsp;|&nbsp;{/if}
{/foreach}
</div>
<h3>About</h3>
<p>This process will take care of setting primary configuration values, please take a moment to visually check the values are ok before proceeding.</p>
<form id="form_config" action="/Config/post" method="POST" enctype="multipart/form-data">
    {foreach $sectionLst as $i => $label name=sects}
    <div id="section_{$smarty.foreach.sects.iteration}" class="section" style="display:none;">

        {include file="section$i.phtml"}
        
        <div class="myhr"></div>
        <div class="buttons right">
        {if !$smarty.foreach.sects.last && $i<3}
            <button type="button" class="button-next" title="{$smarty.const._TITLE_NEXT_}" onclick="togglebwsections('next');">{$smarty.const._LBL_NEXT_}</button>
        {/if}
        {if $i==3}
            <div class="submit_btn_holder">
            {$smarty.const._FORM_BTN_UPDATE_}
            &nbsp;or&nbsp;
            <a href="javascript:;" onclick='$("#GenericDialog").dialog("close");'>cancel</a>&nbsp;
            </div>
            <div class="submit_btn_holder" style="display:none;">
            {$smarty.const._BAR_WAIT_}
            </div>
        {/if}
        </div>        
    </div>
    {/foreach}        
</form>