{*LNG@index.phtml*}
<div class="myhr">{$lL.__programs_currently_installed__}</div>

<input type="radio" name="publisher" value="{sha1(strtolower('artech'))}" checked>&nbsp;Artech
<input type="radio" name="publisher" value="{sha1(strtolower('inprove-it'))}">&nbsp;InProve
<input type="radio" name="publisher" value="all">&nbsp;{$lL.__all__}
<table align="center" width="100%" class="list">
<thead>
    <tr><th>{$lL.__name__}</th><th>{$lL.__publisher__}</th><th>{$lL.__version__}</th></tr>
</thead>
<tbody>
{foreach $lstSoft as $entry_id => $entry_data}
{if $entry_data.DisplayName}
<tr class="{sha1(strtolower($entry_data.Publisher))}" {if strtolower($entry_data.Publisher)!="artech"}style="display:none;"{/if}>
    <td>
        {$entry_data.DisplayName|utf8_encode}
    </td>
    <td>
        {$entry_data.Publisher|utf8_encode}
    </td>
    <td>
        {$entry_data.DisplayVersion}
    </td>
</tr>
{/if}
{/foreach}
</tbody>
</table>