{foreach $entriesLst.gxtend_servers as $server_name => $server_props}
<div class="myhr">Metadata Connection(s) Properties (for {$server_name})</div>
<table id="connproptbl" align="center" width="95%">
{foreach $server_props as $prop_name => $prop_value}
<tr>
    <td style="text-align:left;font-weight:bold;width:30%;">
        <span id="label_{$prop_name|sha1}">{$entriesDef.$prop_name.label|default:$prop_name}</span>
        {if $entriesDef.$prop_name.check}<span id="check_{$prop_name|sha1}" class="right"></span>{/if}
    </td>
    <td align="left">
        <input type="{$entriesDef.$prop_name.inputtype|default:'text'}" size="70" id="input_{$prop_name|sha1}" class="{$entriesDef.$prop_name.class}" name="gxtend_servers[{$server_name}][{$prop_name}]" value="{$prop_value}" {if $entriesDef.$prop_name.readonly}readonly="readonly"{/if} entryname="{$prop_name}" entryvalue="{$prop_value}">
        {if $entriesDef.$prop_name.defvalue}
        &nbsp;&laquo;&nbsp;
        {if $entriesDef.$prop_name.defvalue != "__UNSET__"}
        <a href="javascript:;" class="setDefVal" style="font-size:.8em;" onclick="$('#input_{$prop_name|sha1}').val('{$entriesDef.$prop_name.defvalue}');checkValues('{$prop_name}');">Default</a>&nbsp;|&nbsp;
        {/if}
        <a href="javascript:;" {if $entriesDef.$prop_name.defvalue == "__UNSET__"}class="setDefVal"{/if} style="font-size:.8em;" onclick="$('#input_{$prop_name|sha1}').val('');checkValues('{$prop_name}');">Unset</a>
        {/if}
        {if $prop_name == "schema" && $smarty.const.__LAYER_ROLE__ == "Client"}&nbsp;|&nbsp;<a id="delete_{$prop_value|sha1}" href="javascript:;" style="font-size:.8em;" onclick="deleteFile($('#input_{$prop_name|sha1}').val());">Unlink</a>{/if}
    </td>
</tr>
{/foreach}
</table>
<p>You can help you out by <a href="javascript:;" onclick="$('#connproptbl .setDefVal').click();">clicking here</a> to get all the above boxes populated by GxTend.</p>
{/foreach}