<div class="myhr">__LNG__Programs Currently Installed__LNG__</div>

<input type="radio" name="publisher" value="{sha1(strtolower('artech'))}" checked>&nbsp;Artech
<input type="radio" name="publisher" value="{sha1(strtolower('inprove-it'))}">&nbsp;InProve
<input type="radio" name="publisher" value="all">&nbsp;__LNG__All__LNG__
<table align="center" width="100%" class="list">
<thead>
    <tr><th>__LNG__Name__LNG__</th><th>__LNG__Publisher__LNG__</th><th>__LNG__Version__LNG__</th></tr>
</thead>
<tbody>
{foreach $lstSoft as $entry_id => $entry_data}
{if $entry_data.DisplayName}
<tr class="{sha1(strtolower($entry_data.Publisher))}" {if strtolower($entry_data.Publisher)!="artech"}style="display:none;"{/if}>
    <td>
        {$entry_data.DisplayName|utf8_encode}
    </td>
    <td>
        {$entry_data.Publisher|utf8_encode}
    </td>
    <td>
        {$entry_data.DisplayVersion}
    </td>
</tr>
{/if}
{/foreach}
</tbody>
</table>