<div id="fsysbrw">
{$InProve_Smarty->cutstr($curr_dir,0,80)}
<table width="100%" align="center" class="list">
<thead>
    <tr><th>__LNG__Name__LNG__</th><th>__LNG__Date Modified__LNG__</th><th>__LNG__Size__LNG__</th></tr>
</thead>
<tfoot>
    <tr><th colspan="3">{$fld_cont|@count} __LNG__Object(s)__LNG__</th></tr>
</tfoot>
<tbody>
    {foreach from=$fld_cont key=k item=rec}
        <tr>
        <td>
            {if $rec.mimetype=='folder'}
            <span class="file" onclick="$('#fsysbrw').block();$('#fsysbrw').load('/Fsys-Brw/?data2browse={$rec.b64info}');">
                <img src="../img/icons/16/mimetypes/folder.png">&nbsp;
                {$rec.basename}
            </span>
            {else}
            <a href="/Download/download?file_guid={$rec.b64info}">
                <img src="../img/icons/16/mimetypes/{if file_exists('../img/icons/16/mimetypes/$rec[mimetype].png')}{$rec[mimetype]}.png{else}blank.png{/if}">&nbsp;
                {$rec.basename}
            </a>
            {/if}
        </td>
        <td align="center">{$rec.updated}</td>
        <td align="center">{$rec.filesize}</td>
        </tr>
    {/foreach}
</tbody>
</table>
</div>