{include file="../skel/header.phtml"}
<script type="text/javascript">
$(document).ready(function(){
    $("#tabs").tabs();
});
</script>

    <h2 style="float:right;">{$lL.__log_entry_details__}&nbsp;</h2>
    <br clear="all">
    <table align="center" width="100%" class="list-horizontal">
    <tr>
		<td align="left" class="header first" scope="row">
			{$lL.__id__}
		</td>
		<td align="left" class="first">
			{$record.audguid}
		</td>
	</tr>
    <tr>
		<td align="left" class="header" scope="row">
			{$lL.__code___desc___}
		</td>
		<td align="left">
			{$record.code} / {$record.code2desc|default:"Not Found"}
		</td>
	</tr>
    <tr>
		<td align="left" class="header" scope="row">
			{$lL.__user__}
		</td>
		<td align="left">
			{$InProve_Smarty->guid2name("gxt_users",$record.userguid)}
		</td>
	</tr>
    <tr>
		<td align="left" class="header" scope="row">
			{$lL.__datetime__}
		</td>
		<td align="left">
			{$InProve_Smarty->ts2str($record.timestamp)}
		</td>
	</tr>
    <tr>
		<td align="left" class="header" scope="row">
			{$lL.__gxtend_version_build__}
		</td>
		<td align="left">
			{$record.gxtver}
		</td>
	</tr>
    </table>
    <p>
    <div id="tabs">
    <ul>
        {if $record.masklog}
        <li><a href="#tab-1"><span>{$lL.__log__}</span></a></li>
        {/if}
        <li><a href="#tab-2"><span>{$lL.__raw_log__}</span></a></li>
        <li><a href="#tab-3"><span>{$lL.__process__}</span></a></li>
    </ul>
        {if $record.masklog}
        <div id="tab-1">
            {$record.masklog}
        </div>
        {/if}
        <div id="tab-2">
            {$InProve_Smarty->dBug($record.logtxt)}
        </div>
        <div id="tab-3">
            {$InProve_Smarty->dBug($record.prcdmp.PS_STAT)}
        </div>
    </div>

{include file="../skel/footer.phtml"}