<div id="log_commit">
    <div class="column left">
        <strong>__LNG__Source__LNG__ : </strong> {$InProve_Smarty->guid2name('gxt_kbs', $logData.kbguid)}
        <br>
        <strong>__LNG__Path__LNG__ : </strong> {$logData.kbpath}
    </div>
    <div class="column right">
        <strong>__LNG__TTP__LNG__ : </strong> {$InProve_Smarty->sec2str($logData.end - $logData.start)}
        <br>
        <strong>__LNG__Average__LNG__ : </strong> {$InProve_Smarty->sec2str($logData.ttpavg)}
    </div>
    <br clear="all">
    <div class="myhr"></div>

    <div class="column left">
        __LNG__Objects are listed in the order they were submitted__LNG__.
    </div>
    <div class="column right">
        {count($logData.checked_objs)} __LNG__row(s)__LNG__
    </div>
    <br clear="all">    
    <table width="100%" align="center" class="list">
    <thead>
        <tr><th>__LNG__Object__LNG__</th><th>__LNG__Modified__LNG__ &darr;</th><th>__LNG__TTP__LNG__</th><th>__LNG__Sts__LNG__</th></tr>
    </thead>
    <tbody>
        {foreach $logData.checked_objs as $k => $rec}
        <tr class='{cycle values="odd,even"}'>
        <td>&nbsp;
            {if $rec.gxinfo.objcls!=111}
            <img src="../img/gx/objclass/{$gx_objcls[$rec.gxinfo.objcls].small}.png" title="{$gx_objcls[$rec.gxinfo.objcls].long}">
            &nbsp;{$rec.gxinfo.objnam}
            {else}
            <img src="../img/icons/16/file.png" title="File">
            &nbsp;{$rec.gxinfo.objnam|basename}
            {/if}
        </td>
        <td align="center">
            &nbsp;{$InProve_Smarty->ts2str($rec.gxinfo.objupdts)}
            {if $rec.gxinfo.COMP=="NEW" && $rec.gxinfo.COMPREF!="DELETED_FROM_GXKB"}
            &nbsp;<img alt="new" src="../img/icons/16/new.png" title="__LNG__Does not exist in target__LNG__.">
            {elseif $rec.gxinfo.COMP=="NEW" && $rec.gxinfo.COMPREF=="DELETED_FROM_GXKB"}
            &nbsp;<img alt="del" src="../img/icons/16/cleanup.png" title="__LNG__Object detected as deleted in source__LNG__.">
            {elseif $rec.gxinfo.COMP=="OLDER"}
            &nbsp;<img alt="older" src="../img/icons/16/warning.png" title="__LNG__Target modified on__LNG__ {$InProve_Smarty->ts2str($rec.gxinfo.COMPREF)}">
            {/if}
            {if $rec.gxinfo.generated==1}
            &nbsp;<img alt="gen1" src="../img/icons/16/lightning_green.png" title="__LNG__Automatically generated__LNG__.">
            {else if $rec.gxinfo.generated==2}
            &nbsp;<img alt="gen2" src="../img/icons/16/lightning_red.png" title="__LNG__Automatically generated BUT modified__LNG__.">
            {/if}
        </td>
        <td align="center">            
            {$InProve_Smarty->sec2str($rec.end - $rec.start)}
        </td>
        <td align="center">            
            {if $rec.sts=="ok"}
            <img src='../img/icons/16/tick.png' alt='{$rec.sts}' title='{$rec.sts}'>
            {else}
            <img src='../img/icons/16/error.png' alt='{$rec.sts}' title='{$rec.sts}'>
            {/if}
        </td>
        </tr>
        {/foreach}
    </tbody>
    </table>
</div>