<div id="log_push">
    <div class="column left">
        <strong>{$lL.__project__} : </strong> {$InProve_Smarty->guid2name('gxt_projects', $logData.projguid)}
    </div>
    <div class="column right">
        <strong>{$lL.__ttp__} : </strong> {$InProve_Smarty->sec2str($logData.end - $logData.start)}
    </div>
    <br clear="all">
    <div class="myhr"></div>

    <div class="column left">
        <p><strong>{$lL.__command__} : </strong> {$logData.stdout.env.command}</p>
        <p><strong>{$lL.__outsts__} : </strong> {$logData.stdout.sts}</p>
        <p><strong>{$lL.__output__} : </strong> {$logData.stdout.out}</p>
    </div>
    <br clear="all">    
</div>