<script type="text/javascript">
$(document).ready(function(){

	$("#form_lock").ajaxForm({
		dataType:  'json',
        async: true,
		beforeSubmit: function() {
            $("#div_regexp #bottom_left").html("");
			$("#div_regexp").block({ message: '{$smarty.const._BAR_WAIT_}' });
		},
		success: function (r) {
            if (r.flag.sts == "ok") {
                $("#div_regexp #bottom_left").html("<img src='../img/icons/32/tick.png' alt='ok' title='ok'> {$lL.__matching_rule_successfully_added_to_list__}");
                $("#gobtn").click();
            } else {
                $("#div_regexp #bottom_left").html("<img src='../img/icons/32/error.png' alt='err' title='err'> {$lL.__could_not_add_matching_rule_successfully_to_list__}");
                $("#div_regexp").unblock();
            }
        },
        error: function (jqXHR) {
            handleXHRerror(jqXHR);
        }
	});

    initializeButtons();

});
</script>
<div id="div_regexp">
    <form id="form_lock" action="/Lock/flag" method="POST" enctype="multipart/form-data">
    <input type="hidden" name="projguid" value="{$smarty.request.projguid}">
    <input type="hidden" name="kbguid" value="{$smarty.request.kbguid}">
    <input type="hidden" name="mdlid" value="{$smarty.request.mdlid}">
    <input type="hidden" name="flagtype" value="ignore">
        <p>
        &nbsp;<strong>{$lL.__matching_class__} {$classType}</strong>
        &nbsp;<span style="font-size:0.8em;">{$InProve_Smarty->msg("ui-icon-info","{$lL.__object_class_the__matching_expression__will_be_used_on__}")}</span>
        </p>
        <p>
        &nbsp;<strong>{$lL.__matching_expression__}</strong>
        <br><textarea id="regExpCode" name="regExpCode" cols="80" rows="3"></textarea>
        </p>
        <p>
        &nbsp;<strong>{$lL.__matching_expression_examples__};</strong>
            <ul>
            <li style="padding:.5em;">{$lL.__normal_regular_expression__regexp____eg___strong__a_href__javascript____onclick______regexpcode___val___gx_i______gx_i__a___strong__will_match_all_objects_whose_name_start_with__gx___while__i__will_makes_the_matching_case_insensitive___}</li>
            <li style="padding:.5em;">{$lL.__special_case_for_genexus_x_kbs____strong__a_href__javascript____onclick______regexpcode___val___generated_______generated___a___strong__will_match_all_objects_that_gxtend_detects_as_being_automatically_generated__it_matches_both__generated_and_not_modified__and_also__generated_but_modified____}</li>
            <li style="padding:.5em;">{$lL.__special_case_for_genexus_x_kbs____strong__a_href__javascript____onclick______regexpcode___val___generated_and_not_modified_______generated_and_not_modified___a___strong__will_match_all_objects_that_gxtend_detects_as_being_automatically_generated__it_only_matches__generated_and_not_modified____}</li>
            </ul>
        </p>

        <div class="myhr"></div>

        <div id="bottom_left" class="left">
            &nbsp;
        </div>
        <div  id="bottom_right" class="buttons right">
            <button class="button-circle" type="submit" name="submit_btn" value="{$smarty.const._LBL_SUBMIT_}" title="{$smarty.const._TITLE_SUBMIT_}">{$smarty.const._LBL_SUBMIT_}</button>
        </div>
    </form>
    <br clear="all">

</div>