<script type="text/javascript">
$(document).ready(function(){

	$("#form_unlock").ajaxForm({
		dataType:  'json',
        async: true,
		beforeSubmit: function() {
            $("#div_ignlst #bottom_left").html("");
			$("#diffs").block({ message: '{$smarty.const._BAR_WAIT_}' });
		},
		success: function (r) {
            for ( var i in r.unflaglist ) {
                if (r.unflaglist[i] == "ok") {
                    $("#"+i).html("<img src='../img/icons/16/tick.png' alt='ok' title='"+r.unflaglist[i]+"'>");
                } else {
                    $("#"+i).html("<img src='../img/icons/16/error.png' alt='err' title='"+r.unflaglist[i]+"'>");
                }
            }

            if (r.unflaglist.sts == "ok") {
                $("#div_ignlst #bottom_left").html("<img src='../img/icons/32/tick.png' alt='ok' title='ok'> {$lL.__entries_were_successfully_removed_from_list__}");
                $("#diffs").unblock();
            } else {
                $("#div_ignlst #bottom_left").html("<img src='../img/icons/32/error.png' alt='err' title='err'> {$lL.__some_entries_could_not_be_removed_from_list__}");
                $("#diffs").unblock();
            }

            setsubmitsts("#form_unlock .objlst", "#form_unlock button");
        },
        error: function (jqXHR) {
            handleXHRerror(jqXHR);
        }
	});

    initializeButtons();

    setsubmitsts("#form_unlock .objlst", "#form_unlock button");

    $("#east_panel #project #div_ignlst img.tip").cluetip({ splitTitle: "|" });

});
</script>
<div id="div_ignlst">

    <div class="myhr"></div>

    <div class="column left">
    &nbsp;<img src="{$smarty.const._IMG_IGNORE_SM_}" alt="{$smarty.const._LBL_IGNORE_}" title="{$smarty.const._LBL_IGNORE_}"> {$lL.__list_of_entries_in_ignore_list__}.
    {if $setilist}
    &nbsp;[ <a href="javascript:;" onclick="mDialog('/Lock/addrule?projguid={$smarty.request.projguid}&kbguid={$smarty.request.kbguid}&mdlid={$smarty.request.mdlid}', '{$lL.__add_a_new_matching_rule_to_ignore_list__}.', 480, 640);" class="file">{$lL.__add_matching_rule__}</a> ]
    {/if}
    </div>
    <div class="column right">
    {$resultset|@count} {$lL.__row_s___}&nbsp;
    </div>
    <br clear="all">

    <form id="form_unlock" action="/Lock/relflag" method="POST" enctype="multipart/form-data">
    <input type="hidden" name="projguid" value="{$smarty.request.projguid}">
    <input type="hidden" name="kbguid" value="{$smarty.request.kbguid}">
    <input type="hidden" name="mdlid" value="{$smarty.request.mdlid}">
    <input type="hidden" name="flagtype" value="ignore">

        <table width="100%" align="center" class="list">
        <thead>
            <tr><th>{$lL.__object__}</th><th>{$lL.__username__}</th><th>{$lL.__set_in_list_since__}</th><th><span style='cursor:pointer;' title='{$smarty.const._LBL_CHKALL_}' onclick='setcheck("#form_unlock .objlst");setsubmitsts("#form_unlock .objlst", "#form_unlock button");'>&nbsp;{$smarty.const._LBL_CHKALL_}</span></th></tr>
        </thead>
        <tbody>
            {foreach from=$resultset key=k item=rec}
            <tr class='{cycle values="odd,even"}'>
            <td>&nbsp;<img src="../img/gx/objclass/{$gx_objcls[$rec.objcls].small}.png" title="{$gx_objcls[$rec.objcls].long}">&nbsp;{$rec.objnam}</td>
            <td>&nbsp;{$InProve_Smarty->guid2name('gxt_users', $rec.setuserguid)}</td>
            <td align="center">&nbsp;{$InProve_Smarty->ts2str($rec.setts)}</td>
            <td align="center">
            {if $setilist}
                {if $rec.b64}
                <span id="{$rec.b64|sha1}">
                <input class="objlst" type="checkbox" name='checked_objs[]' value='{$rec.b64}' onclick='setsubmitsts("#form_unlock .objlst", "#form_unlock button");'>
                </span>
                {/if}
            {else}
                <img class="tip" alt="listed" src="{$smarty.const._IMG_IGNORE_SM_}" title="{$lL.__object_s_ignore_list_status__}|'{$InProve_Smarty->guid2name('gxt_users', $rec.setuserguid)}' {$lL.__set_this_entry_so_matching_objects_are_ignored_on__} '{$InProve_Smarty->ts2str($rec.setts)}'">
            {/if}
            </td>
            </tr>
            {/foreach}
        </tbody>
        </table>

        <div class="myhr"></div>

        <div id="bottom_left" class="left">
            {include file='../skel/ttp.phtml' ttpLabel=__LNG__TTP__LNG__ secLabel=__LNG__second__LNG__ topLabel=__LNG__Top__LNG__}
        </div>
        <div  id="bottom_right" class="buttons right">
            <button class="button-circle" type="submit" name="submit_btn" value="{$smarty.const._LBL_SUBMIT_}" title="{$smarty.const._TITLE_SUBMIT_}">{$smarty.const._LBL_SUBMIT_}</button>
        </div>
    </form>    
    <br clear="all">

</div>