<script type="text/javascript">
$(document).ready(function(){

	$("#form_lock").ajaxForm({
		dataType:  'json',
        async: true,
		beforeSubmit: function() {
			$("#diffs").block({ message: '{$smarty.const._BAR_WAIT_}' });
		},
		success: function (r) {
            for ( var i in r.flaglist ) {
                if (r.flaglist[i] == "ok") {
                    $("#"+i).html("<img src='../img/icons/16/tick.png' alt='ok' title='"+r.flaglist[i]+"'>");
                } else {
                    $("#"+i).html("<img src='../img/icons/16/error.png' alt='err' title='"+r.flaglist[i]+"'>");
                }
            }

            if (r.flag.sts == "ok") {
                $("#div_srchres #bottom_left").html("<img src='../img/icons/32/tick.png' alt='ok' title='ok'> {$lL.__objects_were_successfully_locked_flagged__}");
                $("#diffs").unblock();
            } else {
                $("#div_srchres #bottom_left").html("<img src='../img/icons/32/error.png' alt='err' title='err'> {$lL.__some_objects_could_not_be_locked_flagged__}");
                $("#diffs").unblock();
            }

            setsubmitsts("#form_lock .objlst", "#form_lock button");
        },
        error: function (jqXHR) {
            handleXHRerror(jqXHR);
        }
	});

    filter_by_objsts();

    initializeButtons();

    setsubmitsts("#form_lock .objlst", "#form_lock button");

    $("#east_panel #project #div_srchres img.tip").cluetip({ splitTitle: "|" });

});

function filter_by_objsts() {

    $("#form_lock > table > tbody > tr").show();
    if (!$("#div_srchres #gen1chk").prop("checked")) { $("#form_lock > table > tbody > tr.gen1").hide(); }
    if (!$("#div_srchres #gen2chk").prop("checked")) { $("#form_lock > table > tbody > tr.gen2").hide(); }
    
    var $visibleRows = $("#form_lock > table > tbody > tr:visible").length;
    var $hiddenRows = $("#form_lock > table > tbody > tr:hidden").length;
    
    if ($hiddenRows) { $("#div_srchres #filterctrls").show(); }
    $("#div_srchres #resultrows").text($visibleRows);

}

function update_object(b64,src_path,objupdts,atlkbupdts) {

    $("#"+hex_sha1(b64)).html("<span class='msg_wait small'></span>");

    $.getJSON(
            "/Lock/updobj",
            { projguid:"{$smarty.request.projguid}", kbguid:"{$smarty.request.kbguid}", mdlid:"{$smarty.request.mdlid}", src_path:src_path, objupdts:objupdts, atlkbupdts:atlkbupdts },
            function (r, textStatus) {
                if (r.sts == "ok") {
                    $("#"+hex_sha1(b64)).html("<input class='objlst' type='checkbox' name='checked_objs[]' value='"+b64+"' onclick='setsubmitsts(\"#form_lock .objlst\", \"#form_lock button\");'>&nbsp;");
                } else {
                    $("#"+hex_sha1(b64)).html("{$InProve_Smarty->get_popup_link('auditlog','/audit-Info/render?audguid="+r.audguid+"','img|../img/icons/16/error.png','{$lL.__log_entry_details__}','800x600','')}");
                }
            }
    );
    
}
</script>
<div id="div_srchres">

    <div class="myhr"></div>

    <div class="column left">
        <img src="{$smarty.const._IMG_FLAG_SM_}" alt="{$smarty.const._LBL_FLAG_}" title="{$smarty.const._LBL_FLAG_}"> {$lL.__set_logic_flag_on_objects__}.
        <span id="filterctrls" style="display:none;">
        &nbsp;|&nbsp;
        <input type="checkbox" id="gen1chk" name="gen1chk" onchange="filter_by_objsts();"> <img class="tip" alt="gen1" src="../img/icons/16/lightning_green.png" title="{$lL.__visual_tag_information_objects_tagged_with_this_icon_were_detected_as_being_automatically_generated_by_some_genexus_process__eg__from_a_pattern_instance___}.">&nbsp;
        <input type="checkbox" id="gen2chk" name="gen2chk" onchange="filter_by_objsts();" checked> <img class="tip" alt="gen2" src="../img/icons/16/lightning_red.png" title="{$lL.__visual_tag_information_objects_tagged_with_this_icon_were_detected_as_being_automatically_generated_by_some_genexus_process__eg__from_a_pattern_instance__but_some_of_it_has_been_modified_by_a_user__}.">
        </span>
    </div>
    <div class="column right">
        <span id="resultrows"></span> {$lL.__row_s___}&nbsp;
    </div>
    <br clear="all">

    <form id="form_lock" action="/Lock/flag" method="POST" enctype="multipart/form-data">
    <input type="hidden" name="projguid" value="{$smarty.request.projguid}">
    <input type="hidden" name="kbguid" value="{$smarty.request.kbguid}">
    <input type="hidden" name="mdlid" value="{$smarty.request.mdlid}">
        <table width="100%" align="center" class="list">
        <thead>
            <tr><th>{$lL.__object__}</th><th>{$lL.__description__}</th><th>{$lL.__modified___server__} &darr;</th><th><span style='cursor:pointer;' title='{$smarty.const._TITLE_CHKALL_}' onclick='setcheck("#form_lock .objlst");setsubmitsts("#form_lock .objlst", "#form_lock button");'>&nbsp;{$smarty.const._LBL_CHKALL_}</span></th></tr>
        </thead>
        <tbody>
            {foreach $resultset as $k => $rec}
                <tr class='{cycle values="odd,even"} gen{$rec.generated} {$rec.updperiod}' style="{if $rec.generated==1}display:none;{/if}">
                <td>&nbsp;
                    {if $rec.objcls!=111}
                    <img src="../img/gx/objclass/{$gx_objcls[$rec.objcls].small}.png" title="{$gx_objcls[$rec.objcls].long}">
                    {else}
                    <img src="../img/icons/16/file.png" title="{$lL.__file__}">
                    {/if}
                    <a class="pointer" title="{$lL.__click_to_see_object_change_history__}" href="javascript:;" onclick="mDialog('/Promote/?projguid={$smarty.request.projguid}&src_path={$rec.src_path}', '{$lL.__object_change_history___promotion_status__}', 600, 900);">
                    &nbsp;{$rec.objnam}
                    </a>
                </td>
                <td>&nbsp;{$rec.objdsc}</td>
                <td align="center">
                    &nbsp;{$InProve_Smarty->ts2str($rec.objupdts)}
                    {if $rec.generated==1}
                    &nbsp;<img alt="gen1" src="../img/icons/16/lightning_green.png" title="{$lL.__automatically_generated__}.">
                    {else if $rec.generated==2}
                    &nbsp;<img alt="gen2" src="../img/icons/16/lightning_red.png" title="{$lL.__automatically_generated_but_modified__}.">
                    {/if}
                </td>
                <td align="center">
                    {if $rec.lock}
                        {if $rec.lock && $rec.lock.setuserguid != $InProve_Smarty->getSessVar("MyProfile.userdata.userguid")}
                        <img class="tip" alt="locked" src="{$smarty.const._IMG_LOCK_SM_}" title="{$lL.__object_s_lock_status__}|'{$InProve_Smarty->guid2name('gxt_users', $rec.lock.setuserguid)}' {$lL.__has_an_active_lock_on_this_object_since__} '{$InProve_Smarty->ts2str($rec.lock.setts)}'">
                        {else}
                        <img class="tip" alt="locked" src="{$smarty.const._IMG_LOCK_OWN_SM_}" title="{$lL.__object_s_lock_status__}|{$lL.__you_have_an_active_lock_on_this_object_since__} '{$InProve_Smarty->ts2str($rec.lock.setts)}'">
                        {/if}
                    {else}
                    {if $rec.b64}
                    <span id="{$rec.b64|sha1}">
                        {if $rec.COMP=="NEWER"}
                        <input class="objlst" type="checkbox" name='checked_objs[]' value='{$rec.b64}' onclick='setsubmitsts("#form_lock .objlst", "#form_lock button");'>&nbsp;
                        <img alt="neweratkb" src="../img/icons/16/development.png" title="{$lL.__your_version_is_newer__} ({$InProve_Smarty->ts2str($rec.atmykb.objupdts)}).">
                        {elseif $rec.COMP=="OLDER"}
                        <img alt="{$smarty.const._LBL_CATCHUP_}" src="{$smarty.const._IMG_CATCHUP_SM_}" title="{$lL.__your_version_is_outdated__}({$InProve_Smarty->ts2str($rec.atmykb.objupdts)}). [ {$lL.__click_to_update__} ]" class="file" onclick="update_object('{$rec.b64}','{$rec.src_path}','{$rec.objupdts}','{$rec.atmykb.objupdts}');">
                        {else}
                        <input class="objlst" type="checkbox" name='checked_objs[]' value='{$rec.b64}' onclick='setsubmitsts("#form_lock .objlst", "#form_lock button");'>&nbsp;
                        {/if}
                    </span>
                    {/if}
                    {/if}
                </td>
                </tr>
            {/foreach}
        </tbody>
        </table>

        <div class="myhr"></div>

        <div id="bottom_left" class="left">
            {include file='../skel/ttp.phtml' ttpLabel=__LNG__TTP__LNG__ secLabel=__LNG__second__LNG__ topLabel=__LNG__Top__LNG__}
        </div>
        <div  id="bottom_right" class="buttons right">
            <input type="radio" name='flagtype' value='lock' checked>&nbsp;<img src='{$smarty.const._IMG_LOCK_SM_}'> {$smarty.const._LBL_LOCK_}&nbsp;&nbsp;
            {if $setilist}
            <input type="radio" name='flagtype' value='ignore'>&nbsp;<img src='{$smarty.const._IMG_IGNORE_SM_}'> {$smarty.const._LBL_IGNORE_}&nbsp;&nbsp;
            {/if}
            <p>
            <div style="float:right;">
                <button class="button-circle" type="submit" name="submit_btn" value="{$smarty.const._LBL_SUBMIT_}" title="{$smarty.const._TITLE_SUBMIT_}">{$smarty.const._LBL_SUBMIT_}</button>
            </div>
        </div>
    </form>    
    <br clear="all">

</div>