<script type="text/javascript">
$(document).ready(function(){

	$("#form_checkin").ajaxForm({
		dataType:  'json',
        async: true,
		beforeSubmit: function() {
			$("#diffs").block({ message: '{$smarty.const._BAR_WAIT_}' });
            $("#div_checkin #bottom_left").html("");
		},
		success: function (r) {
            for ( var i in r.stage ) {
                if (r.stage[i] == "ok") {
                    $("#"+i).html("<img src='../img/icons/16/tick.png' alt='ok' title='"+r.stage[i]+"'>");
                } else {
                    $("#"+i).html("<img src='../img/icons/16/error.png' alt='err' title='"+r.stage[i]+"'>");
                }
            }

            if (r.commit.sts == "ok") {
                $("#div_checkin #bottom_left").html("<img src='../img/icons/32/tick.png' alt='ok' title='ok'> {$lL.__successful_commit__} "+r.commit.msg);
                if ($("#pushAcommit:checked").val()) {
                    pushAcommit(r.iframe_url)
                } else {
                    $("#diffs").unblock();
                }
            } else {
                $("#div_checkin #bottom_left").html("<img src='../img/icons/32/error.png' alt='err' title='err'> {$lL.__error_in_commit__} "+r.commit.msg);
                $("#diffs").unblock();
            }

            setsubmitsts("#form_checkin .objlst", "#form_checkin button");
        },
        error: function (jqXHR) {
            handleXHRerror(jqXHR);
        }
	});

    $("#pushAcommit").change(function() {
        if ($("#pushAcommit:checked").val()) {
            $("#impApush_holder").show("slow");
        } else {
            $("#impApush").prop("checked", false);
            $("#impApush_holder").hide("slow");
        }
    });

    setsubmitsts("#form_checkin .objlst", "#form_checkin button");

    $("#east_panel #project #div_checkin img.tip").cluetip({ splitTitle: "|" });

    filter_by_objsts();

    loadTickets();

});

function loadTickets() {
    $("#assoc_tickets").html('{$smarty.const._MSG_WAIT_SM_}');
    $("#assoc_tickets").load("/Chkin/tickets", { projguid:"{$smarty.request.projguid}" });
}

function pushAcommit(iframe_url) {
    jQuery.getJSON(
            "/Push/push",
            { projguid:"{$smarty.request.projguid}" },
            function (r, textStatus) {
                if (r.sts == "ok") {
                    $("#div_checkin #bottom_left").append("<p><img src='../img/icons/32/tick.png' alt='ok' title='ok'> {$lL.__successful_push__} "+r.msg);
                } else {
                    $("#div_checkin #bottom_left").append("<p><img src='../img/icons/32/error.png' alt='err' title='err'> {$lL.__pushing_data_error__} "+r.msg);
                }
                $("#diffs").unblock();
                if (r.sts == "ok" && $("#impApush:checked").val()) {
                    mDialog(iframe_url, '{$lL.__commits_data___promotion_status__}', 600, 900);
                }
            }
    );
}

function hardReset() {

    if (confirm("{$lL.__uncommitted_changes_will_be_lost__}.\n\n{$lL.__are_you_sure__} ?")) {

        $("#diffs").block({ message: '{$smarty.const._BAR_WAIT_}' });
        $("#div_checkin #bottom_left").html("");

        jQuery.getJSON(
                "/Chkin/reset",
                { projguid:'{$smarty.request.projguid}',kbguid:'{$smarty.request.kbguid}' },
                function (r, textStatus) {
                    if (r.sts == 0) {
                        $("#div_checkin #bottom_left").append("<p><img src='../img/icons/32/tick.png' alt='ok' title='ok'> {$lL.__repository_reset_successful__}");
                        setTimeout("$('#checkinlnk').click()",2500);
                    } else {
                        $("#div_checkin #bottom_left").append("<p><img src='../img/icons/32/error.png' alt='err' title='err'> {$lL.__repository_reset_error__} "+r.msg);
                        $("#diffs").unblock();
                    }

                }
        );
    }

}

function filter_by_objsts() {

    $("#form_checkin > table > tbody > tr").show();
    if (!$("#div_checkin #gen1chk").prop("checked")) { $("#form_checkin > table > tbody > tr.gen1").hide(); }
    if (!$("#div_checkin #gen2chk").prop("checked")) { $("#form_checkin > table > tbody > tr.gen2").hide(); }
    if (!$("#div_checkin #olderchk").prop("checked")) { $("#form_checkin > table > tbody > tr.OLDER").hide(); }
    if ($("#periods_filter").val()) {
        $("#form_checkin > table > tbody > tr").not("."+$("#periods_filter").val()).hide();
    }

    var $visibleRows = $('#form_checkin > table > tbody > tr:visible').length;
    var $hiddenRows = $('#form_checkin > table > tbody > tr:hidden').length;
    var $newRows = $("#form_checkin > table > tbody > tr:visible .lst2add").length;
    var $diffRows = $("#form_checkin > table > tbody > tr:visible .lst2lck").length;

    if ($newRows) { $("#div_checkin #click2add").show(); }
    if ($diffRows) { $("#div_checkin #click2lck").show(); }
    {if $kbdata.kbclass>=7500}
    if ($hiddenRows) { $("#div_checkin #filterctrls").show(); }
    {/if}
    $("#div_checkin #resultrows").text($visibleRows);

}

function go_for_lock(type) {

    var $str4srch = "";

    $("#form_checkin > table > tbody > tr:visible ."+type).each(function () {
        $str4srch = $str4srch + $(this).text() + ",";
    });

    if ($str4srch!="") {
        if (type=="lst2add") {
            $str4srch = $str4srch + " [Add_New]";
        } else {
            $str4srch = $str4srch + " [Lock]";
        }
        $("#qrystr").val($str4srch);
        $("#gobtn").click();
    } else {
        alert("{$lL.__could_not_get_objects_list__}.");
    }

}
</script>
<div id="div_checkin">

    {if $smarty.request.mergebefore}
    <div class="ui-corner-all ui-state-active" style="padding:1em;">
        <img src="{$smarty.const._IMG_CATCHUP_SM_}" alt="{$smarty.const._LBL_CATCHUP_}" title="{$smarty.const._LBL_CATCHUP_}"> {$lL.__merge_from_main_codeline_performed__}
        <p>{$lL.__status__} : {if $merge_FromGxTendCL.sts==0}<img src="../img/icons/16/tick.png" alt="ok" title="ok"> {$lL.__success__} {else} <img src="../img/icons/16/error.png" alt="err" title="err"> {$lL.__error__}{/if}</p>
        <p>{$merge_FromGxTendCL.out}</p>
    </div>
    {/if}

    <div class="myhr"></div>
    <div class="column left" style="width:50%;">
        {if $have_locks && !$smarty.request.forcecompare}
        {$lL.__list_below_is__strong_restricted__strong__to_your_current_locked_set__}, <a href="javascript:;" onclick='$("#qrystr").val("");$("#diffs").show("slow", show_diffs("checkin", "{$smarty.request.projguid}", "{$smarty.request.kbguid}", 1));'>{$lL.__click_here__}</a> {$lL.__for_full_list_of_differences__}.&nbsp;
        {elseif $have_locks && $smarty.request.forcecompare}
        {$lL.__list_below_contains__strong_full_set__strong__of_differences__}, <a href="javascript:;" onclick='$("#qrystr").val("");$("#diffs").show("slow", show_diffs("checkin", "{$smarty.request.projguid}", "{$smarty.request.kbguid}", 0));'>{$lL.__click_here__}</a> {$lL.__to_restrict_it_to_your_current_locked_set__}.&nbsp;
        {else}
        {$lL.__list_below_contains__} <strong>{$lL.__full_set__}</strong> {$lL.__of_differences__you_have_no_active_locks__}.&nbsp;
        {/if}
    </div>
    <div class="column right">
        {if $kbdata.kbclass>=7500}
        <span id="click2lck" class="file" style="display:none;" onclick='go_for_lock("lst2lck");'><img alt="info" src="../img/icons/16/info.png" title="{$lL.__search___lock__}"> {$lL.__click_to_search___lock_all_modified_objects__}</span>
        <br>
        <span id="click2add" class="file" style="display:none;" onclick='go_for_lock("lst2add");'><img alt="new" src="../img/icons/16/new.png" title="{$lL.__search___lock__}"> {$lL.__click_to_add___lock_all_new_objects__}</span>
        {/if}
    </div>
    <br clear="all">
    <div class="myhr"></div>

    {if !is_array($local_changes)}
        {$InProve_Smarty->msg("ui-icon-alert", $local_changes)}
    {else}

        <div class="column left">
            <img src="{$smarty.const._IMG_COMMIT_SM_}" alt="{$smarty.const._LBL_COMMIT_}" title="{$smarty.const._LBL_COMMIT_}"> {$lL.__commit_changes_into__local_history_repo___}
            &nbsp;|&nbsp;{$periods_filter}
            <span id="filterctrls" style="display:none;">
            &nbsp;|&nbsp;
            <input type="checkbox" id="gen1chk" name="gen1chk" onchange="filter_by_objsts();"> <img class="tip" alt="gen1" src="../img/icons/16/lightning_green.png" title="{$lL.__visual_tag_information_objects_tagged_with_this_icon_were_detected_as_being_automatically_generated_by_some_genexus_process__eg__from_a_pattern_instance___}.">&nbsp;
            <input type="checkbox" id="gen2chk" name="gen2chk" onchange="filter_by_objsts();" checked> <img class="tip" alt="gen2" src="../img/icons/16/lightning_red.png" title="{$lL.__visual_tag_information_objects_tagged_with_this_icon_were_detected_as_being_automatically_generated_by_some_genexus_process__eg__from_a_pattern_instance__but_some_of_it_has_been_modified_by_a_user__}.">&nbsp;
            <input type="checkbox" id="olderchk" name="olderchk" onchange="filter_by_objsts();"> <img class="tip" alt="older" src="../img/icons/16/warning.png" title="{$lL.__visual_tag_information_objects_tagged_with_this_icon_were_detected_as_being_older_than_its_target__}.">
            </span>
        </div>
        <div class="column right">
            <span id="resultrows"></span> row(s)
        </div>
        <br clear="all">

        <form id="form_checkin" action="chkin/chkin" method="POST" enctype="multipart/form-data">
        <input type="hidden" name="projguid" value="{$smarty.request.projguid}">
        <input type="hidden" name="kbguid" value="{$smarty.request.kbguid}">
        <input type="hidden" name="mdlid" value="{$smarty.request.mdlid}">
            <table width="100%" align="center" class="list">
            <thead>
                <tr><th>{$lL.__object__}</th><th>{if $kbdata.kbclass<7500}Folder{else}Description{/if}</th><th>{$lL.__modified___local__} &darr;</th><th><span style='cursor:pointer;' title='{$smarty.const._TITLE_CHKALL_}' onclick='setcheck("#form_checkin .objlst");setsubmitsts("#form_checkin .objlst", "#form_checkin button");'>&nbsp;{$smarty.const._LBL_CHKALL_}</span></th></tr>
            </thead>
            <tbody>
                {foreach $local_changes as $k => $rec}
                <tr class='{cycle values="odd,even"} gen{$rec.gxinfo.generated} {$rec.gxinfo.COMP} {$rec.gxinfo.updperiod}' style="{if $rec.gxinfo.generated==1 || $rec.gxinfo.COMP=='OLDER'}display:none;{/if}">
                <td>&nbsp;
                    {if $rec.gxinfo.objcls!=111}
                    <img src="../img/gx/objclass/{$gx_objcls[$rec.gxinfo.objcls].small}.png" title="{$gx_objcls[$rec.gxinfo.objcls].long}">
                    &nbsp;{$rec.gxinfo.objnam}
                    {else}
                    {$mimeicon='./img/icons/16/mimetypes/'|cat:pathinfo($rec.gxinfo.objnam,$smarty.const.PATHINFO_EXTENSION)|cat:'.png'}
                    <img src="{if file_exists($mimeicon)}{$mimeicon}{else}./img/icons/16/mimetypes/blank.png{/if}" title="File">
                    &nbsp;{$rec.gxinfo.objnam|basename}
                    {/if}
                </td>
                <td>
                    &nbsp;{$rec.gxinfo.objdsc|utf8_encode}
                    {if $rec.gxinfo.lock && $rec.gxinfo.lock.setuserguid == $InProve_Smarty->getSessVar("MyProfile.userdata.userguid")}
                    &nbsp;<img class="tip" alt="locked" src="{$smarty.const._IMG_LOCK_OWN_SM_}" title="{$lL.__object_s_lock_status_you_have_an_active_lock_on_this_object_since__} '{$InProve_Smarty->ts2str($rec.gxinfo.lock.setts)}'">
                    {/if}
                </td>
                <td align="center">
                    &nbsp;{$InProve_Smarty->ts2str($rec.gxinfo.objupdts)}
                    {if $rec.gxinfo.COMP=="NEW" && $rec.gxinfo.COMPREF!="DELETED_FROM_GXKB"}
                    &nbsp;<img alt="new" src="../img/icons/16/new.png" title="{$lL.__does_not_exist_in_target__}.">
                    {elseif $rec.gxinfo.COMP=="NEW" && $rec.gxinfo.COMPREF=="DELETED_FROM_GXKB"}
                    &nbsp;<img alt="del" src="../img/icons/16/cleanup.png" title="{$lL.__object_detected_as_deleted_in_source__}.">
                    {elseif $rec.gxinfo.COMP=="OLDER"}
                    &nbsp;<img alt="older" src="../img/icons/16/warning.png" title="{$lL.__target_modified_on__} {$InProve_Smarty->ts2str($rec.gxinfo.COMPREF)}">
                    {/if}
                    {if $rec.gxinfo.generated==1}
                    &nbsp;<img alt="gen1" src="../img/icons/16/lightning_green.png" title="{$lL.__automatically_generated__}.">
                    {else if $rec.gxinfo.generated==2}
                    &nbsp;<img alt="gen2" src="../img/icons/16/lightning_red.png" title="{$lL.__automatically_generated_but_modified__}.">
                    {/if}
                </td>
                <td align="center">
                    {if $rec.gxinfo.lock && $rec.gxinfo.lock.setuserguid != $InProve_Smarty->getSessVar("MyProfile.userdata.userguid")}
                        <img class="tip" alt="locked" src="{$smarty.const._IMG_LOCK_SM_}" title="{$lL.__object_s_lock_status__}|'{$InProve_Smarty->guid2name('gxt_users', $rec.gxinfo.lock.setuserguid)}' {$lL.__has_an_active_lock_on_this_object_since__} '{$InProve_Smarty->ts2str($rec.gxinfo.lock.setts)}'">
                    {else}
                        {if $rec.b64}
                        <span id="{$rec.b64|sha1}">
                            {if !$rec.gxinfo.lock && $kbdata.kbclass>=7500}
                                {if $rec.gxinfo.COMP=="NEW" && $rec.gxinfo.COMPREF!="DELETED_FROM_GXKB"}
                                    <img alt="new" src="../img/icons/16/new.png" title="{$lL.__does_not_exist_in_target__}.">
                                    {if $rec.gxinfo.objcls!=111}
                                    <span class="lst2add" style="display:none;">{$gx_objcls[$rec.gxinfo.objcls].small}:{$rec.gxinfo.objnam}</span>
                                    {else}
                                    <span class="lst2add" style="display:none;">{str_ireplace($smarty.request.kbguid|cat:'/','',$gx_objcls[$rec.gxinfo.objcls].small|cat:':'|cat:$rec.gxinfo.objnam)}</span>
                                    {/if}
                                {else}
                                    <img alt="info" src="../img/icons/16/info.png" title="{$lL.__no_active_lock_on_this_object__}.">
                                    {if $rec.gxinfo.objcls!=111}
                                    <span class="lst2lck" style="display:none;">{$gx_objcls[$rec.gxinfo.objcls].small}:{$rec.gxinfo.objnam}</span>
                                    {else}
                                    <span class="lst2lck" style="display:none;">{str_ireplace($smarty.request.kbguid|cat:'/','',$gx_objcls[$rec.gxinfo.objcls].small|cat:':'|cat:$rec.gxinfo.objnam)}</span>
                                    {/if}
                                {/if}
                            {else}
                                {if $rec.gxinfo.chkin}
                                <img src="{$smarty.const._IMG_CLOCK_SM_}" alt="{$lL.__pending__}" title="{$lL.__consolidation_pending__}">
                                {else}
                                <input class="objlst" type=checkbox name='checked_objs[]' value='{$rec.b64}' onclick='setsubmitsts("#form_checkin .objlst", "#form_checkin button");'>
                                {/if}
                            {/if}
                        </span>
                        {/if}
                    {/if}
                </td>
                </tr>
                {/foreach}
            </tbody>
            </table>

            <div class="myhr"></div>

            <div id="addcomm" class="newitm" style="padding:10px 0;">
                <img style="float:left; margin:0 0 5px;" width="48" height="48" src="/Ajax/getimg?userguid={$InProve_Smarty->getSessVar('MyProfile.userdata.userguid')}&v={$smarty.now}" alt="{$lL.__my_image__}">
                <div style="margin-left:60px;">
                    <div style="float:left;">
                        <strong>{$lL.__commenting_on_your_commits_is_usually_a_good_idea__}...</strong>
                        <p><textarea rows="10" cols="90" id="comment" name="comment"></textarea></p>
                    </div>
                    <div style="float:right;">
                        <strong>{$lL.__tickets_you_can_associate_this_commit_to__}...</strong>
                        <div id="assoc_tickets">
                        </div>
                    <div class="myhr"></div>
                    {if $InProve_Smarty->getSessVar("LoginStatus.server.status")}
                        {if $project.remo_repo_stats.ava == "open"}
                            {if $project.repo_stats.ava == "open"}
                                <img src='{$smarty.const._IMG_PUSH_SM_}' alt='Push' title='{$lL.__select_to_push_after_commit__}.'>
                                &nbsp;{$lL.__push_after_commit__}
                                &nbsp;<input type="checkbox" id="pushAcommit" value="1" {if $commit_PandI}checked{/if}>

                                <div id="impApush_holder" style="{if !$commit_PandI}display:none;{/if}">
                                {if $iframe_url}
                                &nbsp;&nbsp;&nbsp;&nbsp;&raquo;&nbsp;<img src='{$smarty.const._IMG_PROMOTE_SM_}' alt='Push' title='{$lL.__select_to_open_promotion_dialog_after_successful_push__}.'>
                                &nbsp;{$lL.__promote_after_push__}
                                &nbsp;<input type="checkbox" id="impApush" value="1" {if $commit_PandI==2}checked{/if}>
                                {/if}
                                </div>

                            {/if}
                        {else}
                            &nbsp;{$InProve_Smarty->msg("ui-icon-info","{$lL.__push_after_commit_not_available_as_remote_repository_is_not_open__}")}
                        {/if}
                    {else}
                        &nbsp;{$InProve_Smarty->msg("ui-icon-info","{$lL.__push_after_commit_not_available_as_server_is_not_online__}")}
                    {/if}
                    </div>
                </div>
            </div>

            <br clear="all">
            <div class="myhr"></div>

            <div id="bottom_left" class="left">
                {include file='../skel/ttp.phtml' ttpLabel={$lL.__ttp__} secLabel={$lL.__second__} topLabel={$lL.__top__}}
            </div>
            <div  id="bottom_right" class="buttons right">
                {if $kbdata.kbclass<7500}
                    <button type='button' id='reset_btn' name='reset_btn' value='{$smarty.const._LBL_RESET_}"' title='{$lL.__click_to_reset_all_non_commited_changes__}"' onclick="hardReset();">
                    <img src='{$smarty.const._IMG_RESET_SM_}'> {$smarty.const._LBL_RESET_}
                    </button>
                {/if}
                {$smarty.const._FORM_BTN_COMMIT_}
            </div>

        </form>
        <br clear="all">
    {/if}
</div>