<div id="dnqueue">
    <h2>__LNG__Server Changes__LNG__ (<a href="javascript:;" onclick="dataSync('down');">&darr; __LNG__Sync__LNG__</a>)</h2>
    <table width="100%" align="center" class="list">
    <thead>
        <tr><th>__LNG__Table__LNG__</th><th>__LNG__Size__LNG__</th><th>__LNG__Last Updated__LNG__</th></tr>
    </thead>
    <tbody>
        {foreach from=$dnqueue.tables key=k item=rec}
        {if $rec.dnsync_sts == "outdated"}
        <tr class='{cycle values="odd,even"}'>
            <td>{$rec.TABLE_NAME}</td>
            <td align="center">{$InProve_Smarty->bytes2str($rec.DATA_LENGTH)}</td>
            <td align="center">{$InProve_Smarty->ts2str($rec.UPDATE_TIMESTAMP)}</td>
        </tr>
        {/if}
        {/foreach}
    </tbody>
    <tfoot>
        <tr><td colspan="3" style="font-size:.75em;">__LNG__Last Dn Sync Datetime__LNG__ {$InProve_Smarty->ts2str($dnqueue.last_dnsync_ts)}&nbsp;</td></tr>
    </tfoot>
    </table>
</div>