<div id="dnqueue">
    <h2>Server Changes (<a href="javascript:;" onclick="dataSync('down');">↓ Sync</a>)</h2>
    <table width="100%" align="center" class="list">
    <thead>
        <tr><th>Table</th><th>Size</th><th>Last Updated</th></tr>
    </thead>
    <tbody>
        {foreach from=$dnqueue.tables key=k item=rec}
        {if $rec.dnsync_sts == "outdated"}
        <tr class='{cycle values="odd,even"}'>
            <td>{$rec.TABLE_NAME}</td>
            <td align="center">{$InProve_Smarty->bytes2str($rec.DATA_LENGTH)}</td>
            <td align="center">{$InProve_Smarty->ts2str($rec.UPDATE_TIMESTAMP)}</td>
        </tr>
        {/if}
        {/foreach}
    </tbody>
    <tfoot>
        <tr><td colspan="3" style="font-size:.75em;">Last Dn Sync Datetime {$InProve_Smarty->ts2str($dnqueue.last_dnsync_ts)}&nbsp;</td></tr>
    </tfoot>
    </table>
</div>