<div id="upqueue">
    <h2>__LNG__Queued__LNG__ (<a href="javascript:;" onclick="dataSync('up');">&uarr; __LNG__Sync__LNG__</a>)</h2>
    <table width="100%" align="center" class="list">
    <thead>
        <tr><th>Id</th><th>__LNG__Description__LNG__</th><th>__LNG__Performed__LNG__ &darr;</th><th>__LNG__Ops__LNG__</th></tr>
    </thead>
    <tbody>
        {foreach from=$upqueue.entries key=k item=rec}
        <tr id="row_{$rec.sqlid}" class='{cycle values="odd,even"}'>
            <td><span class="pointer" onclick="$('#nfo_{$rec.sqlid}').toggle();">{$rec.sqlid}</span></td>
            <td align="center">{$rec.sqldesc}</td>
            <td align="center">{$InProve_Smarty->ts2str($rec.setts)}</td>
            <td align="center">
            <span style="cursor:pointer;" onclick="oponEntry('del',{$rec.sqlid});"><img src="{$smarty.const._IMG_REMOVE_SM_}" title="__LNG__Delete__LNG__"></span>
            </td>
        </tr>
        <tr id="nfo_{$rec.sqlid}" style="display:none;">
            <td colspan="4">
                &nbsp;{$rec.sqlcomp.sql}<br>
                {foreach from=$rec.sqlcomp.place_holders_values key=i item=p}
                &nbsp;? = {if is_null($p)}<span class="red">null</span>{else}{$p}{/if}<br>
                {/foreach}
            </td>
        </tr>
        {/foreach}
    </tbody>
    <tfoot>
        <tr><td colspan="4" style="font-size:.75em;">__LNG__Last Up Sync Datetime__LNG__ {$InProve_Smarty->ts2str($upqueue.last_upsync_ts)}&nbsp;</td></tr>
    </tfoot>
    </table>
</div>