<?xml version='1.0' encoding='UTF-8' ?>
<rss version='2.0'>
<channel>
    <title>GxTend's To-Do List Named : {$todoData.todoabv}</title>
    <description>Related Milestone : {$mistData.mistabv} due to {$Accendo_Smarty->ts2str($mistData.mistduets, "date")}</description>
    <link>http://gxtend.accendo-it.com</link>
    <lastBuildDate>{$smarty.now|date_format:$smarty.const.DATE_RSS}</lastBuildDate>
    <pubDate>{$smarty.now|date_format:$smarty.const.DATE_RSS}</pubDate>
    <copyright>&copy; 2005-{$smarty.now|date_format:'%Y'} Accendo</copyright>
    <image>
        <title>GxTend - Rss Feed</title>
        <url>../img/gxtend_logo_{$smarty.const.__LAYER_ROLE__}.png</url>
        <link>http://gxtend.accendo-it.com</link>
    </image>

    {foreach from=$ticketsData key=tk item=ticket}
    <item>
        <author><![CDATA[{$ticket.ttsauthor}]]></author>
        <pubDate>{$ticket.ttspubts|date_format:$smarty.const.DATE_RSS}</pubDate>
        <title><![CDATA[{$ticket.ttsabv}]]></title>
        <description>
            <![CDATA[
            {$ticket.ttstxt}
            <p align="right">
                Status : <font color="{if !$ticket.open}gray{else}green{/if}">{$ticket.ttsstsdsc}</font><br>
                <a href="/Rss/?ttsguid={$ticket.ttsguid}&token={$Accendo_Smarty->userToken()}" target="_blank">RSS Feed</a>
            </p>
            ]]>
        </description>
    </item>
    {/foreach}
</channel>
</rss>
