<img src="{$smarty.const._IMG_FOLDER_OPEN_SM_}" alt=""> <span style="color:green;">{$folder_relative_name}</span>
<table width="100%" align="center" class="list">
<thead>
    <tr><th>__LNG__Name__LNG__</th><th>__LNG__Description__LNG__</th><th>__LNG__Date Modified__LNG__</th></tr>
</thead>
<tbody>
    {foreach from=$fld_cont key=k item=rec}
        <tr>
        <td><img src="../img/gx/objclass/{$gx_objcls[$rec.objcls].small}.png" title="{$gx_objcls[$rec.objcls].long}">&nbsp;{$rec.objnam}</td>
        <td>{$rec.objdsc|utf8_encode}</td>
        <td align="center">{$InProve_Smarty->ts2str($rec.objupdts)}</td>
        </tr>
    {/foreach}
</tbody>
</table>