<script type="text/javascript">
$(document).ready(function(){

    $("#tabber_repnfo").tabs();

	$("#rinfo form").ajaxForm({
		dataType:  'json',
		beforeSubmit: function() {
            if (confirm("{$lL.__please_confirm_submission_of_operation__} ?")) {
                $("#rinfo").block({ message: '{$smarty.const._BAR_WAIT_}' });
            } else {
                return false;
            }
		},
		success: function (r) {
            showlogmsg();
            if (!r.err) {
                mDialog('/Browse-Repos/rinfo?repopath={$smarty.request.repopath}&projguid={$smarty.request.projguid}', '{$lL.__repository_detailed_stats__}', 480, 640);
            } else {
                $("#rinfo").unblock();
            }
        },
        error: function (jqXHR) {
            handleXHRerror(jqXHR);
        }
	});

});

function goChgPrm(mode,k,v) {
    
    $("#rinfo form").hide();
    $("#form_chgprm").show();
    if (mode=="edt") {
        $("#form_chgprm #prmkey").prop("readonly","readonly").val(k);
        $("#form_chgprm #prmval").val(v);
        $("#form_chgprm #prmval").focus();
    } else {
        $("#form_chgprm #prmkey").prop("readonly","").val("");
        $("#form_chgprm #prmval").val("");
        $("#form_chgprm #prmkey").focus();
    }    
    $("#GenericDialog").animate({ scrollTop: $("#GenericDialog").height() }, 1000);

}
</script>

<div id="rinfo" class="profile">
    <div id="tabber_repnfo">
        <ul>
            <li><a href="#tab-1">{$lL.__repository__}</a></li>
            <li><a href="#tab-2">{$lL.__codelines__}</a></li>
            <li><a href="/Fsys-Brw/?data2browse={$meta2browse}"><span>{$lL.__meta_files__}</span></a></li>
        </ul>

        <div id="tab-1">
            <table align="center" width="100%" class="list-horizontal">
            <tr>
                <td align="left" class="header first" scope="row">
                    {$lL.__path__}
                </td>
                <td align="left" class="first">
                    {$InProve_Smarty->cutstr($repo_stats.path,0,50)}
                </td>
            </tr>
            <tr>
                <td align="left" class="header" scope="row">
                    {$lL.__size__}
                </td>
                <td align="left">
                    {$InProve_Smarty->bytes2str($repo_stats.fsysSize)}
                    {if $repo_stats.fsysSize}                    
                    &nbsp;<span onclick='$("#rinfo form, .config_entries").hide();$("#form_cleanup").show();' class='pointer'><img src="{$smarty.const._IMG_CLEANUP_SM_}" title="{$lL.__cleanup_repository__}."></span>
                    {if in_array($smarty.const.__LAYER_ROLE__,array("Server","Website"))}
                    &nbsp;<span onclick='$("#rinfo form, .config_entries").hide();$("#form_updsrvnfo").show();' class='pointer'><img src="{$smarty.const._IMG_UPDSRVNFO_SM_}" title="{$lL.__update_repository_metadata_info__}."></span>
                    {/if}
                    {if $smarty.const.__LAYER_ROLE__ == "Client"}
                    &nbsp;<span onclick='$("#rinfo form, .config_entries").hide();$("#form_mergerpcl").show();' class='pointer'><img src="{$smarty.const._IMG_JOIN_SM_}" title="{$lL.__merge_remote_and_local_personal_code_lines__}."></span>
                    &nbsp;<span onclick='$("#rinfo form, .config_entries").hide();$("#form_setbaseline").show();' class='pointer'><img src="{$smarty.const._IMG_MERGE_SM_}" title="{$lL.__rebase_your_personal_code_line__}."></span>
                    {/if}
                    {/if}
                </td>
            </tr>
            {if $smarty.const.__LAYER_ROLE__ == "Client"}
            <tr>
                <td align="left" class="header" scope="row">
                    {$lL.__working_tree_size__}
                </td>
                <td align="left">
                    {$InProve_Smarty->bytes2str($repo_stats.fsysSizeOfWrkTree)}
                </td>
            </tr>
            {/if}
            <tr>
                <td align="left" class="header" scope="row">
                    {$lL.__number_of_codelines__}
                </td>
                <td align="left">
                    {$repo_stats.branchInfo|@count}
                </td>
            </tr>
            <tr>
                <td align="left" class="header" scope="row">
                    {$lL.__current_codeline__}
                </td>
                <td align="left">
                    {$repo_stats.head}
                </td>
            </tr>
            <tr>
                <td align="left" class="header" scope="row" colspan="2">
                    <span style="cursor:pointer;float:right;font-size:.8em;" onclick="$('#rinfo form').hide();$('.config_entries').toggle();">{$lL.__click_to_view_edit_repository_config_entries__}</span>
                </td>
            </tr>
            {foreach $repo_stats.config as $k => $v}
            <tr class="config_entries" style="display:none;" onmouseover="$('#{$k|sha1}').show();" onmouseout="$('#{$k|sha1}').hide();">
                <td align="left">
                    <strong>{$k}</strong>
                </td>
                <td align="left">
                    {$InProve_Smarty->cutstr($v,0,50)}
                    <span id="{$k|sha1}" style="display:none;" onclick='goChgPrm("edt","{$k}","{$v}");' class='pointer right'><img src="{$smarty.const._IMG_EDIT_SM_}" title="{$lL.__edit_entry__}."></span>
                </td>
            </tr>
            {/foreach}
            <tr class="config_entries" style="display:none;">
                <td align="left" class="header" scope="row" colspan="2">
                    <span style="cursor:pointer;float:right;font-size:.8em;" onclick='goChgPrm("add","","");'>{$lL.__add_entry__}</span>
                </td>
            </tr>
            </table>
            <div>
                <form id="form_cleanup" action="/Browse-Repos/ropts" method="POST" enctype="multipart/form-data" style="display:none;">
                <input type="hidden" name="projguid" value="{$projguid}">
                <input type="hidden" name="opt" value="cleanup">
                    <p>
                        {$InProve_Smarty->msg("ui-icon-info","{$lL.__aggressive_cleanup_might_take_to_complete__}.")}
                    </p>                
                    <div id="bottom_right" class="buttons right">
                        {$smarty.const._FORM_BTN_SUBMIT_}
                        &nbsp;{$lL.__or__}&nbsp;
                        <a href="javascript:;" onclick='$("#rinfo form").hide();'>{$lL.__cancel__}</a>&nbsp;
                    </div>
                </form>
                {if in_array($smarty.const.__LAYER_ROLE__,array("Server","Website"))}
                <form id="form_updsrvnfo" action="/Browse-Repos/ropts" method="POST" enctype="multipart/form-data" style="display:none;">
                <input type="hidden" name="projguid" value="{$projguid}">
                <input type="hidden" name="opt" value="updsrvnfo">
                    <p>
                        {$InProve_Smarty->msg("ui-icon-info","{$lL.__update_server_s_repository_metadata_info_might__}.")}
                    </p>                
                    <div id="bottom_right" class="buttons right">
                        {$smarty.const._FORM_BTN_SUBMIT_}
                        &nbsp;{$lL.__or__}&nbsp;
                        <a href="javascript:;" onclick='$("#rinfo form").hide();'>{$lL.__cancel__}</a>&nbsp;
                    </div>
                </form>
                {else}
                <form id="form_mergerpcl" action="/Browse-Repos/ropts" method="POST" enctype="multipart/form-data" style="display:none;">
                <input type="hidden" name="projguid" value="{$projguid}">
                <input type="hidden" name="opt" value="mergerpcl">
                    <p>
                        {$InProve_Smarty->msg("ui-icon-info","{$lL.__merge_local_and_remote_pcl_will_align_both__}.")}
                    </p>                
                    <div id="bottom_right" class="buttons right">
                        {$smarty.const._FORM_BTN_SUBMIT_}
                        &nbsp;{$lL.__or__}&nbsp;
                        <a href="javascript:;" onclick='$("#rinfo form").hide();'>{$lL.__cancel__}</a>&nbsp;
                    </div>
                </form>
                <form id="form_setbaseline" action="/Browse-Repos/setbaseline" method="POST" enctype="multipart/form-data" style="display:none;">
                <input type="hidden" name="projguid" value="{$projguid}">
                    {if $repo_stats.personalBranch == "not found"}
                        {$InProve_Smarty->msg("ui-icon-alert","{$lL.__personal_baseline_code_not_found__}")}
                        <p>
                        {$lL.__set_it_using___start_point__as_starting_point__}.
                        </p>
                    {else}
                        {$InProve_Smarty->msg("ui-icon-info","{$lL.__by_re_basing_your_pcl_you_will_loose_any_local__}.")}
                        <p>
                         {$lL.__re_base_using__} {$start_point} {$lL.__as_starting_point__}.
                        </p>
                    {/if}
                    <div id="bottom_right" class="buttons right">
                        {$smarty.const._FORM_BTN_SUBMIT_}
                        &nbsp;{$lL.__or__}&nbsp;
                        <a href="javascript:;" onclick='$("#rinfo form").hide();'>{$lL.__cancel__}</a>&nbsp;
                    </div>
                </form>
                {/if}
                <form id="form_chgprm" action="/Browse-Repos/ropts" method="POST" enctype="multipart/form-data" style="display:none;">
                <input type="hidden" name="projguid" value="{$projguid}">
                <input type="hidden" name="opt" value="chgprm">
                    <p>
                        {$InProve_Smarty->msg("ui-icon-info","{$lL.__add_edit_config_property__}")}
                    </p>
                    <div>
                    <label for="key"><strong>{$lL.__key__}</strong></label>
                    <input type="input" id="prmkey" name="prmkey" size="30" value="">
                    </div>
                    <div>
                    <label for="val"><strong>{$lL.__value__}</strong></label>
                    <input type="input" id="prmval" name="prmval" size="75" value="" style="width:80%;">
                    </div>
                    <div id="bottom_right" class="buttons right">
                        {$smarty.const._FORM_BTN_SUBMIT_}
                        &nbsp;{$lL.__or__}&nbsp;
                        <a href="javascript:;" onclick='$("#rinfo form").hide();'>{$lL.__cancel__}</a>&nbsp;
                    </div>
                </form>                
            </div>
            <br style="clear:both;">
        </div>

        <div id="tab-2">
            <fieldset><legend>{$lL.__locals__}</legend>
            {foreach from=$repo_stats.branchInfo key=k item=rec}
                {if $rec.type == "local"}
                    <p>
                    '<b>{$rec.name}</b>' {$lL.__has__} <b>{$rec.commits}</b> commits.
                    <br>{$lL.__last_performed_by__} '<b>{$rec.commitsdata[$rec.lastcommit].commiter}</b>' {$lL.__on__} '<b>{$InProve_Smarty->ts2str($rec.commitsdata[$rec.lastcommit].commiterTs)}</b>' {$lL.__with__} <b>{$rec.commitsdata[$rec.lastcommit].changes|@count}</b> {$lL.__entries__}.
                    </p>
                {/if}
            {/foreach}
            </fieldset>
            <br style="clear:both;">
            <fieldset><legend>{$lL.__remotes__}</legend>
            {foreach from=$repo_stats.branchInfo key=k item=rec}
                {if $rec.type == "remote"}
                    <p>
                    '<b>{$rec.name}</b>' {$lL.__has__} <b>{$rec.commits}</b> commits.
                    <br>{$lL.__last_performed_by__} '<b>{$rec.commitsdata[$rec.lastcommit].commiter}</b>' {$lL.__on__} '<b>{$InProve_Smarty->ts2str($rec.commitsdata[$rec.lastcommit].commiterTs)}</b>' with <b>{$rec.commitsdata[$rec.lastcommit].changes|@count}</b> {$lL.__entries__}.
                    </p>
                {/if}
            {/foreach}
            </fieldset>
        </div>
    </div>
</div>