__LNG__History of__LNG__ <span class="green">{$file_relative_name}</span>
<table width="100%" align="center" class="list">
<thead>
    <tr><th>__LNG__Commited__LNG__</th><th>__LNG__Mode__LNG__</th><th>__LNG__Vers. GUID__LNG__</th></tr>
</thead>
<tbody>
    {foreach from=$file_vers key=k item=rec}
        <tr>
        <td align="center">{$InProve_Smarty->ts2str($rec.timestamp)}</td>
        <td align="center">{$rec.status}</td>
        <td align="center">
            {$InProve_Smarty->cutstr($rec.dst_hash,0,$smarty.const._GUID_LEN_)}
            &nbsp;<a href="/Http/gitfile?filename={$rec.b64filename}&filehash={$rec.dst_hash}"><img src="{$smarty.const._IMG_DOWNLOAD_SM_}" title="{$smarty.const._LBL_DOWNLOAD_}"></a>
        </td>
        </tr>
    {/foreach}
</tbody>
</table>