<script type="text/javascript">
$(document).ready(function(){
    
    {if $smarty.const.__LAYER_ROLE__ == "Server"}
    getVersionStatus();
    $("#servicessts").load("/Services/?match=gxtend");
    {/if}

});

function getVersionStatus() {
    
    $("#chknewver").html('{$smarty.const._MSG_WAIT_SM_}');
    
    $.getJSON(
        "/Help/chknewver",
        function (data, textStatus, jqXHR) {
            if (data.sts) {
            var last_version = data.__BUILD_VERSION__;
            } else {
            var last_version = data.msg;
            }
            $("#chknewver").text(last_version + " ( @ " + data.channel + " update channel )");
            if ($("#currentver").text() != last_version) {
                $("#chknewver").attr("style", "color:red;");
            } else {
                $("#chknewver").attr("style", "color:green;");
            }
        }
    );
    
}
</script>

<div class="heading-block">
    <h1>About GxTend</h1>
</div>

<div class="infoset">
<span class="ui-state-active ui-corner-all" style="padding:0 5px 0 5px;">Product Information</span>
    <ul>
        <li><strong>Layer :</strong> {$smarty.const.__LAYER_ROLE__}</li>
        <li><strong>Built On :</strong> {$InProve_Smarty->ts2str($smarty.const.__TIMESTAMP__)}</li>
        <li><strong>Current Installed Version :</strong> <span id="currentver">{$smarty.const.__BUILD_VERSION__}</span></li>
        {if $smarty.const.__LAYER_ROLE__ == "Server"}
        <li><strong>Metadata Status :</strong> 
            {if $InProve_Smarty->getSessVar("MetaData.checksts.sts")!="ok"}            
                <span style="color:red;">{$InProve_Smarty->getSessVar("MetaData.checksts.msg")}</span>
                &nbsp;<span class="pointer" onclick="mDialog('/Setup/reorg', 'View/Perform Pending Metadata Changes', 600, 900);">Click here to review/perform changes</span>
            {else}
                <span style="color:green;">{$InProve_Smarty->getSessVar("MetaData.checksts.msg")}</span>
            {/if}
        </li>
        <li><strong>Latest Available Build :</strong> <span id="chknewver"></span></li>
        <li><strong>Status of Related Services :</strong> <span id="servicessts">{$smarty.const._MSG_WAIT_SM_}</span></li>
        {/if}
    </ul>    
</div>

<div class="infoset">
<span class="ui-state-active ui-corner-all" style="padding:0 5px 0 5px;">License Information</span>
    <ul>
        <li><strong>Host GUID :</strong> {$gxtguid}</li>
        <li>
            <strong>Status :</strong>
            {if $licsts!="__VALID_KEY__"}
                &nbsp;<span class="red">{$licsts} - {constant($licsts)}</span>
                {if $iframesrc != "0601"}
                &nbsp;<span class="pointer" onclick="mDialog('{$iframesrc}', 'GxTend License Request', 480, 640);">Click here to request key</span>
                {else}
                &nbsp;Could not generate key request file.
                {/if}
            {else}
                &nbsp;<span class="green">Valid license installed, no issues detected.</span>
            {/if}
        </li>
        {if $licnfo}
        <li class="moreS2" style="display:none;"><strong>Requested :</strong> {$InProve_Smarty->ts2str($licnfo.key_data.requested)}</li>
        <li class="moreS2" style="display:none;"><strong>Generated :</strong> {$InProve_Smarty->ts2str($licnfo.key_data.generated)}</li>
        <li class="moreS2" style="display:none;"><strong>Type :</strong> {ucfirst($licnfo.license.lictype)}</li>
        <li class="moreS2" style="display:none;"><strong>Due Date :</strong> {$InProve_Smarty->ts2str(strtotime($licnfo.license.duedate),"date")}</li>
        <li class="moreS2" style="display:none;"><strong>Maximum Users :</strong> {$licnfo.license.maxusers}</li>
        <li class="moreS2" style="display:none;"><strong>Maximum KBs :</strong> {$licnfo.license.maxgxkbs}</li>
        <li style="list-style-type:none;font-size:.85em;">
            <a class="lblS2" style="display:block;" href="javascript:;" onclick="$('.moreS2,.lblS2').toggle();">See More...</a>
            <a class="lblS2" style="display:none;" href="javascript:;" onclick="$('.moreS2,.lblS2').toggle();">See Less...</a>
        </li>
        {/if}
    </ul>
</div>

<div class="infoset">
<span class="ui-state-active ui-corner-all left" style="padding:0 5px 0 5px;">Environment Information</span>
<span class="ui-icon ui-icon-gear pointer left" title="Click to view/set configuration entries" onclick="mDialog('/Config/?secti=4', 'Configuration Settings', 600, 900);"></span>
{$InProve_Smarty->get_popup_link("view_source","/View-Source/?filename={base64_encode('../temp/logs/error.log')}&send_as=error.log&brushas=xml",null,null,"800x600","<span class='ui-icon ui-icon-flag pointer left' title='Click to view error log'></span>")}
<br clear="all">
    <ul>
        <li><strong>Computer Name :</strong> {$osinfo.host}</li>
        <li><strong>OS Name :</strong> {$osinfo.name}</li>
        <li><strong>OS Architecture :</strong> {$osinfo.architecture}</li>
        <li class="moreS3" style="display:none;"><strong>OS Version :</strong> {$osinfo.version}</li>
        <li class="moreS3" style="display:none;"><strong>OS Level :</strong> {$osinfo.level}</li>
        <li class="moreS3" style="display:none;"><strong>OS Current Time :</strong> {$InProve_Smarty->ts2str($osinfo.time)}</li>
        <li class="moreS3" style="display:none;"><strong>OS Time Zone Offset :</strong> {$InProve_Smarty->sec2str($osinfo.timezone.offset)}</li>
        <li style="list-style-type:none;font-size:.85em;">
            <a class="lblS3" style="display:block;" href="javascript:;" onclick="$('.moreS3,.lblS3').toggle();">See More...</a>
            <a class="lblS3" style="display:none;" href="javascript:;" onclick="$('.moreS3,.lblS3').toggle();">See Less...</a>
        </li>
    </ul>
</div>

<div class="infoset">
<span class="ui-state-active ui-corner-all" style="padding:0 5px 0 5px;">Backend Information</span>
    <ul>
        <li><strong>Backend Version :</strong> {$beinfo.version}</li>
        <li class="moreS4" style="display:none;"><strong>PHP Max.Execution Time :</strong> {$InProve_Smarty->sec2str($InProve_Smarty->get_prm("php.max_execution_time"))}</li>
        <li class="moreS4" style="display:none;"><strong>PHP Max.Input Time :</strong> {$InProve_Smarty->sec2str($InProve_Smarty->get_prm("php.max_input_time"))}</li>
        <li class="moreS4" style="display:none;"><strong>PHP Memory Limit :</strong> {$InProve_Smarty->get_prm("php.memory_limit")}</li>
        <li class="moreS4" style="display:none;"><strong>PHP Time Zone Offset :</strong> {$InProve_Smarty->sec2str($InProve_Smarty->getSessVar("MyProfile.tz.gmtoffset"))}</li>
        
        <li style="list-style-type:none;font-size:.85em;">
            <a class="lblS4" style="display:block;" href="javascript:;" onclick="$('.moreS4,.lblS4').toggle();">See More...</a>
            <a class="lblS4" style="display:none;" href="javascript:;" onclick="$('.moreS4,.lblS4').toggle();">See Less...</a>
        </li>
    </ul>
</div>

<div class="myhr"></div>
<p>GxTend is a complete SCM (Software Configuration Management) tool that specifically target GeneXus projects.</p>
<p>Having an issue ? Please report to <a href="mailto:support@in-prove.com">support@in-prove.com</a> enclosing yours and your company name.</p>