<script type="text/javascript">
$(document).ready(function(){

     toggleLangs("{$smarty.cookies['gxtend_login_language']|default:'en'}");

});

function toggleLangs(lang) {
    $("#HandT #langs .file").attr("class", "file");
    $("#HandT #langopt_"+lang).attr("class", "file ui-state-highlight ui-corner-all");
    $("#HandT > #content > div").hide();
    $("#HandT #title").html($("#HandT #content #"+lang).prop("title"));
    $("#HandT #"+lang).show();    
    {if $htmlTag}
    $("#HandT #content #"+lang+" .tip_{$htmlTag}").show();
    {/if}
}
</script>

<div id="HandT">
    <span id="title" style="float:left;font-size:1.25em;font-weight:bold;">
        {if $type=="prmhlp"}
        {$lL.__parameter_information__}
        {/if}
    </span>
    <span id="langs" style="float:right;font-size:0.85em;">
        {foreach $avaLangs as $k => $v}
        <span id="langopt_{$k}" class="file" onclick="toggleLangs('{$k}');">&nbsp;{$v}&nbsp;</span>&nbsp;
        {/foreach}
    </span>
    <br clear="all">
    <div class="myhr"></div>
    <span id="content">
        {if $htmlFile}
        {include file="$htmlFile"}
        {else}
        {$htmlContent}
        {/if}
    </span>
</dif>