<script type="text/javascript">
$(document).ready(function(){

     toggleLangs("{$smarty.cookies['gxtend_login_language']|default:'en'}");

});

function toggleLangs(lang) {
    $("#HandT #langs .file").attr("class", "file");
    $("#HandT #langopt_"+lang).attr("class", "file ui-state-highlight ui-corner-all");
    $("#HandT > #content > div").hide();
    $("#HandT #title").html($("#HandT #content #"+lang).prop("title"));
    $("#HandT #"+lang).show();    
    {if $htmlTag}
    $("#HandT #content #"+lang+" .tip_{$htmlTag}").show();
    {/if}
}
</script>

<div id="HandT">
    <span id="title" style="float:left;font-size:1.25em;font-weight:bold;">
        {$title}
    </span>
    <span id="langs" style="float:right;font-size:0.85em;">
        <span id="langopt_en" class="file" onclick="toggleLangs('en');">&nbsp;English&nbsp;</span>&nbsp;
        <span id="langopt_es" class="file" onclick="toggleLangs('es');">&nbsp;Español&nbsp;</span>&nbsp;
        <span id="langopt_pt-br" class="file" onclick="toggleLangs('pt-br');">&nbsp;Português&nbsp;</span>
    </span>
    <br clear="all">
    <div class="myhr"></div>
    <span id="content">
        {if $htmlFile}
        {include file="$htmlFile"}
        {else}
        {$htmlContent}
        {/if}
    </span>
</dif>