<div id="en" style="display:none;" title="'Path & Ops' links">
    <p>
    <h3>Context</h3>
        <ul>
            <li><strong>Layer :</strong> Client</li>
            <li><strong>Location :</strong> "My Workspace &gt; Project/Kb &gt; Upper Left"</li>
        </ul>
    </p>
    <p>
    <h3>Links Functionality</h3>
    <p>&nbsp;<span style="font-style: italic; font-weight: bold;">'Path :'</span> This link opens a modal dialog that will allow the user to enter/edit the full path to the local Kb.</p>
    <p>&nbsp;<span style="font-style: italic; font-weight: bold;">'<img src='{$smarty.const._IMG_COMMIT_SM_}' alt='{$smarty.const._LBL_COMMIT_}' title=''>'</span> The 'commit' image link will list all changes that GxTend detects as pending to be saved in the local history repository.</p>
    <p>&nbsp;<span style="font-style: italic; font-weight: bold;">'<img src='{$smarty.const._IMG_CATCHUP_SM_}' alt='{$smarty.const._LBL_CATCHUP_}' title=''>'</span> The 'catchup' image link will list all changes performed by other members of the team.</p>
    <p>&nbsp;<span style="font-style: italic; font-weight: bold;">'<img src='{$smarty.const._IMG_PROMOTE_SM_}' alt='{$smarty.const._LBL_PROMOTE_}' title=''>'</span> The 'promote' image link will open a modal dialog, whose logic will run in the server, that will allow the user to import its commited changes into the consolidated Kb.</p>
    </p>
    <p>
    <h3>Overall Philosophy</h3>
    <p align="center"><img src="../img/handt/overall_philosophy.png" title="philosophy" width="90%" height="90%"></p>
    </p>
</div>

<div id="sp" style="display:none;" title="'Path & Ops' links">
    {include file='transNotAvailable.phtml'}
</div>

<div id="pt" style="display:none;" title="'Path & Ops' links">
    {include file='transNotAvailable.phtml'}
</div>