<div id="en" style="display:none;" title="GxTend's Trouble Ticket System">
    
    <span class="tip_notifications" style="display:none;">
        <h3># Notifications</h3>
        <p>The list of people that are currently subscribed to receive email notifications when new comments are posted.</p>
        <p>You can choose to unsubscribe by clicking the "Unsubscribe" action link next to your name.</p>
    </span>
    <span class="tip_subscribe" style="display:none;">
        <h3># Subscribe people to...</h3>
        <p>The people you select will get an email when you post this comment.</p>
        <p>They'll also get subscribed to receive future communications when new comments are added.</p>
    </span>
</div>

<div id="sp" style="display:none;" title="GxTend's Trouble Ticket System">
    {include file='transNotAvailable.phtml'}
</div>

<div id="pt" style="display:none;" title="GxTend's Trouble Ticket System">
    {include file='transNotAvailable.phtml'}
</div>