<div id="en" style="display:none;" title="__LNG__GxTend's Trouble Ticket System__LNG__">    
    <span class="tip_notifications" style="display:none;">
        <h3># __LNG__Notifications__LNG__</h3>
        <p>__LNG__The list of people that are currently subscribed to receive email notifications when new comments are posted__LNG__.</p>
        <p>__LNG__You can choose to unsubscribe by clicking the "Unsubscribe" action link next to your name__LNG__.</p>
    </span>
    <span class="tip_subscribe" style="display:none;">
        <h3># __LNG__Subscribe people to__LNG__...</h3>
        <p>__LNG__The people you select will get an email when you post this comment__LNG__.</p>
        <p>__LNG__They'll also get subscribed to receive future communications when new comments are added__LNG__.</p>
    </span>
</div>

<div id="es" style="display:none;" title="__LNG__GxTend's Trouble Ticket System__LNG__">
    {include file='transNotAvailable.phtml'}
</div>

<div id="pt-br" style="display:none;" title="__LNG__GxTend's Trouble Ticket System__LNG__">
    {include file='transNotAvailable.phtml'}
</div>