<script type="text/javascript">

$(document).ready(function(){
    $("#emailqueues #tabber").tabs({
        load: function(event, ui) {
            initializeButtons();
        }
    });
});

</script>

<div class="heading-block" style="margin-bottom:25px;">
    <span class="left" style="font-size:1.5em;font-weight:bold;">
    {if $smarty.request.id=="out"}
    __LNG__OutBound Messages__LNG__
    {else}
    __LNG__InBound Messages__LNG__
    {/if}
    </span>

    <span class="right">
    {$InProve_Smarty->get_popup_link("email_write","/Email-Mgmt/write",null,"","800x600","<span class='ui-icon ui-icon-pencil' style='display:inline-block;'></span> __LNG__Write new Message__LNG__")}
    {if $smarty.request.id=="out"}
        &nbsp;|&nbsp;<a href="javascript:;" onclick="loadappdiv('/Email-Mgmt/?id=in');"><span class="ui-icon ui-icon-arrowreturnthick-1-s" style="vertical-align:middle;display:inline-block;"></span> __LNG__InBound Messages__LNG__</a>
    {else}
        &nbsp;|&nbsp;<a href="javascript:;" onclick="loadappdiv('/Email-Mgmt/?id=out');"><span class="ui-icon ui-icon-arrowreturnthick-1-n" style="vertical-align:middle;display:inline-block;"></span> __LNG__OutBound Messages__LNG__</a>
    {/if}
    </span>
</div>

<br clear="all">

<div id="emailqueues">
    {$grid}
</div>