<script type="text/javascript">

$(document).ready(function(){
    $("#emailqueues #tabber").tabs({
        load: function(event, ui) {
            initializeButtons();
        }
    });
});

</script>
<div id="email_dashboard">
<div class="heading-block" style="margin-bottom:25px;">
    <span class="left" style="font-size:1.5em;font-weight:bold;">
    {if $smarty.request.id=="out"}
    {$lL.__outbound_messages__}
    {else}
    {$lL.__inbound_messages__}
    {/if}
    </span>

    <span class="right">
    {$InProve_Smarty->get_popup_link("email_write","/Email-Mgmt/write",null,"","800x600","<span class='ui-icon ui-icon-pencil' style='display:inline-block;'></span> {$lL.__write_new_message__}")}
    {if $smarty.request.id=="out"}
        &nbsp;|&nbsp;<a href="javascript:;" onclick="loadappdiv('/Email-Mgmt/?id=in',null,'#email_dashboard');"><span class="ui-icon ui-icon-arrowreturnthick-1-s" style="vertical-align:middle;display:inline-block;"></span> {$lL.__inbound_messages__}</a>
    {else}
        &nbsp;|&nbsp;<a href="javascript:;" onclick="loadappdiv('/Email-Mgmt/?id=out',null,'#email_dashboard');"><span class="ui-icon ui-icon-arrowreturnthick-1-n" style="vertical-align:middle;display:inline-block;"></span> {$lL.__outbound_messages__}</a>
    {/if}
    </span>
</div>

<br clear="all">

<div id="emailqueues">
    {$grid}
</div>
</div>