<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
    "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
    {include file='../index/common_head.phtml'}
    <script type="text/javascript">
    $(document).ready(function(){
        $("#tabs").tabs({
            select: function(event, ui) {
                if (ui.index==1) {
                $("#emailTab1 .atchs").load("/Ticket-Mgmt/atchs?emguid={$smarty.request.emguid}&preview=off");
                }
            }
        });        
    });
    </script>
</head>
<body class="popup">

    <table align="center" width="100%" class="list-horizontal">
    <tr>
		<td align="left" width="15%" class="header first" scope="row">
			Id / Type
		</td>
		<td align="left" class="first">
			{$InProve_Smarty->cutstr($email.emguid,0,$smarty.const._GUID_LEN_)} / {if $email.emsentts>-1}Outbound{else}Inbound{/if}
            <span style="float:right;">{$reply}  Reply | {$forward} Forward</span>
		</td>
	</tr>
    <tr>
		<td align="left" class="header" scope="row">
			{if $email.emsentts>-1}
                Date / Status
            {else}
                Date
            {/if}			
		</td>
		<td align="left">
			{if $email.emsentts>-1}
    			{if $email.emsentts==0}
                    {if $email.emsentlog<>''}
                    {$smarty.const._DELIVERY_ERROR_}
                    {else}
                    {$smarty.const._DELIVERY_PENDING_}
                    {/if}
                {else}
                    {$InProve_Smarty->ts2str($email.emsentts)}
                {/if}
            {else}
                {$InProve_Smarty->ts2str($email.emqueuets)}
            {/if}
		</td>
	</tr>
    <tr>
		<td align="left" class="header" scope="row">
			From
		</td>
		<td align="left">
			{$email.emheader.from.name} &lt;{$email.emheader.from.mail}&gt;
		</td>
	</tr>
    <tr>
		<td align="left" class="header" scope="row">
			To
		</td>
		<td align="left">
			{$email.emheader.to.name} &lt;{$email.emheader.to.mail}&gt;
		</td>
	</tr>
    {if $email.emheader.cc.mail}
    <tr>
        <td align="left" class="header" scope="row">
            Cc
        </td>
        <td align="left">
            {$email.emheader.cc.name} &lt;{$email.emheader.cc.mail}&gt;
        </td>
    </tr>
    {/if}
    {if $email.emheader.bcc.mail}
    <tr>
        <td align="left" class="header" scope="row">
            Bcc
        </td>
        <td align="left">
            {$email.emheader.bcc.name} &lt;{$email.emheader.bcc.mail}&gt;
        </td>
    </tr>
    {/if}
    <tr>
		<td align="left" class="header" scope="row">
			Subject
		</td>
		<td align="left">
			{$email.emheader.subject}
		</td>
	</tr>
    </table>

    <div id="tabs">
        <ul>
            <li><a href="#emailTab0"><span>Body</span></a></li>
            <li><a href="#emailTab1"><span>Attachments</span></a></li>
            <li><a href="#emailTab2"><span>Headers</span></a></li>
            <li><a href="#emailTab3"><span>Log</span></a></li>
        </ul>
        <div id="emailTab0">
            {$email.embody}
        </div>
        <div id="emailTab1">            
            <div class="atchs" style="margin:5px; text-align:right;">
                {$smarty.const._MSG_WAIT_SM_}
            </div>
            {if $atchs}
            <div style="font-size:0.8em;float:right;cursor:pointer;">
            <span class="togglePreview" onclick="$('#emailTab1 .atchs').load('/Ticket-Mgmt/atchs?emguid={$smarty.request.emguid}&preview=on');$('#emailTab1 .togglePreview').toggle();" style="display:inline;">Enable Preview</span>
            <span class="togglePreview" onclick="$('#emailTab1 .atchs').load('/Ticket-Mgmt/atchs?emguid={$smarty.request.emguid}&preview=off');$('#emailTab1 .togglePreview').toggle();" style="display:none;">Disable Preview</span>
            </div>
            <br clear="both">
            {/if}
        </div>
        <div id="emailTab2">
            <pre>{$email.emheader.raw}</pre>
        </div>
        <div id="emailTab3">
            <pre>{$email.emsentlog}</pre>
        </div>
    </div>

</body>
</html>