{include file="../skel/header.phtml" class="popup"}
<script type="text/javascript">
$(document).ready(function(){
    //
    initializeButtons();

    // Form submit...
    $("#write_email_form").ajaxForm({
        dataType: 'json',
        async: false,
        beforeSubmit: function() {
            $('#write_email_form .toValidate').validate({
            ignore: ":hidden"
            });
            if ( $('.toValidate').valid() ) {
                $("#write_email_form .submit_btn_holder").toggle();
                return true;
            }
            return false;
        },
        success: function (r) {
            if (r.sts) {
                setTimeout('window.close();', 2500);
            } else {
                $("#write_email_form .submit_btn_holder").toggle();
            }
        },
        error: function (jqXHR) {
            handleXHRerror(jqXHR);
        }
    });

    initRichTextEditor("body","MyBasicOptions");

});
</script>

    <h2 style="float:right;">{$lL.__write_email__}&nbsp;</h2>
    <br clear="all">
    <form id="write_email_form" class="toValidate" action="/Email-Mgmt/send" method="POST" enctype="multipart/form-data">
    <input type="hidden" name="options" value="{$b64options}">
    <table align="center" width="100%" class="list-horizontal">
    <tr id="toRow">
		<td align="left" width="15%" class="header first" scope="row">
			{$lL.__to__}
		</td>
		<td align="left" class="first">
            {if $smarty.request.op=='Re'}
            <input type="text" name="to" value="{$email.emheader.to.mail}" class="required email" style="width:55%;" >
            {else}
            <input type="text" name="to" value="" class="required email" style="width:50%;" >
            {/if}
            <span style="font-size:.8em;">
            <a href="javascript:;" id="add_cc_lnk" onclick="javascript:$('#ccRow').show();$('#add_cc_lnk,#add_sepa').hide();">{$lL.__add_cc__}</a>
            <span id="add_sepa">|</span>
            <a href="javascript:;" id="add_bcc_lnk" onclick="javascript:$('#bccRow').show();$('#add_bcc_lnk,#add_sepa').hide();">{$lL.__add_bcc__}</a>
            </span>
            <span style="float:right;">
            <label for="priority"><strong>{$lL.__priority__}</strong></label>
            {$priority}
            </span>
		</td>
	</tr>
    <tr id="ccRow" style="display:none;">
		<td align="left" class="header" scope="row">
			{$lL.__cc__}
		</td>
		<td align="left">
            <input type="text" name="cc" value="{$cc}" class="email" style="width:50%;">
		</td>
    </tr>
    <tr id="bccRow" style="display:none;">
		<td align="left" class="header" scope="row">
			{$lL.__bcc__}
		</td>
		<td align="left">
            <input type="text" name="bcc" value="{$bcc}" class="email" style="width:50%;">
		</td>
    </tr>
    <tr id="subjectRow" >
		<td align="left" class="header" scope="row">
			{$lL.__subject__}
		</td>
		<td align="left">
            {if $smarty.request.op=='Re'}
            <input type="text" name="subject" value="Re: {$email.emheader.subject}" class="required" style="width:99%;">
            {elseif $smarty.request.op=='Fwd'}
            <input type="text" name="subject" value="[Fwd: {$email.emheader.subject}]" class="required" style="width:99%;">
            {else}
            <input type="text" name="subject" value="{$subject}" class="required" style="width:99%;">
            {/if}
		</td>
	</tr>
    <tr id="attchsRow" style="display:none;">
		<td align="left" class="header" scope="row">
			{$lL.__attachments__}
		</td>
		<td align="left">
            <span id="attchsHolder"></span>
		</td>
    </tr>
    </table>
    <div>
        <span class="toggleToolbar" onclick="rsetRichTextEditor('body','MyFullOptions');$('.toggleToolbar').toggle();" style="display:inline;font-size:.8em;float:right;cursor:pointer;">{$lL.__toggle_to_full_toolbar__}</span>
        <span class="toggleToolbar" onclick="rsetRichTextEditor('body','MyBasicOptions');$('.toggleToolbar').toggle();" style="display:none;font-size:.8em;float:right;cursor:pointer;">{$lL.__toggle_to_basic_toolbar__}</span>
    </div>
    <br clear="all">
    <div>
        <textarea id="body" name="body" rows="15" cols="70">{$body}</textarea>
    </div>
    <br clear="all">
    <div class="buttons left">
        {include file='../Upload/widget.phtml' dlgTitle={$lL.__file_upload_dialog__} btnLabel={$lL.__attach_file_s___}}
    </div>
    <div class="buttons right">
        <div class="submit_btn_holder">
        {$smarty.const._FORM_BTN_SUBMIT_}
        &nbsp;{$lL.__or__}&nbsp;
        <a href="javascript:;" onclick="window.close();">{$lL.__cancel__}</a>&nbsp;
        </div>
        <div class="submit_btn_holder" style="display:none;">
        {$smarty.const._BAR_WAIT_}
        </div>
    </div>
    </form>

{include file="../skel/footer.phtml"}