{include file="../skel/header.phtml"}
<script type="text/javascript">
$(document).ready(function(){
    //
    initializeButtons();

    // Form submit...
    $("#write_email_form").ajaxForm({
        dataType: 'json',
        async: false,
        beforeSubmit: function() {
            $('#write_email_form .toValidate').validate({
            ignore: ":hidden"
            });
            if ( $('.toValidate').valid() ) {
                $("#write_email_form .submit_btn_holder").toggle();
                return true;
            }
            return false;
        },
        success: function (r) {
            if (r.sts) {
                setTimeout('window.close();', 2500);
            } else {
                $("#write_email_form .submit_btn_holder").toggle();
            }
        },
        error: function (jqXHR) {
            handleXHRerror(jqXHR);
        }
    });

    initRichTextEditor("body","MyBasicOptions");

});
</script>

    <h2 style="float:right;">__LNG__Write Email__LNG__&nbsp;</h2>
    <br clear="all">
    <form id="write_email_form" class="toValidate" action="/Email-Mgmt/send" method="POST" enctype="multipart/form-data">
    <input type="hidden" name="options" value="{$b64options}">
    <table align="center" width="100%" class="list-horizontal">
    <tr id="toRow">
		<td align="left" width="15%" class="header first" scope="row">
			__LNG__To__LNG__
		</td>
		<td align="left" class="first">
            {if $smarty.request.op=='Re'}
            <input type="text" name="to" value="{$email.emheader.to.mail}" class="required email" style="width:55%;" >
            {else}
            <input type="text" name="to" value="" class="required email" style="width:50%;" >
            {/if}
            <span style="font-size:.8em;">
            <a href="javascript:;" id="add_cc_lnk" onclick="javascript:$('#ccRow').show();$('#add_cc_lnk,#add_sepa').hide();">__LNG__Add Cc__LNG__</a>
            <span id="add_sepa">|</span>
            <a href="javascript:;" id="add_bcc_lnk" onclick="javascript:$('#bccRow').show();$('#add_bcc_lnk,#add_sepa').hide();">__LNG__Add Bcc__LNG__</a>
            </span>
            <span style="float:right;">
            <label for="priority"><strong>__LNG__Priority__LNG__</strong></label>
            {$priority}
            </span>
		</td>
	</tr>
    <tr id="ccRow" style="display:none;">
		<td align="left" class="header" scope="row">
			__LNG__Cc__LNG__
		</td>
		<td align="left">
            <input type="text" name="cc" value="{$cc}" class="email" style="width:50%;">
		</td>
    </tr>
    <tr id="bccRow" style="display:none;">
		<td align="left" class="header" scope="row">
			__LNG__Bcc__LNG__
		</td>
		<td align="left">
            <input type="text" name="bcc" value="{$bcc}" class="email" style="width:50%;">
		</td>
    </tr>
    <tr id="subjectRow" >
		<td align="left" class="header" scope="row">
			__LNG__Subject__LNG__
		</td>
		<td align="left">
            {if $smarty.request.op=='Re'}
            <input type="text" name="subject" value="Re: {$email.emheader.subject}" class="required" style="width:99%;">
            {elseif $smarty.request.op=='Fwd'}
            <input type="text" name="subject" value="[Fwd: {$email.emheader.subject}]" class="required" style="width:99%;">
            {else}
            <input type="text" name="subject" value="{$subject}" class="required" style="width:99%;">
            {/if}
		</td>
	</tr>
    <tr id="attchsRow" style="display:none;">
		<td align="left" class="header" scope="row">
			__LNG__Attachments__LNG__
		</td>
		<td align="left">
            <span id="attchsHolder"></span>
		</td>
    </tr>
    </table>
    <div>
        <span class="toggleToolbar" onclick="rsetRichTextEditor('body','MyFullOptions');$('.toggleToolbar').toggle();" style="display:inline;font-size:.8em;float:right;cursor:pointer;">__LNG__Toggle to Full Toolbar__LNG__</span>
        <span class="toggleToolbar" onclick="rsetRichTextEditor('body','MyBasicOptions');$('.toggleToolbar').toggle();" style="display:none;font-size:.8em;float:right;cursor:pointer;">__LNG__Toggle to Basic Toolbar__LNG__</span>
    </div>
    <br clear="all">
    <div>
        <textarea id="body" name="body" rows="15" cols="70">{$body}</textarea>
    </div>
    <br clear="all">
    <div class="buttons left">
        {include file='../Upload/widget.phtml' dlgTitle=__LNG__File Upload Dialog__LNG__ btnLabel=__LNG__Attach File(s)__LNG__}
    </div>
    <div class="buttons right">
        <div class="submit_btn_holder">
        {$smarty.const._FORM_BTN_SUBMIT_}
        &nbsp;__LNG__or__LNG__&nbsp;
        <a href="javascript:;" onclick="window.close();">__LNG__cancel__LNG__</a>&nbsp;
        </div>
        <div class="submit_btn_holder" style="display:none;">
        {$smarty.const._BAR_WAIT_}
        </div>
    </div>
    </form>

{include file="../skel/footer.phtml"}