<ul id="appmenu">
    <li id="my_options"><span class="folder">{$lL.__my_options__}</span>
        <ul>
        <li><span class="file" onclick="loadappdiv('/My-Profile/')">{$lL.__my_profile__}</span></li>
        </ul>
    </li>
    <li id="people"><span class="folder">{$lL.__people__}</span>
        <ul>
            <li><span class="file" onclick="loadappdiv('/Tbls-Mgmt/?tbl=gxt_clients')">{$lL.__clients__}</span></li>
            <li><span class="file" onclick="loadappdiv('/Tbls-Mgmt/?tbl=gxt_users')">{$lL.__users__}</span></li>
            <li><span class="file" onclick="loadappdiv('/Tbls-Mgmt/?tbl=gxt_groups')">{$lL.__users__groups__}</span></li>
            <li><span class="file" onclick="loadappdiv('/Tbls-Mgmt/?tbl=gxt_hosts')">{$lL.__hosts__}</span></li>
        </ul>
    </li>
    <li id="knowledge"><span class="folder">{$lL.__knowledge__}</span>
        <ul>
            <li id="knowledge_task_definition"><span class="folder">{$lL.__tasks_definition__}</span>
                <ul>
                <li><span class="file" onclick="loadappdiv('/Tbls-Mgmt/?tbl=gxt_projects')">{$lL.__projects__}</span></li>
                <li><span class="file" onclick="loadappdiv('/Tbls-Mgmt/?tbl=gxt_milestones')">{$lL.__milestones__}</span></li>
                <li><span class="file" onclick="loadappdiv('/Tbls-Mgmt/?tbl=gxt_todos')">{$lL.__to_do_lists__}</span></li>
                <li><span class="file" onclick="loadappdiv('/Ticket-Mgmt/listall')">{$lL.__tickets__}</span></li>
                </ul>
            </li>
            <li id="knowledge_code"><span class="folder">{$lL.__code__}</span>
                <ul>
                <li><span class="file" onclick="loadappdiv('/Tbls-Mgmt/?tbl=gxt_kbs')">{$lL.__kbs_mgmt___}</span></li>
                <li><span class="file" onclick="loadappdiv('/Browse-Repos/')">{$lL.__browse_kbs__}</span></li>
                <li><span class="file" onclick="loadappdiv('/Browse-History/')">{$lL.__browse_history__}</span></li>
                <li><span class="file" onclick="loadappdiv('/Comp-Kbs/')">{$lL.__compare___promote__}</span></li>
                </ul>
            </li>
        </ul>
    </li>
    <li id="settings"><span class="folder">{$lL.__settings___monitoring__}</span>
        <ul>
            <li><span class="file" onclick="loadappdiv('/Tbls-Mgmt/?tbl=gxt_prmdef')">{$lL.__parameters__}</span></li>
            <li><span class="file" onclick="loadappdiv('/Tbls-Mgmt/?tbl=gxt_evtdef')">{$lL.__events__scheduler___}</span></li>
            <li id="settings_background_ops"><span class="folder">{$lL.__background_ops__}</span>
                <ul>
                    <li><span class="file" onclick="loadappdiv('/Tbls-Mgmt/?tbl=gxt_evtqueue')">{$lL.__events_queue__}</span></li>
                    <li><span class="file" onclick="loadappdiv('/Email-Mgmt/?id=out')">{$lL.__e_mail_queue__}</span></li>
                </ul>
            </li>
            <li id="settings_audit_info"><span class="folder">{$lL.__audit_info__}</span>
                <ul>
                    <li><span class="file" onclick="loadappdiv('/Tbls-Mgmt/?tbl=gxt_sessions')">{$lL.__app_sessions__}</span></li>
                    <li><span class="file" onclick="loadappdiv('/Logs-Mgmt/')">{$lL.__app_logs__}</span></li>
                </ul>
            </li>
        </ul>
    </li>
    <li id="help"><span class="folder">{$lL.__help__}</span>
        <ul>
            <li><span class="file" onclick="loadappdiv('/Help/about')">{$lL.__about__}</span></li>
            <li id="help_debugging_tools" class="dbgtoolsmnu" style="display:none;"><span class="folder red">{$lL.__debugging_tools__}</span>
                <ul>
                    <li><span class="file" onclick="loadappdiv('/tools/dbquery')">{$lL.__query_metadata__}</span></li>
                    <li><span class="file" onclick="loadappdiv('/tools/kbquery')">{$lL.__query_gxkb__}</span></li>
                </ul>
            </li>
        </ul>
    </li>
    <li style="padding-top:1em;text-align:right;font-size:1.15em;">
        <span class="file logout" onclick="mDialog('/index/logout', '...', 150, 300);">
        {$lL.__logout__} <span class="ui-icon ui-icon-power" style="display:inline-block;vertical-align:middle;"></span>
        </span>
    </li>
</ul>