<ul id="appmenu">
    <li id="my_options"><span class="folder">{$lL.__my_options__}</span>
        <ul>
        <li><span class="file" onclick="loadappdiv('/My-Profile/');">{$lL.__my_profile__}</span></li>
        <li id="logging"><span class="folder">{$lL.__logging__}</span>
            <ul>
            <li><span class="file" onclick="loadappdiv('/Tbls-Mgmt/?tbl=gxt_evtqueue');">{$lL.__queued_events__}</span></li>
            <li><span class="file" onclick="loadappdiv('/Logs-Mgmt/');">{$lL.__app_logs__}</span></li>
            <li><span class="file" onclick="loadappdiv('/Sync-Mgmt/');">{$lL.__sync_status__}</span></li>
            </ul>
        </li>
        </ul>
    </li>
    <li id="tasks_definition"><span class="folder">{$lL.__tasks_definition__}</span>
        <ul>
            <li><span class="file" onclick="loadappdiv('/Tbls-Mgmt/?tbl=gxt_milestones');">{$lL.__milestones__}</span></li>
            <li><span class="file" onclick="loadappdiv('/Tbls-Mgmt/?tbl=gxt_todos');">{$lL.__to_do_lists__}</span></li>
            <li><span class="file" onclick="loadappdiv('/Ticket-Mgmt/listall');">{$lL.__tickets__}</span></li>
        </ul>
    </li>
    <li id="help"><span class="folder">{$lL.__help__}</span>
        <ul>
            <li><span class="file" onclick="loadappdiv('/Help/about');">{$lL.__about__}</span></li>
            <li id="help_debugging_tools" class="dbgtoolsmnu" style="display:none;"><span class="folder red">{$lL.__debugging_tools__}</span>
                <ul>
                    <li><span class="file" onclick="loadappdiv('/tools/dbquery');">{$lL.__query_metadata__}</span></li>
                    <li><span class="file" onclick="loadappdiv('/tools/kbquery');">{$lL.__query_gxkb__}</span></li>
                </ul>
            </li>
        </ul>
    </li>
    <li style="padding-top:1em;text-align:right;font-size:1.15em;">
        <span class="file logout" onclick="mDialog('/index/logout', '...', 150, 300);">
        {$lL.__logout__} <span class="ui-icon ui-icon-power" style="display:inline-block;vertical-align:middle;"></span>
        </span>
    </li>
</ul>