{include file="../skel/header.phtml"}
<script type="text/javascript">
$(document).ready(function(){
    $("#tabs").tabs();
});
</script>

    <h2 style="float:right;">__LNG__Event Entry Details__LNG__&nbsp;</h2>
    <br clear="all">
    <table align="center" width="100%" class="list-horizontal">
    <tr>
		<td align="left" class="header first" scope="row">
			Id #
		</td>
		<td align="left" class="first">
			{$record.evtid}
		</td>
	</tr>
    <tr>
		<td align="left" class="header" scope="row">
			__LNG__Code / Desc.__LNG__
		</td>
		<td align="left">
			{$record.evtname} / {$record.evtdsc}
		</td>
	</tr>
    <tr>
		<td align="left" class="header" scope="row">
			__LNG__User__LNG__
		</td>
		<td align="left">
			{$InProve_Smarty->guid2name("gxt_users",$record.userguid)}
		</td>
	</tr>
    <tr>
		<td align="left" class="header" scope="row">
			__LNG__Event Type__LNG__
		</td>
		<td align="left">
			{ucfirst($record.evttype)}
		</td>
	</tr>
    <tr>
		<td align="left" class="header" scope="row">
			__LNG__Queue -> Start -> Finish__LNG__
		</td>
		<td align="left">
			{$InProve_Smarty->ts2str($record.queue_time)} -> {$InProve_Smarty->ts2str($record.ini_time)} -> {$InProve_Smarty->ts2str($record.end_time)}
		</td>
	</tr>
    <tr>
		<td align="left" class="header" scope="row">
			__LNG__Current Status / TTP__LNG__
		</td>
		<td align="left">
			{$record.status} / {$InProve_Smarty->sec2str($record.end_time - $record.ini_time)}
		</td>
	</tr>
    </table>
    <p>
    <div class="inoutlog" id="tabs">
    <ul>
        {if $record.masklog}
        <li><a href="#tab-1"><span>__LNG__Log__LNG__</span></a></li>
        {/if}
        <li><a href="#tab-2"><span>__LNG__Raw Input__LNG__</span></a></li>
        <li><a href="#tab-3"><span>__LNG__Raw Output__LNG__</span></a></li>
    </ul>
        {if $record.masklog}
        <div id="tab-1">
            {$record.masklog}
        </div>
        {/if}
        <div id="tab-2">
            {$InProve_Smarty->dBug($record.inoutlog.in)}
        </div>
        <div id="tab-3">
            {$InProve_Smarty->dBug($record.inoutlog.out)}
        </div>
    </div>

{include file="../skel/footer.phtml"}