<div id="log_promote">
    <div class="column left">
        <strong>{$lL.__target__} : </strong> {$InProve_Smarty->guid2name('gxt_kbs', $logData.kbguid)}
        <br>
        <strong>{$lL.__unlock_after_import__} : </strong> {($logData.unlockAimport) ? "{$lL.__yes__}" : "{$lL.__no__}"}
    </div>
    <div class="column right">
        <strong>{$lL.__queued_for_batch_processing__} : </strong> {($logData.queue4exec) ? "{$lL.__yes__}" : "{$lL.__no__}"}
        <br>
        <strong>{$lL.__process_result_audit_entry__} : </strong> {$logData.output}
    </div>
    <br clear="all">
    <div class="myhr"></div>
    
    <div class="column left">
        {$lL.__objects_are_listed_in_the_order_they_were_submitted__}.
    </div>
    <div class="column right">
        {count($logData.checked_objs)} {$lL.__row_s___}
    </div>
    <br clear="all">
    <table width="100%" align="center" class="list">
    <thead>
        <tr><th>{$lL.__object__}</th><th>{$lL.__modified__} &darr;</th></tr>
    </thead>
    <tbody>
        {foreach from=$logData.checked_objs key=k item=rec}
        <tr class='{cycle values="odd,even"}'>
        <td>&nbsp;
            {if $rec.gxinfo.objcls!=111}
            <img src="../img/gx/objclass/{$gx_objcls[$rec.gxinfo.objcls].small}.png" title="{$gx_objcls[$rec.gxinfo.objcls].long}">
            &nbsp;{$rec.gxinfo.objnam}
            {else}
            <img src="../img/icons/16/file.png" title="File">
            &nbsp;{$rec.gxinfo.objnam|basename}
            {/if}
        </td>
        <td align="center">
            &nbsp;{$InProve_Smarty->ts2str($rec.gxinfo.objupdts)}
            {if $rec.gxinfo.COMP=="NEW" && $rec.gxinfo.COMPREF!="DELETED_FROM_GXKB"}
            &nbsp;<img alt="new" src="../img/icons/16/new.png" title="{$lL.__does_not_exist_in_target__}.">
            {elseif $rec.gxinfo.COMP=="NEW" && $rec.gxinfo.COMPREF=="DELETED_FROM_GXKB"}
            &nbsp;<img alt="del" src="../img/icons/16/cleanup.png" title="{$lL.__object_detected_as_deleted_in_source__}.">
            {elseif $rec.gxinfo.COMP=="OLDER"}
            &nbsp;<img alt="older" src="../img/icons/16/warning.png" title="{$lL.__target_modified_on__} {$InProve_Smarty->ts2str($rec.gxinfo.COMPREF)}">
            {/if}
            {if $rec.gxinfo.generated==1}
            &nbsp;<img alt="gen1" src="../img/icons/16/lightning_green.png" title="{$lL.__automatically_generated__}.">
            {else if $rec.gxinfo.generated==2}
            &nbsp;<img alt="gen2" src="../img/icons/16/lightning_red.png" title="{$lL.__automatically_generated_but_modified__}.">
            {/if}
        </td>
        </tr>
        {/foreach}
    </tbody>
    </table>
</div>