<script type="text/javascript">
$(document).ready(function(){

	$("#form_fetch").ajaxForm({
		dataType:  'json',
		beforeSubmit: function() {
			$("#synch").block({ message: '{$smarty.const._BAR_WAIT_}' });
            $("#div_fetch #bottom_left").html("");
		},
		success: function (r) {
            for ( var i in r.fetch ) {
                if (r.fetch[i] == "ok") {
                    $("#"+i).html("<img src='../img/icons/32/tick.png' alt='ok' title='"+r.fetch[i]+"'>");
                } else {
                    $("#"+i).html("<img src='../img/icons/32/error.png' alt='err' title='"+r.fetch[i]+"'>");
                }
            }

            if (r.sts == "ok") {
                $("#div_fetch #bottom_left").html("<img src='../img/icons/32/tick.png' alt='ok' title='ok'> Successful Fetch "+r.msg);
                $("#form_fetch button").attr("disabled", "disabled");
                if ($("#mergeAfetch:checked").val()) {
                    mergeAfetch()
                } else {
                    $("#synch").unblock();
                }
            } else if (r.sts == "wrn") {
                $("#div_fetch #bottom_left").html("<img src='../img/icons/32/warning.png' alt='wrn' title='err'> Fetching Data Warning "+r.msg);
                $("#synch").unblock();
            } else {
                $("#div_fetch #bottom_left").html("<img src='../img/icons/32/error.png' alt='err' title='err'> Fetching Data Error "+r.msg);
                $("#synch").unblock();
            }
        },
        error: function (jqXHR) {
            handleXHRerror(jqXHR);
        }
	});

    $("#east_panel #project #div_fetch img.tip").cluetip({ splitTitle: "|" });
});

function mergeAfetch() {
    jQuery.getJSON(
            "/Fetch/merge?projguid={$smarty.request.projguid}",
            null,
            function (r, textStatus) {
                if (r.sts == "ok") {
                    $("#div_fetch #bottom_left").append("<p><img src='../img/icons/32/tick.png' alt='ok' title='ok'> Successful Merge "+r.msg);
                } else {
                    $("#div_fetch #bottom_left").append("<p><img src='../img/icons/32/error.png' alt='err' title='err'> Error in Merge "+r.msg);
                }
                $("#synch").unblock();
            }
    );
}
</script>
<div id="div_fetch">

<fieldset>
    <legend>
        <img src='{$smarty.const._IMG_FETCH_SM_}' alt='Fetch' title=''>&nbsp;Fetch from Server. 
        [&nbsp;
        <span class='file' title='{$smarty.const._TITLE_HIDE_}' onclick='$("#synch").hide("slow");'>&laquo;</span>
        &nbsp;]
    </legend>
    {if !is_array($remote_changes)}
        <br clear="all">
        {$InProve_Smarty->msg("ui-icon-info","None Found")}
        <div class="myhr"></div>
        <div id="bottom_left" class="left">
            {include file='../index/ttp.phtml'}
        </div>
        <div  id="bottom_right" class="right">
            &nbsp;
        </div>
    {else}
	<form id="form_fetch" action="Fetch/fetch" method="POST" enctype="multipart/form-data">
    <input type="hidden" name="projguid" value="{$smarty.request.projguid}">
        {foreach from=$remote_changes key=commit_id item=commit_data}        
        <br clear="all">
        <span class="column left">
            <b>Id :</b> {$InProve_Smarty->cutstr($commit_id,0,7)}
            {if $commit_data.codeline == $InProve_Smarty->getSessVar("MyProfile.userdata.username")}
                &nbsp;<img class="tip" alt="merge" src="../img/icons/16/warning.png" title="Commit's Compare Status|Commit in remote personal codeline not present in local personal codeline.">
                {assign var=commitsToMerge value=$commitsToMerge+1}
            {/if}
            <br>
            <img src='{$smarty.const._IMG_COMMENT_BLUE_SM_}' alt="comment" title='Comment' style="vertical-align:text-top;"> {$InProve_Smarty->cutstr($commit_data.subject,0,80)}
        </span>
        <span class="column right" id="{$commit_id}">
            <b>Commited on :</b> {$InProve_Smarty->ts2str($commit_data.commiterTs)}<br>
            <b>Commited by :</b> {$commit_data.commiter}
            <input type="hidden" name="commits[]" value="{$commit_id}">
        </span>
        <br clear="all">
        <table width="100%" align="center" class="list">
        <thead>
            <tr><th>Kb<br>&nbsp;# Env.</th><th>Object</th><th>STS</th></tr>
        </thead>
        <tbody>
            {foreach from=$commit_data.changes key=kbguid item=kb_commit_data}
                <tr>
                    <td colspan="3">{$kb_commit_data.kbinfo.visualid}</td>
                </tr>
                {foreach from=$kb_commit_data.objects key=k item=rec}
                {if $k<3}
                <tr class='{cycle values="odd,even"}'>
                    <td>&nbsp;{$rec.gxinfo.mdlid}</td>
                    <td>&nbsp;
                        {if $rec.gxinfo.objcls!=111}
                        <img src="../img/gx/objclass/{$gx_objcls[$rec.gxinfo.objcls].small}.png" title="{$gx_objcls[$rec.gxinfo.objcls].long}">
                        {else}
                        <img src="../img/icons/16/file.png" title="File">
                        {/if}
                        &nbsp;{$rec.gxinfo.objnam}
                    </td>
                    <td align="center">
                        {if $rec.gitnfo.status=="A"}
                            <img class="tip" alt="new" src="../img/icons/16/new.png" title="Change Description [{$rec.gitnfo.status}]|Object created in this commit.">
                        {elseif $rec.gitnfo.status=="M"}
                            <img class="tip" alt="new" src="../img/icons/16/edit.png" title="Change Description [{$rec.gitnfo.status}]|Object was modified in this commit.">
                        {elseif $rec.gitnfo.status=="D"}
                            <img class="tip" alt="new" src="../img/icons/16/cleanup.png" title="Change Description [{$rec.gitnfo.status}]|Object was deleted in this commit.">
                        {/if}
                    </td>
                </tr>
                {/if}
                {/foreach}
                    {assign var=totrecs value=$k+1}
                    <tr class='{cycle values="odd,even"}'>
                    {if $k>3}
                        <td colspan="3" style="text-align:right;font-size:.90em;">3 out of {$totrecs} objects in this commit.&nbsp;</td>
                    {else}
                        <td colspan="3" style="text-align:right;font-size:.90em;">{$totrecs} object(s) in this commit.&nbsp;</td>
                    {/if}
                    </tr>
            {/foreach}
        </tbody>
        </table>
        {/foreach}

        <div class="myhr"></div>

        <div style="float:right;">
            {if $commitsToMerge}
                <img alt="merge" src="../img/icons/16/repo-join.png" title="Merge remote PCL codeline into local PCL">
                &nbsp;Merge PCL after fetch
                &nbsp;<input type="checkbox" id="mergeAfetch" value="1" checked>&nbsp;
            {/if}
        </div>        
        <br clear="all">
        <br clear="all">
        <div id="bottom_left" class="left">
            {include file='../index/ttp.phtml'}
        </div>
        <div  id="bottom_right" class="buttons right">
            {$smarty.const._FORM_BTN_FETCH_}
        </div>
	</form>
    {/if}
</fieldset>

</div>