<!-- <script type="text/javascript" src="../js/addons/singlef/jquery.printElement.js"></script> -->

<script type="text/javascript">
$(document).ready(function(){
    
	$("#expdata form").ajaxForm({
		dataType: 'json',
        async: true,
		beforeSubmit: function() {
            $("#GenericDialog").block({ message: '{$smarty.const._MSG_WAIT_}' });
		},
		success: function (r) {
            $("#GenericDialog").block({ message: r.msg });
            if (r.sts) {
                if (r.action=="Export") {
                    setTimeout('$("#GenericDialog").dialog("close");location.href="'+r.url+'";', 1500);
                }
                if (r.action=="Print") {
                    setTimeout('$("#GenericDialog").dialog("close");$("#UploadDialog").load("'+r.url+'", function() { $(this).find("table").printElement(); });', 1500);
                }
            } else {
                setTimeout('$("#GenericDialog").unblock();', 3000);
            }
        },
        error: function (jqXHR) {
            handleXHRerror(jqXHR);
        }
	});

    $("#expdata input:text:visible:first").focus();

});
</script>
<div id="expdata">
    <h3>{$lL.__select_export_options_and_then_submit__}</h3>
    <div class="myhr"></div>
    <form action="/Export/grid2excel" method="POST" enctype="multipart/form-data">
    <input type="hidden" id="deffile" name="deffile" value="{$smarty.request.deffile}">
        <table>
		<tr>
            <td align="left">
                <strong>{$lL.__range__}</strong>
            </td>
			<td align="left">
                <input type="radio" id="range_all" class="radio" name="range" value="ALL" checked="checked">&nbsp;{$lL.__all__}
                <input type="radio" id="range_cur" class="radio" name="range" value="Current" disabled="disabled">&nbsp;{$lL.__grid_s_current_set__}
            </td>
        </tr>
        <tr><td colspan="2">&nbsp;</td></tr>
        <tr><td colspan="2"><strong>{$lL.__available_export_sets__}</strong></td></tr>
		<tr>
            <td align="left">
                &nbsp;
            </td>
			<td align="left">
                {foreach from=$expoconf key=desc item=qry}
                <input type="radio" id="eset_{$desc|sha1}" class="radio" name="eset" value="{$qry|base64_encode}" checked="checked" onclick="$('#fname').val('Grid_Export_{$smarty.now}.xls');">&nbsp;{$desc}
                {/foreach}
            </td>
        </tr>
        <tr><td colspan="2">&nbsp;</td></tr>
		<tr>
            <td align="left">
                <strong>{$lL.__file_name__}</strong>
            </td>
			<td align="left">
                <input type="text" id="fname" name="fname" value="Grid_Export_{$smarty.now}.xls" title="{$lL.__name_for_the_resulting_dumped_file__}" style="width:30em;">
            </td>
        </tr>
        </table>
        <hr style="margin:1em 0;">
        <div class="left">
            <small>{$lL.__exporting_data_might_take_a_few_minutes__once_you_submit_please__strong_be_patient__strong___}.</small>
        </div>
        <div class="right">
            <div class="buttons">
                {if $smarty.request.action=="print"}
                <button type="submit" name="submit_btn" class="button-circle" value="Print" title="{$lL.__print__}">{$lL.__print__}</button>
                {elseif $smarty.request.action=="export"}
                <button type="submit" name="submit_btn" class="button-circle" value="Export" title="{$lL.__export__}">{$lL.__export__}</button>
                {else}
                <!-- <button type="submit" name="submit_btn" class="button-circle" value="Print" title="{$lL.__print__}">{$lL.__print__}</button> -->
                <button type="submit" name="submit_btn" class="button-circle" value="Export" title="{$lL.__export__}">{$lL.__export__}</button>
                {/if}
            </div>
        </div>
    </form>
</div>