<script type="text/javascript">
$(document).ready(function(){
    
	$("#expdata form").ajaxForm({
		dataType: 'json',
        async: true,
		beforeSubmit: function() {
            $("#GenericDialog").block({ message: '{$smarty.const._BAR_WAIT_}' });
		},
		success: function (r) {
            $("#GenericDialog").block({ message: r.msg });
            if (r.sts) {
                setTimeout('$("#GenericDialog").dialog("close");location.href="'+r.url+'";', 1500);
            } else {
                setTimeout('$("#GenericDialog").unblock();', 3000);
            }
        },
        error: function (jqXHR) {
            handleXHRerror(jqXHR);
        }
	});

    $("#expdata input:text:visible:first").focus();

});
</script>
<div id="expdata">
    <h3>__LNG__Select export options and then submit__LNG__</h3>
    <div class="myhr"></div>
    <form action="/Export/grid2excel" method="POST" enctype="multipart/form-data">
    <input type="hidden" id="deffile" name="deffile" value="{$smarty.request.deffile}">
        <table>
		<tr>
            <td align="left">
                <strong>__LNG__Range__LNG__</strong>
            </td>
			<td align="left">
                <input type="radio" id="range_all" class="radio" name="range" value="ALL" checked="checked">&nbsp;__LNG__All__LNG__
                <input type="radio" id="range_cur" class="radio" name="range" value="Current" disabled="disabled">&nbsp;__LNG__Grid's Current Set__LNG__
            </td>
        </tr>
        <tr><td colspan="2">&nbsp;</td></tr>
        <tr><td colspan="2"><strong>__LNG__Available Export Sets__LNG__</strong></td></tr>
		<tr>
            <td align="left">
                &nbsp;
            </td>
			<td align="left">
                {foreach from=$expoconf key=desc item=qry}
                <input type="radio" id="eset_{$desc|sha1}" class="radio" name="eset" value="{$qry|base64_encode}" checked="checked" onclick="$('#fname').val('Grid_Export_{$smarty.now}.xls');">&nbsp;{$desc}
                {/foreach}
            </td>
        </tr>
        <tr><td colspan="2">&nbsp;</td></tr>
		<tr>
            <td align="left">
                <strong>__LNG__File Name__LNG__</strong>
            </td>
			<td align="left">
                <input type="text" id="fname" name="fname" value="Grid_Export_{$smarty.now}.xls" title="__LNG__Name for the resulting dumped file__LNG__" style="width:30em;">
            </td>
        </tr>
        </table>
        <hr style="margin:1em 0;">
        <div class="left">
            <small>__LNG__Exporting data might take a few minutes, once you submit please <strong>be patient</strong>__LNG__.</small>
        </div>
        <div class="right">
            <div class="buttons">
                <button type="submit" name="submit_btn" class="button-circle" value="Export" title="__LNG__Export__LNG__">__LNG__Export__LNG__</button>
            </div>
        </div>
    </form>
</div>