<div style="float:left;font-size:.8em;">
<div id="ttpnfo">
    {$ttpLabel} : {($smarty.now - $smarty.server.REQUEST_TIME) ? {$InProve_Smarty->sec2str($smarty.now - $smarty.server.REQUEST_TIME)} : "< 1 {$secLabel}"}
</div>
{if $bck2top!='no'}
<div id="bck2top">
    <a href="javascript:;" onclick="$('#east_panel').animate({ scrollTop: 0 }, 1000);"><span class="ui-icon ui-icon-arrow-1-n" style="float:left;"></span> {$topLabel}</a>
</div>
{/if}
</div>