<div style="float:left;font-size:.8em;">
<div id="ttpnfo">
    __LNG__TTP__LNG__ : {($smarty.now - $smarty.server.REQUEST_TIME) ? {$InProve_Smarty->sec2str($smarty.now - $smarty.server.REQUEST_TIME)} : "< 1 __LNG__second__LNG__"}
</div>
{if $bck2top!='no'}
<div id="bck2top">
    <a href="javascript:;" onclick="$('#east_panel').animate({ scrollTop: 0 }, 1000);"><span class="ui-icon ui-icon-arrow-1-n" style="float:left;"></span> __LNG__Top__LNG__</a>
</div>
{/if}
</div>