{include file="../skel/header.phtml"}
<!--External Includes-->
<script type="text/javascript" src="../jquery/addons/syntax/shCore.js"></script>
<script type="text/javascript" src="../jquery/addons/syntax/shAutoloader.js"></script>
<link href="../jquery/addons/syntax/css/shCore.css" rel="stylesheet" type="text/css" />
<link href="../jquery/addons/syntax/css/shThemeDefault.css" rel="stylesheet" type="text/css" />

<script type="text/javascript">
$(document).ready(function(){
    SyntaxHighlighter.autoloader(
        'sql  ../jquery/addons/syntax/shBrushSql.js',
        'php  ../jquery/addons/syntax/shBrushPhp.js',
        'xml  ../jquery/addons/syntax/shBrushXml.js',
        'css  ../jquery/addons/syntax/shBrushCss.js',
        'js   ../jquery/addons/syntax/shBrushJScript.js',
        'java ../jquery/addons/syntax/shBrushJava.js',
        'css  ../jquery/addons/syntax/shBrushCss.js',
        'rb   ../jquery/addons/syntax/shBrushRuby.js'
    );
    SyntaxHighlighter.all();
});
</script>

    <table align="center" width="100%" class="list-horizontal">
    {if $smarty.request.projguid}
    <tr>
		<td align="left" class="header first" scope="row">
			{$lL.__project__}
		</td>
		<td align="left" class="first">
			{$project.projabv}
		</td>
	</tr>
    {/if}
    <tr>
		<td align="left" class="header" scope="row" width="20%">
        {if $smarty.request.filename}
            {$lL.__file_name__}
        {else}
            {$lL.__content_description__}
        {/if}
		</td>
		<td align="left">
        {if $smarty.request.filehash}
            {$smarty.request.filename}
            <a class="pointer" style="float:right;" title="{$lL.__click_to_download_file__}" href="/Http/gitfile?projguid={$smarty.request.projguid}&filehash={$smarty.request.filehash}&filename={$smarty.request.filename}"><span class="ui-icon ui-icon-arrowstop-1-s"></span></a>
        {/if}
        {if $smarty.request.send_as}
            {$smarty.request.send_as}
            <a class="pointer" style="float:right;" title="{$lL.__click_to_download_file__} ({$InProve_Smarty->bytes2str({filesize(base64_decode($smarty.request.filename))})})" href="/Http/getfile?filename={$smarty.request.filename}&send_as={$smarty.request.send_as}"><span class="ui-icon ui-icon-arrowstop-1-s"></span></a>
        {/if}
		</td>
	</tr>
    </table>
    <pre type="syntaxhighlighter" class="brush: {$brush}">{$content}</pre>

{include file="../skel/footer.phtml"}